.ci/intellij.json

- turn off aspect tests on macs
- temporarily turn off set/depset enforcement in skylark
(until we build against rules_scala head)

Fix Bazel CI tests

---

README.md

The docs currently refer to using the jar as the plugin, however, it appears that we need to use the zip now which contains both the jar and the aspect. Using the current instructions to build/run the plugin do not work, however, using the zip does.
Also, it seems that the output is in `bazel-bin`, not `bazel-genfiles`

Updating docs to reference ijwb_bazel_zip

---

WORKSPACE

The currently used version of rules_scala contains deprecated Skylark constructs (namely the `+` operator on dicts) and will soon not be supported.

Update rules_scala to the latest version

---

README.md

The README was missing some info on how to build the plugin for CLion.
Secondly, keeping `ij_product` as `clion-latest` would result in the
plugin not loading on the latest CLion (2018.1.5). So, this PR also
informs the developer how to debug that.

README: Inform how to build for CLion

---

.bazelci/android-studio.yml
.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij.yml

Ubuntu 14.04 is about to be end-of-life and Bazel CI will stop supporting it shortly afterwards.
Context: https://groups.google.com/d/msg/bazel-dev/_D6XzfNkQQE/8TNKiNmsCAAJ

Don't test on Ubuntu 14.04

---

.bazelci/android-studio.yml
.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij.yml

I have migrated ubuntu1804 to use OpenJDK 11, because that's the default JDK for that distribution.
During the migration I noticed that you have tests that fail with OpenJDK 11, so I recommend to
disable them until they're fixed.
For your reference, here's the log: https://buildkite.com/bazel/intellij-plugin/builds/2057#45f59142-dd60-491c-94eb-155b965fb0a4

Disable tests on ubuntu1804 that don't work with JDK11

---

base/tests/utils/unit/com/google/idea/blaze/base/scope/ErrorCollector.java

Migrate from assertThat(foo).named("foo") to assertWithMessage("foo").that(foo).
(The exact change is slightly different in some cases, like when using custom subjects or check(), but it's always a migration from named(...) to [assert]WithMessage(...).)
named(...) is being removed.

Migrate from assertThat(foo).named("foo") to assertWithMessage("foo").that(foo).

---

golang/src/META-INF/go-contents.xml

Move go debugging extensions to bazel plugin.xml. Fixes #489.

Move go debugging extensions to bazel plugin.xml. Fixes #489.

---

base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Remove confusion with indefinite "Updating in-memory state".
outputTimingSummary emits nothing if sync happened too quickly,
the last line ends up being
"Updating in-memory state..."
that makes people think it is still ongoing.

Remove confusion with indefinite "Updating in-memory state".

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/prefetch/PrefetchService.java
base/src/com/google/idea/blaze/base/prefetch/PrefetchServiceImpl.java
base/src/com/google/idea/blaze/base/prefetch/PrefetchVcsSyncListener.java
base/tests/utils/unit/com/google/idea/blaze/base/prefetch/MockPrefetchService.java

Prefetch project files when base CL changes.
These days I'm commonly seeing code analysis blocked for minutes after syncing, while the IDE is busy refreshing all project files.

Prefetch project files when base CL changes.

---

aspect/artifacts.bzl
aspect/fast_build_info.bzl
aspect/intellij_info_impl.bzl

Add explicit depset to list conversions
Implicit conversions will be forbidden with upcoming
incompatible_depset_is_not_iterable change in Bazel.

Add explicit depset to list conversions

---

java/src/com/google/idea/blaze/java/libraries/BlazeSourceJarNavigationPolicy.java

Disable source jar navigation by default.
For now, just disable it under an experiment. If this doesn't cause problems, I'll remove it entirely in a later release.

Disable source jar navigation by default.

---

build_defs/build_defs.bzl

Address Bazel's --incompatible_depset_is_not_iterable in build_defs.bzl
Fixes https://github.com/bazelbuild/intellij/issues/529
With this change, the Bazel build is compatible with all flags listed in https://github.com/bazelbuild/intellij/issues/529#issue-417792349

Address Bazel's --incompatible_depset_is_not_iterable in build_defs.bzl

---

common/experiments/src/com/google/idea/common/experiments/ExperimentUsernameProvider.java
common/experiments/tests/unittests/com/google/idea/common/experiments/FeatureRolloutExperimentTest.java
testing/src/com/google/idea/testing/BlazeTestSystemPropertiesRule.java

Prefer SystemProperties.getUsername() or StandardSystemProperty.USER_NAME.value()
SystemProperties.getUsername() supports mocking via SystemProperties#setTestUserName,
so use it whenever code runs in the IDE and mock support makes sense.

Prefer SystemProperties.getUsername() or StandardSystemProperty.USER_NAME.value()

---

common/experiments/src/com/google/idea/common/experiments/FeatureRolloutExperiment.java
common/experiments/tests/unittests/com/google/idea/common/experiments/FeatureRolloutExperimentTest.java
common/experiments/tests/utils/unit/com/google/idea/common/experiments/MockExperimentService.java

Allow internal devs to disable specific rollout experiments by setting them to "disabled".

Allow internal devs to disable specific rollout experiments by setting them to "disabled".

---

javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptResolveScopeProvider.java

Separate typescript and javascript resolve scope.
Typescript should only resolve to other typescript files, javascript
should only resolve to other javascript files.

Separate typescript and javascript resolve scope.

---

base/src/com/google/idea/blaze/base/console/BlazeConsoleView.java

Don't set up filters as part of a post-startup activity, this only works if post-startup activities haven't already been run.

Don't set up filters as part of a post-startup activity, this only works if post-startup activities haven't already been run.

---

common/experiments/src/com/google/idea/common/experiments/ExperimentServiceImpl.java
common/experiments/src/com/google/idea/common/experiments/ExperimentsUtil.java
common/experiments/src/com/google/idea/common/experiments/FileExperimentLoader.java
common/experiments/tests/unittests/com/google/idea/common/experiments/ExperimentServiceImplTest.java

Improve performance retrieving experiment data
- keep a global cache of hashed keys
- never calculate experiments list synchronously, instead refresh list every 5 minutes.
This means users will need to start an experiment scope (e.g. by syncing), restart the IDE, or wait 5 minutes to see experiment changes, but that's an acceptable cost.

Improve performance retrieving experiment data

---

clwb/src/com/google/idea/blaze/clwb/run/BlazeGDBServerProvider.java

Run gdbserver script under bash manually. Fixes #494.
CLion removes the executable permission on the gdbserver script if the
plugin is installed through the marketplace.

Run gdbserver script under bash manually. Fixes #494.

---

base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java
base/src/com/google/idea/blaze/base/run/PendingRunConfigurationContext.java
base/src/com/google/idea/blaze/base/run/confighandler/PendingTargetRunConfigurationHandler.java
base/src/com/google/idea/blaze/base/run/producers/TestContext.java

Refactor PendingRunConfigurationContext API.
Moves all of the asynchronous assumptions of
PendingRunConfigurationContext to implementation.
Now PendingRunConfigurationContext can either be asynchronous or
require user action to resolve.

Refactor PendingRunConfigurationContext API.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/run/producers/AllInPackageTestContextProvider.java
base/tests/integrationtests/com/google/idea/blaze/base/run/producer/AllInPackageTestContextProviderTest.java

Remove all-in-package run config producer -- move to TestContextProvider API.

Remove all-in-package run config producer -- move to TestContextProvider API.

---

aswb/src/com/google/idea/blaze/android/cppimpl/debug/BlazeAutoAndroidDebugger.java

Don't use BlazeAutoAndroidDebugger by default.

Don't use BlazeAutoAndroidDebugger by default.

---

WORKSPACE
aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/ccbinary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/cclibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/cctest/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/cctoolchain/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/coptsmakevars/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/alias/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/artifacts/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/build/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/noide/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/tags/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/dependencies/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/filteredgenjar/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/genjars/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javabinary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javaplugin/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javatest/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/python/pybinary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/python/pylibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/python/pytest/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalabinary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalalibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalamacrolibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalatest/BUILD

Use a consistent truth version for third_party aspect tests

Use a consistent truth version for third_party aspect tests

---

base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java

Extend BlazeIssueParser to parse JSC compiler output
JSC error messages show up as:
path/to/my/file.js:12: WARNING - Message
This CL extends the existing CompileParser to:
- Accept case insensitive message types
- And accept - as an alternative to : as a separator for the message

Extend BlazeIssueParser to parse JSC compiler output

---

aswb/src/com/google/idea/blaze/android/run/BlazeAndroidRunConfigurationHandler.java
aswb/src/com/google/idea/blaze/android/run/BlazeAndroidRunConfigurationValidationUtil.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryRunConfigurationHandler.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationHandler.java

Ensure target is up to date in android run config handler.
Due to the way blaze run configuration editors update the underlying
configuration state, it's possible for the configuration referenced in
android run config handlers to be out of date. This can cause tricky
side-effects such as incorrect build target being build during test.

Ensure target is up to date in android run config handler.

---

aspect/intellij_info_impl.bzl

Fix --incompatible_depset_is_not_iterable for Go projects.

Fix --incompatible_depset_is_not_iterable for Go projects.

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java

Fix hang running herb/blaze query from a read lock

Fix hang running herb/blaze query from a read lock

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/model/BlazeProjectData.java
base/src/com/google/idea/blaze/base/model/ProjectTargetData.java
base/src/com/google/idea/blaze/base/model/RemoteOutputArtifacts.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceState.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
base/tests/utils/unit/com/google/idea/blaze/base/model/MockBlazeProjectDataBuilder.java
proto/project_data.proto

Cleanup: package target data together as a top-level BlazeProjectData message.
The only reason to put it in SyncState was to hide the aspect-specific implementation details, back when there was a possibility of implementing the IDE-blaze interface differently.
We've well and truly settled on using an aspect, and the ProjectTargetData state already exposes BlazeIdeInterfaceState outside the 'aspect' package, so time to move it out of SyncState.

Cleanup: package target data together as a top-level BlazeProjectData message.

---

java/BUILD
third_party/java/jdk/BUILD

Stop depending on deprecated @local_jdk//:langtools for tools.jar. (bazelbuild/intellij PR import #968)
This removes the warning when building `//java:fast_build_javac` and `//java:jdk_tools_lib`:
```
$ bazel build //java:jdk_tools_lib //java:fast_build_javac
WARNING: /Users/jingwen/code/intellij/java/BUILD:178:1: in java_import rule //java:jdk_tools_jar: target '//java:jdk_tools_jar' depends on deprecated target '@local_jdk//:langtools': Don't depend on targets in the JDK workspace; use @bazel_tools//tools/jdk:current_java_runtime instead (see https://github.com/bazelbuild/bazel/issues/5594)
```

Stop depending on deprecated @local_jdk//:langtools for tools.jar. (bazelbuild/intellij PR import #968)

---

base/src/com/google/idea/blaze/base/wizard2/GenerateFromBuildFileSelectProjectViewOption.java

Project import: Don't include targets in template when generating from a BUILD file.

Project import: Don't include targets in template when generating from a BUILD file.

---

base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsConfigurable.java

Don't apply UI font scaling twice in bold Blaze tool window popup settings.

Don't apply UI font scaling twice in bold Blaze tool window popup settings.

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeApkBuildStepMobileInstall.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepNormalBuild.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperBep.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperProvider.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginDeployer.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BuildPluginBeforeRunTaskProvider.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Refactor BEP readers to pass through ParsedBepOutput directly.
Also adds a ParsedBepOutput#getPerTargetOutputArtifacts to get transitive outputs associated with a target.

Refactor BEP readers to pass through ParsedBepOutput directly.

---

base/src/com/google/idea/blaze/base/model/RemoteOutputArtifacts.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java

Don't keep tracking old remote outputs when they've been replaced by local versions in a more recent build.

Don't keep tracking old remote outputs when they've been replaced by local versions in a more recent build.

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java

Fix query building for directory to target provider.
If the root directory's relative path is the empty string, the string formatting will result in "///...", which is an incorrect target.

Fix query building for directory to target provider.

---

java/src/com/google/idea/blaze/java/sync/jdeps/JdepsFileReader.java

Fix "Multiple entries with same key" error when syncing an updated project.

Fix "Multiple entries with same key" error when syncing an updated project.

---

base/src/com/google/idea/blaze/base/command/buildresult/LocalFileOutputArtifact.java

Don't canonicalize file paths when comparing output artifacts.

Don't canonicalize file paths when comparing output artifacts.

---

aswb/src/com/google/idea/blaze/android/sync/model/idea/BlazeAndroidModel.java
aswb/src/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncer.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/model/idea/BlazeAndroidModelTest.java

Upstream ag/6237454
Original commit message: 
Currently, BlazeAndroidModel recomputes a module's application ID from
its Android manifest each time getApplicationId() is called. When the
user tries to attach the debugger to a running Android target,
AndroidProcesssChooserDialog ends up calling this method on the EDT for
each module in the project. For large projects, this can mean hundreds
of file operations and sometimes results in UI freezes.
This CL resolves the issue by pre-computing the application IDs during
Blaze sync. As a result, changes to package names in any
AndroidManifest.xml won't affect application IDs until after the project
has been synced.

Upstream ag/6237454

---

aswb/sdkcompat/as34/com/google/idea/blaze/android/run/DefaultActivityLocatorCompat.java
aswb/sdkcompat/as35/com/google/idea/blaze/android/run/DefaultActivityLocatorCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/DefaultActivityLocatorCompat.java
aswb/src/META-INF/aswb.xml
aswb/src/com/google/idea/blaze/android/manifest/ManifestParser.java
aswb/src/com/google/idea/blaze/android/manifest/ParsedManifestService.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryApplicationIdProvider.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryApplicationLaunchTaskProvider.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryNormalBuildRunContext.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeDefaultActivityLocator.java
aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeAndroidBinaryMobileInstallRunContext.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeAndroidDeployInfo.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestApplicationIdProvider.java
aswb/src/com/google/idea/blaze/android/run/test/StockAndroidTestLaunchTask.java
aswb/src/com/google/idea/blaze/android/sync/BlazeAndroidSyncPlugin.java
aswb/src/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncer.java
aswb/tests/unittests/com/google/idea/blaze/android/manifest/ManifestParserTest.java

Fetch common manifest attributes directly from manifest file.
Currently the ManifestParser parses the manifest using PSI APIs, which
requires that the generated manifest be first refreshed in the VFS.
These VFS refreshes sometimes take too long due to previously queued
refreshes from other sources and cannot proceed until previous refreshes
are flushed.
We work around this issue by changing ManifestParser to use Java file
APIs to read the up-to-date file and implementing our own logic to
extract the few attributes we need from the manifest.
The new ManifestParser does not perform any PSI or VFS related 
operations and therefore doesn't block in the refresh queue.
ManifestParser is now a functional utility class that keeps no state.
ParsedManifests are cached through ParsedManifestService.

Fetch common manifest attributes directly from manifest file.

---

base/src/com/google/idea/blaze/base/settings/ui/ProjectViewUi.java

Simplify blazeproject wizard document creation, and support undo/redo.
This doesn't seem to impair our language or autocompletion support at all,
and also doesn't trigger any errors when using undo. It should be safe,
since LanguageTextField#createDocument does the same thing the
"File and Code Templates" settings editor does under the hood.

Simplify blazeproject wizard document creation, and support undo/redo.

---

base/src/com/google/idea/blaze/base/console/BlazeConsoleView.java

Focus Blaze console editor when tool window is focused.
This should already happen by default, but there's a bug in
RunnerLayoutUi's RunnerContentUi. It wraps our content in a GridImpl,
but doesn't override TabInfo's preferred focus component to be either
the root content, or the content's preferred focus component.
So GridImpl gets to decide what should be focused, and always picks
the first empty placeholder cell...

Focus Blaze console editor when tool window is focused.

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypescriptSyncPlugin.java

Allow using typescript support in WebStorm and GoLand externally.

Allow using typescript support in WebStorm and GoLand externally.

---

golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java

Invalid cached PSI files in go packages if they become invalid.

Invalid cached PSI files in go packages if they become invalid.

---

base/src/com/google/idea/blaze/base/dependencies/TargetInfo.java
base/src/com/google/idea/blaze/base/ideinfo/TargetIdeInfo.java
base/src/com/google/idea/blaze/base/run/TestTargetHeuristic.java
base/tests/integrationtests/com/google/idea/blaze/base/run/TestTargetHeuristicTest.java

When matching test targets to sources, prefer the most recently synced project targets.

When matching test targets to sources, prefer the most recently synced project targets.

---

base/src/com/google/idea/blaze/base/async/process/ExternalTask.java

Shell-encode ExternalTask command arguments displayed in Blaze Console.

Shell-encode ExternalTask command arguments displayed in Blaze Console.

---

intellij_platform_sdk/BUILD

Remove out-of-package usages of //third_party/jetbrains/plugin_api:plugin_api_internal

Remove out-of-package usages of //third_party/jetbrains/plugin_api:plugin_api_internal

---

java/src/com/google/idea/blaze/java/fastbuild/FastBuildInfo.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildParameters.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildState.java
java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestEnvironmentCreator.java
java/tests/integrationtests/com/google/idea/blaze/java/fastbuild/FastBuildChangedFilesServiceTest.java

Fast run/debug: don't get BlazeInfo from the project data, which might be using a different blaze binary.

Fast run/debug: don't get BlazeInfo from the project data, which might be using a different blaze binary.

---

base/src/com/google/idea/blaze/base/run/processhandler/ScopedBlazeProcessHandler.java
base/src/com/google/idea/blaze/base/util/ProcessGroupUtil.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java

Launch processes in a new session groups so that signals sent to child
processes do not propagate.

Launch processes in a new session groups so that signals sent to child

---

base/src/com/google/idea/blaze/base/command/buildresult/BepArtifactData.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/LocalFileOutputArtifact.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Improve performance parsing BEP output during sync.
We were iterating over the graph of file sets once per top-level target. If most top-level targets have a significant fraction of the artifacts in their transitive closure, this scales very badly.

Improve performance parsing BEP output during sync.

---

base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java

Fix for the NPEs when blaze problems tree is empty
This CL adds a fix (possibly temporary) to handle empty Blaze problems 
trees in the Blaze Problems tool window. Looks like the problem started 
to appear after update to Intellij 192.

Fix for the NPEs when blaze problems tree is empty

---

aspect/intellij_info_impl.bzl
proto/intellij_ide_info.proto

Expose attributes required for android instrumentation tests in aspect
Currently Android Studio does not support running android instrumentation
tests of the target kind android_instrumentation_test due to lack of
sufficient information about the targets and their instrumentation 
dependencies. 
To support running android_instrumentation_test from Android Studio, 
android_binary#instruments and android_instrumentation_test#test_app
attributes are required. These CL exposes those two attributes through
AndroidIdeInfo and AndroidInstrumentationInfo aspects.

Expose attributes required for android instrumentation tests in aspect

---

base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/io/FileAttributeScanner.java

BEP parsing: don't return duplicates in 'getOutputGroupArtifacts'.
Fixes a regression debugging java binary targets in the latest release.

BEP parsing: don't return duplicates in 'getOutputGroupArtifacts'.

---

testing/test_defs.bzl

Enable legacy PicoContainer behavior in 2019.2 tests, to match production.

Enable legacy PicoContainer behavior in 2019.2 tests, to match production.

---

aspect/testing/rules/intellij_aspect_test_fixture.bzl

Rename some language test source files to avoid being detected by tools.

Rename some language test source files to avoid being detected by tools.

---

aswb/src/com/google/idea/blaze/android/sync/BlazeAndroidSyncPlugin.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/BlazeAndroidSyncPluginTest.java

Set android SDK from project view if one doesn't exist after sync.
Currently, a directory only sync will not update the project's SDK.
In a large android project, this means the android SDK won't be set
until the next "real" sync succeeds. The SDK is required for many
IDE functionalities to work, such as AdbService and attaching to 
devices.
Normally info regarding a project's SDK is retained between IDE
restarts.  However when the user imports a new project, they face
a special situation where project SDK is not available AND the init
sync usually takes a very long time. When this happens, the user won't
be able to use IDE functionalities that require an android SDK.
This CL changes BlazeAndroidSyncPlugin#updateProjectSdk to set 
the project's SDK from project view if:
1. There is no SDK …

Set android SDK from project view if one doesn't exist after sync.

---

python/src/com/google/idea/blaze/python/PythonPluginUtils.java
python/src/com/google/idea/blaze/python/sync/AlwaysPresentPythonSyncPlugin.java

Fix python support for GoLand, PyCharm.
Still doesn't behave well for IDEs which don't support python, but we don't support those IDEs, and it's also relatively harmless -- it will just incorrectly show 'python' as a possible additional language.

Fix python support for GoLand, PyCharm.

---

java/src/com/google/idea/blaze/java/run/producers/NonBlazeProducerSuppressor.java

Catch wrapped class not found exception in 2019.2

Catch wrapped class not found exception in 2019.2

---

base/src/com/google/idea/blaze/base/sync/sharding/SuggestBuildShardingNotification.java

Make it clearer what happens when the 'shard sync' suggestion notification hyperlink is clicked.

Make it clearer what happens when the 'shard sync' suggestion notification hyperlink is clicked.

---

intellij_platform_sdk/build_defs.bzl

Migrate clion 2019.2 to beta

---

aswb/tests/integrationtests/com/google/idea/blaze/android/AswbGotoDeclarationTest.java

Disable AswbGotoDeclarationTest as it fails with 3.6 C9

Disable AswbGotoDeclarationTest as it fails with 3.6 C9

---

base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java

Fix target outputs being dropped when sharding sync

Fix target outputs being dropped when sharding sync

---

aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java

JarFilter: handle duplicate jar entries across JavaInfo outputs

JarFilter: handle duplicate jar entries across JavaInfo outputs

---

clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java

Always attach the console builder to CLion run/debug sessions.

Always attach the console builder to CLion run/debug sessions.

---

aspect/intellij_info_impl.bzl

Flatten depset to fix incompatibility with --incompatible_depset_is_not_iterable

Flatten depset to fix incompatibility with --incompatible_depset_is_not_iterable

---

README.md

The current readme doesn't really show how `-beta` and `-latest` defines work, and don't even note that `<IDE>-beta` exists as a possible `ij_product` definition.
Pure documentary change.

Fix a bit of the language in the readme, to highlight -beta versions

---

aspect/java_classpath.bzl

Remove unused load statements from .bzl files
After transitive loads have been disabled in Blaze, unused load statements have
no effect (besides not useful memory consumption).
The CL has been created automatically by calling `buildifier --lint=fix --warnings=load` on all .bzl files.
The following additional command were run on all affected files to clean them up:

Remove unused load statements from .bzl files

---

aspect/fast_build_info.bzl
java/src/com/google/idea/blaze/java/fastbuild/FastBuildBlazeData.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildCompilerFactoryImpl.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildJavac.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildJavacImpl.java
java/tests/unittests/com/google/idea/blaze/java/fastbuild/FastBuildCompilerFactoryImplTest.java
proto/fast_build_info.proto

Fix fast run/debug manual compilation failing with mismatched java versions.
There were two problems:
- the FastBuildJavac interface included classes which changed between java versions, so we couldn't map between the two instances in the classpath
- we weren't specifying the boot classpath during compilation, so if core jdk classes referenced in the files being compiled had changed, recompilation failed

Fix fast run/debug manual compilation failing with mismatched java versions.

---

base/src/com/google/idea/blaze/base/async/process/ExternalTask.java
base/tests/unittests/com/google/idea/blaze/base/async/process/ExternalTaskImplTest.java

Allow customizing the $PATH we use in ExternalTask.

Allow customizing the $PATH we use in ExternalTask.

---

intellij_platform_sdk/build_defs.bzl

Extract a custom rule for our file templating, and use it to simplify our IJwB build rules.
Removes a lot of duplication in the build rules.

Extract a custom rule for our file templating, and use it to simplify our IJwB build rules.

---

intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Create intellij-canary and intellij-ue-canary to bring in EAP releases
https://blog.jetbrains.com/idea/2019/09/intellij-idea-starts-2019-3-early-access-program/

Create intellij-canary and intellij-ue-canary to bring in EAP releases

---

WORKSPACE

Update IJ CE 2019.2 (and drop in the mac version)

Update IJ CE 2019.2 (and drop in the mac version)

---

WORKSPACE
javascript/tests/integrationtests/com/google/idea/blaze/typescript/BlazeTypescriptGotoDeclarationHandlerTest.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/OldBlazeTypescriptGotoDeclarationHandlerTest.java

Update IJ UE 2019.2 (and drop in the mac version)

Update IJ UE 2019.2 (and drop in the mac version)

---

java/src/com/google/idea/blaze/java/libraries/BlazeAttachSourceProvider.java

Improve automatic source jar redirection.
The plugin now just attaches the source jar automatically. Once that's done, IntelliJ will automatically navigate to the correct position in the source jar.

Improve automatic source jar redirection.

---

aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationHandler.java

Guard against NPE when validating instrumentation binary.
Validating a android test run config in ASwB involves obtaining the
instrumentation binary of the test through project target map.  It's
possible for a run config to have stale information and cause it to
NPE when a matching target can't be found.

Guard against NPE when validating instrumentation binary.

---

aswb/src/com/google/idea/blaze/android/sdk/BlazeSdkProviderImpl.java
aswb/src/com/google/idea/blaze/android/sdk/MockBlazeSdkProvider.java
aswb/src/com/google/idea/blaze/android/sync/sdk/SdkUtil.java

Check if selected sdk is valid during sync
Sdk manager does not update sdk if user just select to install/ uninstall some
sdks. What's more, sdk may not be removed as a whole. When we retrieve sdk
from jdk table, it may get a sdk without path to jar file/ resource file. To
avoid this case, this patch will double check whether path of android.jar/
resource folder existed. If the information is missing, we will remove current
sdk and try to re-add it with correct information.

Check if selected sdk is valid during sync

---

ijwb/BUILD

Remove unused load statements from BUILD files
The CL has been created automatically by calling `buildifier --lint=fix
--warnings=load` on all BUILD files.
The following additional command were run on all affected files to clean them up:

Remove unused load statements from BUILD files

---

base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java

Fix blaze sync spuriously aborting if a shard had an OOME but was then successfully retried.

Fix blaze sync spuriously aborting if a shard had an OOME but was then successfully retried.

---

base/src/com/google/idea/blaze/base/actions/BuildFileUtils.java
base/tests/integrationtests/com/google/idea/blaze/base/actions/BuildFileUtilsTest.java

Add more flexible BUILD file target name matching.
kt_jvm_library currently produces java IDE info with target names
plus a "_DO_NOT_DEPEND_JVM" at the end. This breaks BUILD file target
name matching.  
This CL fixes issues like these by augmenting BuildFileUtils#findBuildTarget
to look for a macro with matching prefix when the target isn't in the BUILD
file.
When a label is calculated, #findBuildTarget first checks to see if the
label actually points to a target in the corresponding BUILD file.
If it doesn't, then it iterates through the named macros in the BUILD
file until it finds one with name matching the beginning of the label.
The new macro prefix matching mechanism is enabled by the flag 
"buildfile.macro.prefix.matching.enabled"

Add more flexible BUILD file target name matching.

---

base/src/com/google/idea/blaze/base/dependencies/DependencyFinder.java
base/tests/integrationtests/com/google/idea/blaze/base/dependencies/DependencyFinderTest.java

Add DependencyFinder utility class to get the dependencies of a target using the Blaze project data.

Add DependencyFinder utility class to get the dependencies of a target using the Blaze project data.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java
base/src/com/google/idea/blaze/base/query/BlazeQueryOutputBaseProvider.java

Use a custom output base for background blaze query invocations.

Use a custom output base for background blaze query invocations.

---

golang/src/META-INF/go-contents.xml
golang/src/com/google/idea/blaze/golang/run/BlazeDlvPositionConverter.java
golang/tests/unittests/com/google/idea/blaze/golang/run/BlazeDlvPositionConverterTest.java

Fix go debug path resolving.
1. Move the extension first. There's a new position converter
extension that moved in front of the blaze one.
2. Fix resolving to GOROOT paths.

Fix go debug path resolving.

---

aswb/src/com/google/idea/blaze/android/cppimpl/BlazeNdkSupportEnabler.java
aswb/src/com/google/idea/blaze/android/manifest/ParsedManifestService.java
aswb/src/com/google/idea/blaze/android/projectsystem/BlazeProjectSystemSyncManager.java
aswb/src/com/google/idea/blaze/android/sync/BlazeAndroidSyncListener.java
base/src/com/google/idea/blaze/base/dependencies/ExternalFileProjectManagementHelper.java
base/src/com/google/idea/blaze/base/run/BlazeRunConfigurationSyncListener.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncModificationTracker.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/SimpleSyncListenerService.java
base/src/com/google/idea/blaze/base/sync/SyncCache.java
base/src/com/google/idea/blaze/base/sync/SyncListener.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java
base/src/com/google/idea/blaze/base/sync/projectview/WorkspaceFileFinderImpl.java
base/src/com/google/idea/blaze/base/sync/status/BlazeSyncStatusListener.java
base/tests/unittests/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManagerTest.java
cpp/src/com/google/idea/blaze/cpp/BulkSymbolTableBuildingChangeListener.java
golang/src/com/google/idea/blaze/golang/sync/BlazeGoSdkUpdater.java
java/src/com/google/idea/blaze/java/libraries/DetachAllSourceJarsAction.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfigServiceImpl.java
kotlin/src/com/google/idea/blaze/kotlin/sync/BlazeKotlinSyncPlugin.java

Associate an ID with each blaze build during sync, and communicate it to SyncListener along with the synced targets.

Associate an ID with each blaze build during sync, and communicate it to SyncListener along with the synced targets.

---

base/BUILD
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/dependencies/MissingDependencyData.java
base/src/com/google/idea/blaze/base/dependencies/MissingDependencyTargetProvider.java
base/src/com/google/idea/blaze/base/dependencies/MissingDependencyTargetProviderImpl.java
base/tests/integrationtests/com/google/idea/blaze/base/dependencies/MissingDependencyTargetProviderImplTest.java

Add MissingDependencyTargetProvider to find the Blaze targets that are missing from the dependency set of the rules building a given source file.

Add MissingDependencyTargetProvider to find the Blaze targets that are missing from the dependency set of the rules building a given source file.

---

aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryApplicationIdProvider.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeAndroidDeployInfo.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestApplicationIdProvider.java
aswb/src/com/google/idea/blaze/android/run/test/ConnectBlazeTestDebuggerTask.java
aswb/tests/unittests/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryApplicationIdProviderTest.java
aswb/tests/unittests/com/google/idea/blaze/android/run/test/BlazeAndroidTestApplicationIdProviderTest.java

Use ManifestParser.ParsedManifest in BlazeAndroidDeployInfo
Currently BlazeAndroidDeployInfo is a wrapper around AndroidDeployInfo
proto and contains it's own extraction logic for manifest values. This
is unecessarily complex and inflexible, so this CL extracts the logic
out of BlazeAndroidDeployInfo so it's now just a data-class. This added
flexibility also aids the upcoming android_instrumentation_test support
feature, where manifests values are extracted differently depending on
the build step.

Use ManifestParser.ParsedManifest in BlazeAndroidDeployInfo

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildEventStreamProvider.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperBep.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java

BuildRabbit syncing: stream BEP output in batches, don't read it all into memory at once.

BuildRabbit syncing: stream BEP output in batches, don't read it all into memory at once.

---

aswb/sdkcompat/as35/com/google/idea/blaze/android/run/binary/StartupProfilerSupport.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/binary/StartupProfilerSupport.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryProgramRunner.java

Fix startup profiling support for ASwB 3.6
Currently startup profiling doesn't work in ASwB 3.6 dev branch
because BlazeAndroidBinaryProgramRunner doesn't support it, this CL
fixes that.

Fix startup profiling support for ASwB 3.6

---

base/src/META-INF/blaze-base.xml

Remove reference to MissingDependencyTargetProviderImpl in the plug-in configuration file which has been previously removed.

Remove reference to MissingDependencyTargetProviderImpl in the plug-in configuration file which has been previously removed.

---

aswb/BUILD
aswb/src/META-INF/aswb.xml
aswb/src/com/google/idea/blaze/android/sdk/MockBlazeSdkProvider.java
aswb/src/com/google/idea/blaze/android/sync/sdk/AndroidSdkFromProjectView.java
aswb/src/com/google/idea/blaze/android/sync/sdk/SdkUtil.java
aswb/tests/integrationtests/com/google/idea/blaze/android/AswbGotoDeclarationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/AswbMergedManifestTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeModuleSystemDependentLibrariesIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeModuleSystemExternalDependencyIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/projectsystem/BlazeSampleDataDirectoryProviderTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/sync/AndroidSyncTest.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/BlazeAndroidSyncPluginTest.java
aswb/tests/utils/integration/com/google/idea/blaze/android/BlazeAndroidIntegrationTestCase.java
aswb/tests/utils/integration/com/google/idea/blaze/android/MockSdkUtil.java
aswb/tests/utils/unit/com/google/idea/blaze/android/LightWeightMockSdkUtil.java
base/tests/utils/unit/com/google/idea/blaze/base/TestUtils.java

Create test case to test sync with BlazeSdkProivder
Previous, we mock sdk by using Mockito and MockBlazeSdkProvider which is quick but bypass BlazeSdkProivder. So we cannot verify the part that IDE retrieve Sdk from jdk table.

Create test case to test sync with BlazeSdkProivder

---

base/src/com/google/idea/blaze/base/lang/buildfile/references/BuildReferenceManager.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/FilePathCompletionTest.java

BUILD label autocomplete: stop directory traversal at blaze packages.

BUILD label autocomplete: stop directory traversal at blaze packages.

---

aspect/java_classpath.bzl

Work around for JavaInfo constructor not filling in compilation_info.

Work around for JavaInfo constructor not filling in compilation_info.

---

base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java

Sync sharding: separate shard size default to keep the build invocation below ARG_MAX

Sync sharding: separate shard size default to keep the build invocation below ARG_MAX

---

aspect/java_classpath.bzl

Fall back to full transitive set of runtime jars if JavaInfo compilation info isn't filled in.

Fall back to full transitive set of runtime jars if JavaInfo compilation info isn't filled in.

---

aswb/src/com/google/idea/blaze/android/manifest/ParsedManifestService.java
aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeApkBuildStepMobileInstall.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepInstrumentation.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepNormalBuild.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestProgramRunner.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunContextBase.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepInstrumentationIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/targetmapbuilder/NbTargetMapUtilsTest.java
aswb/tests/unittests/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelperTest.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbAndroidInstrumentationTestTarget.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbAndroidTarget.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbTargetMapUtils.java
base/src/com/google/idea/blaze/base/ideinfo/AndroidIdeInfo.java
base/src/com/google/idea/blaze/base/ideinfo/AndroidInstrumentationInfo.java
base/src/com/google/idea/blaze/base/ideinfo/TargetIdeInfo.java

Add support for running/debugging android_instrumentation_test targets.
The following are required to support android_instrumentation_test:
* BlazeApkBuildStepInstrumentation is added to specifically handle android_instrumentation_test targets. Doing this also simplifies BlazeApkBuildStepNormalBuild as it doesn't have to have separate logic for building multiple APKs just for instrumentation tests.
* BlazeApkDeployInfoProtoHelper has been updated to handle two scenarios: normal deployment, and instrumentation test deployment.  Normal deployment handles existing usages, while instrumentation test deployment handles the case where there are two deploy info files to process (info for both test and target APKs).
* Finally, BlazeAndroidTestProgramRunner is updated to support …

Add support for running/debugging android_instrumentation_test targets.

---

java/src/com/google/idea/blaze/java/fastbuild/FastBuildChangedFilesService.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildCompilerFactoryImpl.java
sdkcompat/v191/BUILD
sdkcompat/v191/com/intellij/serviceContainer/NonInjectable.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/intellij/serviceContainer/NonInjectable.java

Do not inject services via the constructor
One restriction with sdk v193 is that services should not be injected
via the constructor. There is also a new annotation (@NonInjectable)
that needs to be placed on constructors that are not supposed to be
used by picocontainers.

Do not inject services via the constructor

---

sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/python/PyInspectionExtensionCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/python/PythonVisitorFilterCompat.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/python/PyInspectionExtensionCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/python/PythonVisitorFilterCompat.java
sdkcompat/v193/BUILD
sdkcompat/v193/com/google/idea/sdkcompat/python/PyInspectionExtensionCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/python/PythonVisitorFilterCompat.java

Fix python plugin to work with IJ v193
* PyUnresolvedReferenceSkipperExtPoint has been removed in favor of
PyInspectionExtension
* PythonVisitorFilter has moved from com.jetbrains.python.inspections to
com.jetbrains.python.psi

Fix python plugin to work with IJ v193

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeApkBuildStepMobileInstall.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepNormalBuild.java

Add blaze integration tests for building/parsing android deploy info.
Currently there are no tests that verify deploy info protos are built/parsed
correctly.  These deploy info protos are required for ASwB to correctly
perform many run/debug functions such as debugger attachment, APK deployment,
etc.
This CL adds tests for building and parsing android deploy info for android_binary
targets from both normal build and mobile-install scenarios. 
* BlazeApkDeployInfoProtoHelper has been simplified to static utilities.  It didn't make sense for a proto helper to run blaze-info just to fetch the exec root anyway.
* BlazeApkBuildStepNormalBuild and BlazeApkBuildStepMobileInstall have been modified to obtain exec root from blaze project data instead of re-running blaze info.
* …

Add blaze integration tests for building/parsing android deploy info.

---

base/src/com/google/idea/blaze/base/console/BlazeConsoleView.java

Hide tingle single "Tab" tab from current Blaze console

Hide tingle single "Tab" tab from current Blaze console

---

base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectHelper.java
base/src/com/google/idea/blaze/base/lang/buildfile/quickfix/DeprecatedLoadQuickFix.java

Fix read/write lock freeze categorization with JDK 11.

Fix read/write lock freeze categorization with JDK 11.

---

clwb/src/com/google/idea/blaze/clwb/run/producers/NonBlazeProducerSuppressor.java
intellij_platform_sdk/BUILD.clion193

clion-2019.3 compat: Support test frameworks being in separate plugins

clion-2019.3 compat: Support test frameworks being in separate plugins

---

sdkcompat/v191/com/google/idea/sdkcompat/python/PythonCodeStyleServiceAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/python/PythonCodeStyleServiceAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/python/PythonCodeStyleServiceAdapter.java

clion 2019.3 compat: IMPORT_GROUP_BEGIN move from PyBlock to PythonCodeStyleService

clion 2019.3 compat: IMPORT_GROUP_BEGIN move from PyBlock to PythonCodeStyleService

---

WORKSPACE

Update bazel-integration-testing to prepare for Bazel 2.0.

Update bazel-integration-testing to prepare for Bazel 2.0.

---

sdkcompat/v191/com/google/idea/sdkcompat/platform/PluginInstallerCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/platform/PluginInstallerCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/platform/PluginInstallerCompat.java

2019.3 sdkcompat: Workaround for change to PluginInstaller.prepareToUninstall()

2019.3 sdkcompat: Workaround for change to PluginInstaller.prepareToUninstall()

---

aswb/tests/integrationtests/com/google/idea/blaze/android/functional/InstrumentationTestTargetIntegrationTest.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbAndroidInstrumentationTestTarget.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbAndroidTarget.java
base/src/com/google/idea/blaze/base/ideinfo/AndroidIdeInfo.java
base/src/com/google/idea/blaze/base/ideinfo/AndroidInstrumentationInfo.java
base/src/com/google/idea/blaze/base/ideinfo/TargetIdeInfo.java

Update IDE info classes to support android_instrumentation_test.
android_ide_info now exposes information required to support
android_instrumentation_test.  This CL does the necessary IDE side
changes to consume these newly exposed aspect fields.
TEST INFRA:
Added new NB target map builders for android_instrumentation_test.

Update IDE info classes to support android_instrumentation_test.

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeApkBuildStepMobileInstall.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeAndroidRunConfigurationRunner.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStep.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepNormalBuild.java

Move scoping logic out of build steps.
Currently, every build step has a section that creates a scoped task and
starts itself in a progressive task with indicator.  
These sections are identical, the scoping logic adds annoying nesting
in an already crowded method, and the future task logic makes these 
build step classes hard to test.  It should be extracted out to the caller 
where it's better suited anyway.  
TEST:
I've manually verified that both mobile-install and normal build works the same way as before.

Move scoping logic out of build steps.

---

plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfigurationType.java

Remove comments from vmoptions before using it inside a run config
Merges https://github.com/bazelbuild/intellij/pull/1439 from mtoader.

Remove comments from vmoptions before using it inside a run config

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeApkBuildStepMobileInstall.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepNormalBuild.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepMobileInstallIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepNormalBuildIntegrationTest.java
aswb/tests/unittests/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelperTest.java
base/src/com/google/idea/blaze/base/async/process/ExternalTask.java
base/src/com/google/idea/blaze/base/async/process/ExternalTaskProvider.java

Add tests for blaze APK build steps and BlazeApkDeployInfoProtoHelper.
There are currently no test coverage for blaze APK build steps. The
build steps are a critical part of run/deploy pipeline and regressions
in this area are guaranteed to be severe.
This CL adds tests tha cover the existing build steps.  This CL also
includes updates to BlazeApkDeployInfoProtoHelper to make it more
testable, as well as a unit test for the proto helper itself.
Expanded visibility on some blaze-intellij classes because they were
required to write these tests.

Add tests for blaze APK build steps and BlazeApkDeployInfoProtoHelper.

---

base/src/com/google/idea/blaze/base/io/FileOperationProvider.java
java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestEnvironmentCreator.java

Allow insecure delete for test resources when configured
Fast-run/debug fails when using a file system that does not support secure deletion. This is the case when we connect over an SSHFS, for example. This change provides configuration through a system property that allows insecure delete, in the sense described in [RecursiveDeleteOption#ALLOW_INSECURE](https://guava.dev/releases/23.0/api/docs/com/google/common/io/RecursiveDeleteOption.html#ALLOW_INSECURE). The default case in unchanged.

Allow insecure delete for test resources when configured

---

aspect/intellij_info_impl.bzl

Remove non-jars from JavaToolchainIdeInfo.
They get put into the jar cache (after renaming to .jar as part of the name
hashing) and causes compilation failures when put on the classpath.

Remove non-jars from JavaToolchainIdeInfo.

---

sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/util/CreateDesktopEntryActionCompat.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/util/CreateDesktopEntryActionCompat.java
sdkcompat/v193/BUILD
sdkcompat/v193/com/google/idea/sdkcompat/util/CreateDesktopEntryActionCompat.java

compat: CreateDesktopEntryAction no longer contains `getLauncherScript()` method in api193. It is replaced by `Restarter.getIdeStarter()`

compat: CreateDesktopEntryAction no longer contains `getLauncherScript()` method in api193. It is replaced by `Restarter.getIdeStarter()`

---

testing/testcompat/v192/com/google/idea/sdkcompat/testframework/PlatformTestCaseCompat.java
testing/testcompat/v193/com/google/idea/sdkcompat/testframework/PlatformTestCaseCompat.java

compat: Add compat class for PlatformTestCase.createProject
PlatformTestCase.createProject has changed signature in v193. This CL adds a compat class for a consistent signature.

compat: Add compat class for PlatformTestCase.createProject

---

testing/BUILD
testing/testcompat/v192/com/google/idea/sdkcompat/testframework/JavaResolveTestCase.java
testing/testcompat/v193/com/google/idea/sdkcompat/testframework/JavaResolveTestCase.java

compat: Add compat class for (Java)ResolveTestCase
api193 renames ResolveTestCase to JavaResolveTestCase. This CL creates a compat class to provide a consistent name.

compat: Add compat class for (Java)ResolveTestCase

---

base/src/com/google/idea/blaze/base/sync/projectview/TargetExpressionList.java
base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java
base/tests/unittests/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharderTest.java

Fix sharded syncs not properly removing explicitly-excluded targets when deriving targets from directories.

Fix sharded syncs not properly removing explicitly-excluded targets when deriving targets from directories.

---

common/formatter/src/com/google/idea/common/formatter/DelegatingCodeStyleManager.java
sdkcompat/v191/com/google/idea/sdkcompat/openapi/DelegatingCodeStyleManagerCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/openapi/DelegatingCodeStyleManagerCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/openapi/DelegatingCodeStyleManagerCompat.java

Fix code style manager support in 2019.3
GitHub issue: https://github.com/bazelbuild/intellij/issues/1548

Fix code style manager support in 2019.3

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeApkBuildStepMobileInstall.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeApkBuildStepNormalBuild.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeInstrumentationTestApkBuildStep.java
aswb/src/com/google/idea/blaze/android/run/runner/ExecRootUtil.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepMobileInstallIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepNormalBuildIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeInstrumentationTestApkBuildStepIntegrationTest.java
aswb/tests/utils/integration/com/google/idea/blaze/android/MessageCollector.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java

Use correct execroot to obtain deployment files.
Currently ASwB assumes a project will only have one execroot.  As a
result the build process will attempt to save time by reusing the
execroot fetched during initial project sync.  This is not always correct
and caused a bug where the build process will use a remote execroot 
as it's local blaze execroot and failed due to "missing files".
This CL fixes this by parsing BEP for the execroot, which should 
always be present after a build anyway.  
This change modifies the critical path for running/debugging 
android apps from the IDE. Fetching execroot from BEP output
hasn't been done before so a fallback mechanism guarded by
"enable.execroot.fallback" flag will automatically enable the old
way of obtaining the execroot through blaze info if …

Use correct execroot to obtain deployment files.

---

java/src/META-INF/java-contents.xml
java/src/com/google/idea/blaze/java/sync/model/AttachSourcesFilter.java
java/src/com/google/idea/blaze/java/sync/model/BlazeJarLibrary.java

Eagerly attach sources for android support libraries.
DejetifiedGotoDeclarationHandler requires the presence of indexed
support lib source jars to work.  Specifically, so that the source files
can be found using the FilenameIndex.
This CL adds the extension SourceJarAttachmentDecider to allow
implementers control which libraries to attach source jars.

Eagerly attach sources for android support libraries.

---

base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java

Expand and collapse all buttons for Blaze Problems
The CL adds expand all and collapse all buttons for the tree of errors
in the Blaze Problems view.

Expand and collapse all buttons for Blaze Problems

---

base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/findusages/LocalVariableUsagesTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/CombinedTestHeuristicTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/JUnitTestHeuristicTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlagsIntegrationTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaAbstractTestCaseConfigurationProducerTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaTestClassConfigurationProducerTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaTestMethodConfigurationProducerTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/MultipleJavaClassesTestContextProviderTest.java

api193: Java integration test fixes.
api193 expects `org.junit.Test` and `org.junit.runners.JUnit4` classes to be present in the project to classify it as a JUnit4 project. CombinedTestHeuristic.java already added the relevant classes, but missed the `.java` extension which caused the tests to fail in 193. This CL adds the mentioned classes to the tests that need it.

api193: Java integration test fixes.

---

aswb/tests/unittests/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelperTest.java

Make test assert something rather than ignoring a #containsAll call.

Make test assert something rather than ignoring a #containsAll call.

---

javascript/BUILD
javascript/src/META-INF/javascript-contents.xml
javascript/src/META-INF/pre-v193.xml
sdkcompat/v191/com/google/idea/sdkcompat/javascript/BlazeJsCompletionService.java
sdkcompat/v192/com/google/idea/sdkcompat/javascript/BlazeJsCompletionService.java

Remove BlazeJsCompletionService in v193, since JsCompletionService is now final.

Remove BlazeJsCompletionService in v193, since JsCompletionService is now final.

---

java/src/META-INF/java-contents.xml

api193: Load BuildFileSafeDeleteProcessor first
As of api193 BuildFileSafeDeleteProcessor randomly loads after `OCSafeDeleteProcessorDelegate` (introduced by Android NDK plugin). `OCSafeDeleteProcessorDelegate` claims to handle all elements, and does not provide an extension ID. So, this CL forces BuildFileSafeDeleteProcessor to be loaded first.

api193: Load BuildFileSafeDeleteProcessor first

---

base/tests/integrationtests/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManagerTest.java

Fix race condition in ExternalLibraryManagerTest.
Using a separate VFS listener can be flaky as it is not guaranteed to be
run after the one from ExternalLibraryManager. I found an explicit wait
for events function instead, and it seems to do what we need.

Fix race condition in ExternalLibraryManagerTest.

---

WORKSPACE

Update maven URLs to HTTPS.
See https://support.sonatype.com/hc/en-us/articles/360041287334.

Update maven URLs to HTTPS.

---

java/src/com/google/idea/blaze/java/sync/source/JavaSourcePackageReader.java
java/src/com/google/idea/blaze/java/sync/source/SourceDirectoryCalculator.java

Don't display warning messages during sync when java source files can't be found.
It's an expected situation during partial syncs, when previously-synced data may not be up-to-date.

Don't display warning messages during sync when java source files can't be found.

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java

Add verbose deploy info error logging.
Currently if the deployment info file can't be found after a build, a
message indicating failure will be logged but it's not enough to help
with debugging tricky bugs.  This CL adds more verbose logging.

Add verbose deploy info error logging.

---

aswb/src/com/google/idea/blaze/android/run/runner/ExecRootUtil.java

Fix ExecRootUtil.getExecutionRoot always falling through.
ExecRootUtil.getExecutionRoot gets the execroot but doesn't actually
return it.  This CL fixes that.

Fix ExecRootUtil.getExecutionRoot always falling through.

---

javascript/tests/integrationtests/com/google/idea/blaze/typescript/BlazeTypeScriptConfigTest.java

Drop the noStrictGenericChecks: true compiler setting.
We're removing this globally for google3.

Drop the noStrictGenericChecks: true compiler setting.

---

base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/findusages/FindRuleUsagesTest.java

api193: Fix Base Integration test
193 does not guarantee the order of returned PSIReferences. This CL makes `FindRuleUsagesTest#testLocalReferences` order agnostic.

api193: Fix Base Integration test

---

base/src/com/google/idea/blaze/base/io/FileOperationProvider.java
base/src/com/google/idea/blaze/base/prefetch/PrefetchService.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptAdditionalLibraryRootsProvider.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfigServiceImpl.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypescriptSyncPlugin.java
javascript/src/com/google/idea/blaze/typescript/DelegatingTypeScriptConfigService.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/BlazeTypeScriptConfigTest.java

Move where we reload tsconfig files.
After cl/282411077, we always reload the tsconfig whenever we read the
file list to avoid having stale configs, but that causes file resolving
to happen on the EDT when we want to rebuild the external libraries for
TypeScript.
This CL moves tsconfig reloading to immediately follow the place where
we rebuild the tsconfig rules. It is off the EDT, and guarantees that
the TypeScript service always has an up to date view of the tsconfig
files.

Move where we reload tsconfig files.

---

BUILD
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/findusages/FunctionStatementUsagesTest.java
golang/BUILD
golang/tests/unittests/com/google/idea/blaze/golang/run/BlazeDlvPositionConverterTest.java
intellij_platform_sdk/build_defs.bzl
java/tests/integrationtests/com/google/idea/blaze/java/sync/JavaSyncTest.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/JavascriptSyncTest.java
scala/tests/integrationtests/com/google/idea/blaze/scala/run/producers/BlazeScalaTestRunLineMarkerContributorTest.java
scala/tests/integrationtests/com/google/idea/blaze/scala/run/producers/ScalaSpecs2TestContextProviderTest.java
sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/golang/GoSdkServiceProvider.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/golang/GoSdkServiceProvider.java
sdkcompat/v193/BUILD
sdkcompat/v193/com/google/idea/sdkcompat/golang/GoSdkServiceProvider.java
testing/testcompat/v193/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java

Move 2019.3 into the beta branch
Fixes several failing tests, and temporarily disables some Go, JS/TS, Scala tests still failing against 2019.3

Move 2019.3 into the beta branch

---

.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij.yml

The IntelliJ platform SDKs already switched to Java 11 and the plugins will be
running in a Java 11 environment. Hence, build and tests the plugins also in
the context of Java 11. To do so, we need to choose a test environment which
features Java 11 as default JDK. ubuntu1804 is one of those (see #722).
For the moment, we'll keep the ubuntu1604 configuration to have a graceful
transition period. We expect to drop that configuration soon as we don't need
Java 8 compatibility anymore.

Run tests also on Java 11 (via ubuntu1804)

---

.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij.yml

Current versions of IntelliJ/CLion run with JDK 11 and hence we don't
need compatibility with Java 8 anymore. This doesn't mean that we can
start using Java language features of Java 9+ immediately. That's still
a bit out in the future.

Stop running the tests on Java 8 (via ubuntu 1604)

---

.bazelci/intellij-ue.yml

Until now, we've only automatically run the tests for IntelliJ CE.
This means that we catch issues with the UE version only much later
(e.g. when we build and test it for the upload to the public plugin
repository). Let's change this.

Add a test configuration for IntelliJ UE

---

.bazelci/intellij.yml

The IntelliJ tests were split up into CE and UE tests in the past.
The general ijwb_tests target was only kept for compatibility with our
test configuration. Hence, cleanup the test configuration so that we
can remove this unnecessary target.

Correct test target of IntelliJ CE configuration

---

.bazelci/android-studio.yml
.bazelci/clion.yml
.bazelci/intellij-ue.yml
.bazelci/intellij.yml

Issue number: #2595
This pull request adds tasks for testing against all the IDE versions supported internally and externally. I update the CI config files to include a task for testing against every supported version.
I also added a soft fail option for the IDE version that we currently work towards supporting (labeled as under development) so that its failure won't affect the overall check status. Testing against this version is expected to fail for most PRs until we fully support it but we want the whole presubmit test pipeline to succeed if the tests against older versions passes. This will allow us to merge the pull request, of course, after checking that the failed test log does not contain anything that should have passed and was broken by the PR.

Add tests against all supported IDE versions to the project CI

---

.bazelci/aspect.yml

The flag flip broke IntelliJ downstream tests.
Fixes https://github.com/bazelbuild/bazel/issues/13328
details.
Issue number: https://github.com/bazelbuild/bazel/issues/13328

Add --notrim_test_configuration to Bazel CI configuration

---

.bazelci/clion.yml

For the sake of completeness, add a test for CLion with the internal under development version defined by clion-under-dev.

Add tests for CLion Internal Under Development version

---

.bazelci/aspect.yml

Following the change proposed in #2794, this PR renames canary to under-dev in aspect tests as well.

Rename canary to under-dev in aspect CI

---

base/src/com/google/idea/blaze/base/model/primitives/WorkspacePath.java
base/tests/unittests/com/google/idea/blaze/base/model/primitives/WorkspacePathTest.java

details.
Issue number: #2338
Prepending `parentPath` when the `parentPath` is the workspace root could end up with a path that starts with `/` (`BLAZE_COMPONENT_SEPERATOR`), which is incorrect and results in an invalid WorkspacePath. This change will only prepend the `parentPath` if the `parentPath` is not the workspace root.
Fixes: https://github.com/bazelbuild/intellij/issues/2338
Takes over from PR: https://github.com/bazelbuild/intellij/pull/2829

Conditionally prepend parentPath in WorkspacePath

---

README.md

[This is a cleanup change, in violation of the checklist requested, but I hope that it is uncontroversial enough to be quickly reviewed.]
Fix a grammar error and a spelling error in the repository's README.md

Two nit-picks in README.md

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/project/NewBazelProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/wizard2/BlazeNewProjectBuilder.java
base/src/com/google/idea/blaze/base/wizard2/BlazeProjectImportBuilder.java

Opening this PR for discussion, as current implementation may be a bit too feature rich. 
This PR adds support for opening unimported Bazel projects directly from a directory without a need to go over import wizard steps. **We need this feature to be able to open Bazel projects using remote Intellij.**
Adds ProjectOpenProcessor to import project by opening it directly from directory
Project view can be created from (in order of existence):
- ENV var: `INTELLIJ_BAZEL_PROJECT_VIEW_TEMPLATE=/home/user/some.bazelproject`
- from workspace: `tools/intellij/.managed.bazelproject`
- if above don't exist, creates minimal project view file manually

Automatically import projects from directory

---

WORKSPACE
golang/BUILD
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.idea212
intellij_platform_sdk/BUILD.idea213
intellij_platform_sdk/BUILD.idea221
intellij_platform_sdk/BUILD.idea222
intellij_platform_sdk/BUILD.ue212
intellij_platform_sdk/BUILD.ue213
intellij_platform_sdk/BUILD.ue221
intellij_platform_sdk/BUILD.ue222

- Use 2022.2 Beta 2 for IntelliJ and CLion
- Add dependency on IntelliLang needed by GoLang plugin 2022.2

Import IntelliJ and CLion 2022.2 Beta 2

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/MobileInstallBuildStep.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/MobileInstallBuildStepIntegrationTest.java

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See  the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more details.
https://github.com/bazelbuild/intellij/issues/2328 and https://github.com/bazelbuild/intellij/issues/2084
When running `mobile-install` through Android Studio, it appends the `--nolaunch_app` flag to the command. This flag cannot be found and prevents the app from being installed. This PR removes it. Perhaps `nolaunch_app` was removed or it only exists in Blaze?
```
Invoking mobile-install...
Command: bazel mobile-install --tool_tag=ijwb:AndroidStudio --adb sdk/platform-tools/adb --device ABC123:tcp:7890 --curses=no --color=yes --progress_in_terminal_title=no …
```

Remove nolaunch_app to fix mobile-install

---

WORKSPACE
golang/BUILD
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.idea212
intellij_platform_sdk/BUILD.idea213
intellij_platform_sdk/BUILD.idea221
intellij_platform_sdk/BUILD.idea222
intellij_platform_sdk/BUILD.ue212
intellij_platform_sdk/BUILD.ue213
intellij_platform_sdk/BUILD.ue221
intellij_platform_sdk/BUILD.ue222
testing/testcompat/v222/com/google/idea/sdkcompat/indexing/ProjectIndexingHistoryWrapper.java

- Replace `boolean getWasFullRescanning()` with `ScanningType getScanningType()` and return `ScanningType.PARTIAL`.
-  Use bundled IntelliLang plugin in golang integration tests

IntelliJ 2022.2 compatibility fixes

---

.bazelci/android-studio.yml
.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij-ue.yml
.bazelci/intellij.yml

Update plugin versions name and build/test flags in CI following the update in https://github.com/bazelbuild/intellij/pull/3843.
- {PRODUCT}-oss-oldest-stable: the oldest stable IDE version supported
- {PRODUCT}-oss-latest-stable: the second stable IDE version supported
- {PRODUCT}-oss-under-dev: the EAP version we are working towards supporting

Update product versions aliases

---

common/experiments/src/com/google/idea/common/experiments/experiment.properties

- Roll out Kotlin coroutines debugging to 100% of users
- Roll out the new sync window to 100% of users
- Roll out Go external packages tree display to 100% of users
- Roll out the new minimum supported version of Bazel (1.2.0) to 20% of users

Update rollout percentage of experimental features

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java

details.
We are slowly migrating a project to bazel and the auto import code is causing issues and making it hard for developers to work the project in the mean time. 
Ultimatly a easy fix for this is to use the `external.system.auto.import.disabled` key (defined [here](https://github.com/JetBrains/intellij-community/blob/master/platform/util/resources/misc/registry.properties#L1476)) to allow us to disable the auto import functionality. 
Its worth noting, this is used in IntelliJ community already to disable maven importing, we can use a different registry key, but I figure this …

Prevent auto import of project if registry key is set

---

base/src/com/google/idea/blaze/base/project/BlazeProjectOpenProcessor.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/2147
Shows a modal dialogue asking where to open the new Bazel project as with regular projects.

Simplify opening of Bazel project using ProjectUtil.

---

sdkcompat/v213/BUILD

This glob is not globbing anything.
This prevents flipping the flag incompatible_disallow_empty_glob https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1301#0183e377-8857-4e31-8aca-c14ba82f4a15
details.

Remove empty glob

---

base/src/com/google/idea/blaze/base/model/primitives/TargetExpression.java
base/tests/unittests/com/google/idea/blaze/base/model/primitives/TargetExpressionTest.java

details.
Issue number: #4008
This commit ensures that main repository target expressions such as `@//foo:test` can be parsed correctly. Since
https://github.com/bazelbuild/bazel/commit/b1113f801da87ed2e089ff4122aa13400c177804, these are emitted by Bazel by default.

Fix main repo target parsing

---

base/src/com/google/idea/blaze/base/ui/problems/ProblemsViewConfiguration.java

details.
Issue number: #3106
Currently the Autoscroll to console feature in the Bazel plugin is disabled by default.
Considering that many Bazel output parsers only emit the first line of the error to the Bazel problems view, it is very common for developers to look for errors details in the Bazel output. The Autoscroll to console feature is a great help here. But it is disabled by default and poorly advertised, which degrades the UX for Bazel-powered projects.
This commit enables the Autoscroll to console feature by default. The feature can still be disabled if necessary.

Enable the Autoscroll to console by default

---

base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/project/BlazeProjectOpenProcessor.java
clwb/src/com/google/idea/blaze/plugin/CMakeNotificationFilter.java
java/src/com/google/idea/blaze/java/libraries/AddLibraryTargetDirectoryToProjectViewAttachSourcesProvider.java
java/src/com/google/idea/blaze/java/libraries/BlazeAttachSourceProvider.java
java/src/com/google/idea/blaze/java/libraries/DisableLibraryBytecodeNotification.java
sdkcompat/v213/BUILD
sdkcompat/v213/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v213/com/google/idea/sdkcompat/general/EditorNotificationCompat.java
sdkcompat/v213/com/google/idea/sdkcompat/java/AttachSourcesProviderAdapter.java
sdkcompat/v221/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v221/com/google/idea/sdkcompat/general/EditorNotificationCompat.java
sdkcompat/v221/com/google/idea/sdkcompat/java/AttachSourcesProviderAdapter.java
sdkcompat/v222/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v222/com/google/idea/sdkcompat/general/EditorNotificationCompat.java
sdkcompat/v222/com/google/idea/sdkcompat/java/AttachSourcesProviderAdapter.java

details.
Issue number: #4037 
Preparation before introduction of 2022.3 support. The original PR introducing 2022.3 is here #4019, but I decided to split it into smaller parts in order to simplify review

Move APIs removed in IntelliJ Platform 2022.3 to sdkcompat modules

---

.bazelrc

details.
Issue number: closes #4069 
This is required in order to import projects using JVM < 17 (because
our aspects run some Java apps, like PackageParser), as well as IntelliJ
instances hosted on JVMs older than 17.

Fix: Build jvm class file format v52

---

WORKSPACE

Previously, it was (inserted by accident) the checksum of a newline
```
echo -n  "" | sha256sum
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
```
Btw, we have a bug in CI config, so the CI report is green, despite particular jobs being red
details.

Fix checksum of IntelliJ 2022.3

---

BUILD
examples/go/with_proto/BUILD.bazel
examples/go/with_proto/with_proto.bazelproject
gazelle/BUILD
gazelle/src/META-INF/blaze-gazelle.xml
gazelle/src/com/google/idea/blaze/gazelle/BlazeGazelleRunner.java
gazelle/src/com/google/idea/blaze/gazelle/BlazeGazelleRunnerImpl.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleIssueParsers.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleRunResult.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleSection.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleSyncListener.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleSyncPlugin.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleUserSettings.java
gazelle/src/com/google/idea/blaze/gazelle/GazelleUserSettingsConfigurable.java
gazelle/tests/integrationtests/com/google/idea/blaze/gazelle/sync/RunGazelleOnSyncTest.java
ijwb/BUILD

This is a WIP because I can't figure out how to make the tests work.
details.
Issue number: `3216`
See linked issue for a description and general design.
This is a port of the existing plugin: https://github.com/blorente/intellij_gazelle. Refer to that README for usage.
Architecturally, this plugin does two things:
- Implements a `GazelleSyncPlugin`, which inserts itself between the `bazel info` and `bazel build` phases of a sync cycle, to run gazelle in between, via a `BlazeGazelleRunnerImpl`.
- Hooks into UserSettings, to add a global field to specify a gazelle target to run on …

feat: Add gazelle to plugin

---

gazelle/tests/integrationtests/com/google/idea/blaze/gazelle/sync/RunGazelleOnSyncTest.java

@mai93 brought it to attention.
Some downstream tests use the `USE_BAZEL_VERSION` env var to set up the Bazel executable. Normally, this would not be set up for tests, as most tests don't run Bazel themselves. However, the Gazelle integration tests do need to run Bazel, so we must set those global settings manually.

Make gazelle tests respect USE_BAZEL_VERSION

---

plugin_dev/src/com/google/idea/blaze/plugin/run/IntellijWithPluginClasspathHelper.java

Without it, 2022.3 RC will throw an exception when you try to open module settings. Throws "ClassNotFoundException: org.intellij.lang.annotations.MagicConstant"
details.
Issue number: #4139

[IJ 2022.3] Add annotations.jar and groovy.jr to the list of IJ libraries

---

aspect/intellij_info_impl.bzl

details.
`go_proto_library` has compilers which bring some types implicitly. Let's not forget to include them.

Include implicit dependencies from proto compilers

---

examples/go/with_proto/proto/BUILD.bazel
examples/go/with_proto/proto/fooserver.proto

Issue number: #3248 added support for well-known protobuf types in go. This change just adds an illustrative case to demonstrate the impact of those changes.

Go: Add well-known proto type to example project

---

WORKSPACE
intellij_platform_sdk/build_defs.bzl

- Use the stable 2022.3 release
- Upgrade the supported IDE versions so that oldest stable is 2022.2 and the latest stable is 2022.3

Update 2022.3 to the stable release

---

base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
examples/java/greetings_project/.bazelrc
java/src/com/google/idea/blaze/java/projectview/JavaLanguageLevelSection.java
java/src/com/google/idea/blaze/java/sync/projectstructure/Jdks.java
java/tests/integrationtests/com/google/idea/blaze/java/sync/projectstructure/JdksTest.java
java/tests/unittests/com/google/idea/blaze/java/projectview/JavaLanguageLevelSectionTest.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/3080
Intellij project language levels may include variants of major Java
versions such as "17 (preview)". Today, the Bazel plugin
`java_language_level` option specified in in the Project View File
accepts an integer value which defines the major Java version to use.
As an integer, it is not possible to specify preview versions.
This changes adds support for specifying any Java language level by
specifying a string for `java_language_level` that is attempted to be
matched against the LanguageLevel enum value names …

Support Preview Java Language Levels

---

plugin_dev/src/com/google/idea/blaze/plugin/run/IntellijWithPluginClasspathHelper.java

If you setup dev environment according to DEV_IDE_SETUP.md, indexing of some languages (for example Scala) won't work without this library.
details.

Plugin Development: add jsp-base.jar library to run configuration.

---

examples/go/with_proto/go/lib/lib_test.go
golang/src/com/google/idea/blaze/golang/run/producers/GoTestContextProvider.java
golang/tests/integrationtests/com/google/idea/blaze/golang/resolve/BlazeGoPackageTest.java
golang/tests/integrationtests/com/google/idea/blaze/golang/run/producers/BlazeGoTestConfigurationProducerTest.java
golang/tests/integrationtests/com/google/idea/blaze/golang/utils/MockGoImportResolver.java
golang/tests/integrationtests/com/google/idea/blaze/golang/utils/MockGoPackageFactory.java

Issue number: #3691 
Bazel and rules_go support subtests using the `--test_filter` flag. However, the plugin doesn't currently recognise any test beyond a top-level function.
This change improves the granularity of recognition somewhat, allowing for nested tests inside a single function.
The actual change is small, just calling to the Go plugin's very handy `GoTestRunConfigurationProducerBase.findSubTestInContext` in `GoTestContextProvider`. The bulk of the change is made up of improvements to the testing infrastructure to support these tests.
Commits can be reviewed independently.
Fixes #3691

fix(go) Correctly identify subscoped tests

---

base/src/com/google/idea/blaze/base/actions/FileGitHubIssueAction.java

details.
Issue number: #1341 
The attempt to run `glogin` is expected to fail for all users outside the Google's infrastructure. This causes a stack trace which litters the idea.log and makes it harder to look for any actual problems.

Check whether the glogin command exists before running it.

---

cpp/src/META-INF/blaze-cpp.xml
cpp/src/com/google/idea/blaze/cpp/BlazeOwnModuleDetector.java
sdkcompat/v212/com/google/idea/sdkcompat/cpp/CidrOwnModuleDetectorWrapper.java
sdkcompat/v213/com/google/idea/sdkcompat/cpp/CidrOwnModuleDetectorWrapper.java
sdkcompat/v221/com/google/idea/sdkcompat/cpp/CidrOwnModuleDetectorWrapper.java
sdkcompat/v222/com/google/idea/sdkcompat/cpp/CidrOwnModuleDetectorWrapper.java
sdkcompat/v223/com/google/idea/sdkcompat/cpp/CidrOwnModuleDetectorWrapper.java

details.
Issue number: #4168 
This prevents "This file does not belong to any project target; code insight features might not work properly" popup

Mark module as clion's own module

---

README.md

there was only a URL for the IntelliJ Beta channel. Added CLion and Android Studio

Add beta installation links for all supported products

---

aspect/intellij_info_impl.bzl

Issue number: #4108 
Use full jars instead of ijars. See:
https://youtrack.jetbrains.com/issue/SCL-16975/Navigation-to-attached-Scala-sources-for-interface-jar-does-not-work

Scala source attachment: use full jars instead of ijars

---

aspect/artifacts.bzl
base/src/com/google/idea/blaze/base/ideinfo/ArtifactLocation.java
base/tests/unittests/com/google/idea/blaze/base/sync/workspace/ArtifactLocationDecoderTest.java
java/src/com/google/idea/blaze/java/sync/source/PackageManifestReader.java
proto/common.proto

details.
This temporary field was used to cover old bazel behavior, which is not the case now.
By the way there was a bug here because `toProto` was not setting the "is_new_external_version" field so if an already-serialized data was deserialized again, the fixProto method was applied again

Remove `is_new_external_version` temporary field

---

base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java

- [x ] I have received the approval from the maintainers to make this change.
- [x ] This is not a stylistic, refactoring, or cleanup change.
details.
Bazel commands currently require target specifications for run configurations but these are unnecessary for the 'info' command. Removed the requirement for just that command

Bazel 'info' command doesn't require target specification

---

WORKSPACE
aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BUILD
base/src/com/google/idea/blaze/base/plugin/BazelVersionChecker.java
common/experiments/src/com/google/idea/common/experiments/experiment.properties

Remove experiment and set the minimum supported Bazel version to 1.2.0 by default.

Update Bazel minimum supported version

---

plugin_dev/src/META-INF/blaze-plugin-dev.xml
plugin_dev/src/com/google/idea/blaze/plugin/sync/IntellijScalaPluginSyncPlugin.java
plugin_dev/tests/integrationtests/com/google/idea/blaze/plugin/sync/PluginScalaDevSyncTest.java

At Wix we use Scala code to write internal plugins, but Scala language is not supported if `workspace_type` is `intellij_plugin`. This PR adds support to allow Scala language to be used in plugin workspaces.
Implementation is mostly copy of `IntellijPluginSyncPlugin` with added modifications to allow Scala to be used in the workspace. The test only adds `scala` to `additional_languages` project view section, but still uses Java code, because compiling code with Rules Scala would require complex workspace setup as the ruleset is not bundled with Bazel. I think this is enough to verify Scala language is supported.
I am open to make any changes, if needed.

Add Scala support to plugin workspace

---

base/src/com/google/idea/blaze/base/run/smrunner/BlazeXmlToTestEventsConverter.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/2149
When using certain assertion libraries, such as https://github.com/google/truth, the expected and actual value are not always present and the patterns defined in com.intellij.junit4.ExpectedPatterns are not covering all possible messages (actually I don't see them covering any of Google Truth messages).
But even without them, IMO the test should be considered a "failure" rather than an "error" when an assertion fails. This can be controlled by the means of the "error" XML element in the generated JUnit report …

Allow for more flexibility when reporting test failures

---

.github/workflows/labeler.yml

This Github workflow will add 'not stale' label on Copybara-service[bot] PR's, to avoid stale Github action workflow.

This Github workflow will add 'not stale' label on copybara PR's

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTestRunner.java

This test is [failing with Bazel@Head](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2854#01862a0b-3ae5-4841-9105-0cad45f2ed1f) and the failure is not reproducible locally so this PR adds more details to the failure message to learn more about the failing invocation.

Add more information in failure message

---

WORKSPACE
base/tests/integrationtests/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManagerTest.java

details.
The call to `libraryProvider.setFiles(newFile.getPath())` is removed
from `ExternalLibraryManagerTest.testFailedAsync`, because after sync failure
the project still has Old.java file, not the New.java file.
Unfortunately, because of that, in the `after` method of this test suite, the
file New.java is deleted, while Old.java is attached to the project. Contrary,
in the `testSuccessfulSync` test, the `after` method removes the same file that
is attached to the project (New.java)
This was working until the new …

Bump IntelliJ to 231.6471.13 and CLion 231.6471.1

---

.bazelci/aspect.yml

This should fix [these failures with Bazel@Head](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2861#01863915-6207-4e93-9d68-c385da125f49) caused by `--test_env=USE_BAZEL_VERSION` looking for a Bazel binary that does not exist.

Skip USE_BAZEL_VERSION added by CI

---

WORKSPACE
base/BUILD
intellij_platform_sdk/build_defs.bzl

details.
We need to make sure that the //base:integration_test_utils is compiled with javac option "-source 17" (or newer) because
EditorTestHelpere calls `new CaretAndSelectionState` which is a record type constructor (introduced in JVM 16).
https://github.com/JetBrains/intellij-community/blob/1cf4235348c121a5e01977637e87e4f6bc08168e/platform/testFramework/src/com/intellij/testFramework/EditorTestUtil.java#L837
Since 2022.3 IntelliJ requires JVM 17 to start, so the function `java_version_flags` returns java11 for all …

Bump to IntelliJ 231.7515.13

---

aspect/intellij_info_impl.bzl

https://github.com/bazelbuild/intellij/commit/3ce133cc9e0bc4962671647b01e6514f95821612 was rolled back because the plugin code needs to be further modified to handle the new Bazel labels with leading `@`(s). The modification will not be simple until this change is rolled out for Blaze as well ([comment](https://github.com/bazelbuild/intellij/issues/4349#issuecomment-1410464797)). This PR only adds the missing handling for `go_test` targets.

Fix ambiguous labels for Go

---

.github/workflows/notstale.yml

This Github action will add "not stale" label to all the copybara-service[bot] PR's. So that they are exempted from stale Github action workflow.

Adds not stale label on copybara-service[bot] PR's

---

.github/workflows/notstale.yml

Extension of https://github.com/bazelbuild/intellij/pull/4517 (add "not stale" label to copybara-service[bot] PRs)
Without permission it is throwning the resource integration error. Now it is fixed. Tested on dummy bot on a dummy repo https://github.com/sgowroji/DummyRepo/pull/15

Applying permission to write only on pull-requests

---

base/src/com/google/idea/blaze/base/buildmodifier/BuildFileFormatOnSaveHandler.java
base/src/com/google/idea/blaze/base/buildmodifier/BuildFileFormatter.java
base/src/com/google/idea/blaze/base/buildmodifier/BuildifierCustomFormatter.java
base/src/com/google/idea/blaze/base/buildmodifier/BuildifierFormattingService.java

details.
Issue number: #4496 
Previously, when formatting a file, buildifier would be called without passing the `--path` argument. Because buildifier will receive the content of the file to format via stdin, buildifier cannot determine to which package the file being formatted belongs.
Unfortunately, this can lead to unexpected results during formatting. For instance, if `StripLabelLeadingSlashes` and
`ShortenAbsoluteLabelsToRelative` are enabled, then the absolute label of a target at the root of the workspace such as `//:label` will be rewritten to the relative label `:label`, …

Pass `--path` to buildifier when possible

---

testing/testcompat/v223/com/google/idea/sdkcompat/roots/ex/ProjectRootManagerExWrapper.java

[ProjectRootManagerExWrapper.java](https://github.com/bazelbuild/intellij/blob/google/testing/testcompat/v223/com/google/idea/sdkcompat/roots/ex/ProjectRootManagerExWrapper.java) is needed by AS 2022.3, we need to add it to the main branch to make cherry-picking from `google` branch easier.

Add missing testing compat class for 2022.3

---

intellij_platform_sdk/build_defs.bzl

Move 2022.3 to `oldest-stable` and 2023.1 to `latest-stable`

Move IntelliJ and CLion 2023.1 to stable

---

plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfigurationType.java

It could cause crashes for non-IJ IDEs, as well as was causing interference between host and guest instance settings.
closes #4802
details.

plugin_dev: Do not pass host IntelliJ's vmOptionsFile to guest IJ instance

---

plugin_dev/src/com/google/idea/blaze/plugin/run/IntellijWithPluginClasspathHelper.java

details.
IntellijWithPluginClasspathHelper in the google branch significantly diverged from master branch version. It seems that the changes in both branches were supposed to introduce a new way of obtaining jvm arguments (from product-info.json file). 
This change merges code from `google` branch to `master` branch with one exception - it preservers master's code that handles case when there is more than one entry in `product-info.json`'s  field named `launch`. Google version was just taking the first entry, which was …

Merge IntellijWithPluginClasspathHelper from google branch

---

aspect/intellij_info_impl.bzl

details.
Issue number: https://github.com/bazelbuild/intellij/issues/4914
Add `associates` as a known dep-like attribute to the aspect. This fixes the simple reproducing example from the issue and works on our internal repository.

Add associates to dep attributes

---

base/src/com/google/idea/blaze/base/model/primitives/WorkspacePath.java

closes #3380
details.
Issue number: #3380 
Fix path separator in run configuration generator

Fix path separator in run configuration generator

---

examples/cpp/simple_project/.bazelrc
examples/cpp/simple_project/WORKSPACE

New GTest requires c++ version 14 or newer
details.

Bump GTest veresion in example project

---

CHANGELOG

Update changelog for release v2023.06.13

---

DEV_IDE_SETUP.md

They are now set automatically via product-info.json
https://github.com/bazelbuild/intellij/pull/4408
details.

doc: Do not recommend to manually set jdk17 vm options

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

This PR is to automatically assign issues to the triage team and add "type" labels.
Once the triage team takes a look and adds other labels/assignees as appropriate, they will unassign themselves, similar to the process for the main Bazel repository.

Automatically assign issues to triage team and add "type" labels

---

base/src/com/google/idea/blaze/base/lang/buildfile/references/LabelUtils.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/references/ExternalWorkspaceReferenceTest.java

details.
Issue number: #4310
`load`s of non-repo-absolute labels in external workspace are now resolved correctly.

Fix references for repo-relative labels in external workspaces

---

base/src/com/google/idea/blaze/base/model/primitives/Kind.java

details.
Issue number: #5183 
Update the heuristic for detecting test_suites to check if a rule ends in `"test_suite"`.

Fix detecting custom test_suite macros

---

.github/labeler.yml

Remove automatic label `product: Android Studio` because pull-requests based on the `master` branch will not affect the Android studio plugin as it is released from the `google` branch.

Remove automatic label `product: Android Studio` for PRs

---

.github/labeler.yml
aspect/intellij_info_impl.bzl
examples/go/with_go_source/BUILD.bazel
examples/go/with_go_source/WORKSPACE
examples/go/with_go_source/otherlib/BUILD.bazel
examples/go/with_go_source/otherlib/otherlib.go
examples/go/with_go_source/testa/BUILD.bazel
examples/go/with_go_source/testa/src.go
examples/go/with_go_source/testa/testa.go
examples/go/with_go_source/testb/BUILD.bazel
examples/go/with_go_source/testb/src.go
examples/go/with_go_source/testb/testb.go
examples/go/with_go_source/testb/testb_test.go
examples/go/with_go_source/with_go_source.bazelproject
examples/go/with_proto/with_proto.bazelproject

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked.
See the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more details.
Issue number: #1265 
This change mark all source files and generated source files of all embedded `go_source` rules in `go_test` and `go_library` rules as source files.

Support embedded `go_source` rule type in `go_test` and `go_library` rules

---

.github/workflows/pr-assignee.yml

Auto-assign PRs based on attached labels

Auto-assign PRs

---

base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationType.java

details.
This change makes the Bazel run configurations dumb aware. As far as I can tell,  none of the run configurations use any of the indexes and simply invokes bazel run. Because of this, there is no reason to rely on "smart" mode.

Make bazel run configurations dumbaware

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/bazel/AbstractBuildInvoker.java
base/src/com/google/idea/blaze/base/command/info/BlazeInfoProvider.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncManager.java
base/src/com/google/idea/blaze/base/sync/ProjectStateSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Issue number: #5217
More details can be found in the issue and on each commit.

Sync process optimizations

---

DEV_IDE_SETUP.md

Adding screenshots to the Markup documentation to make it clear what needs to be done at each step.

Add screenshots to DEV_IDE_SETUP.md

---

base/src/com/google/idea/blaze/base/projectview/ProjectViewStorageManagerImpl.java
base/src/com/google/idea/blaze/base/toolwindow/ConsoleView.java

Since the commit below, FSRecords update operations are forbidden in EDT thread. https://github.com/JetBrains/intellij-community/commit/78f74745498f981d66733bcba315f85cc86c11c6
For this reason, we delegate a few method calls to Background Thread in order to make sure it will not crash. We do it via a synchrounous BGT call, so EDT still stops and waits until the aciton is completed, like it was before this change.
details.

Prepare for 2023.3: Move some tasks to background thread.

---

WORKSPACE
intellij_platform_sdk/BUILD.idea233
intellij_platform_sdk/BUILD.ue233
plugin_dev/BUILD
third_party/devkit/BUILD

Since now, the DevKit plugin is published to JetBrains Marketplace so we have to obtain it from there
https://plugins.jetbrains.com/plugin/22851-plugin-devkit
details.

Bump IntelliJ to 2023.3 EAP 4 and use DevKit from Marketplace

---

base/src/com/google/idea/blaze/base/sync/SyncProjectTargetsHelper.java
base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java
base/src/com/google/idea/blaze/base/sync/sharding/WildcardTargetExpander.java
base/tests/unittests/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharderTest.java

This PR is a continuation of https://github.com/bazelbuild/intellij/issues/4546. One issue is that for manual targets specified, they are also excluded without this change (see https://github.com/bazelbuild/intellij/issues/4546#issuecomment-1741969833).
This fix will only work currently if the [shard_sync: true](https://ij.bazel.build/docs/project-views.html#shard_sync). Otherwise the query will not be performed. I pushed a [second commit](https://github.com/bazelbuild/intellij/pull/5458/commits/680862626c3fc88f8be0a1437450e73ed33dd118) to make this change explicit. Otherwise, two flags must be set for this part to work.
Issue number: https://github.com/bazelbuild/intellij/issues/4546
When `allow_manual_targets_sync: true` is set, this change will allow manual targets to be part of the …

Fix manual targets sync for target explicitly specified

---

DEV_IDE_SETUP.md
base/src/com/google/idea/blaze/base/settings/ui/ProjectViewUi.java
base/src/com/google/idea/blaze/base/wizard2/ImportFromWorkspaceProjectViewOption.java

Fix typos
details.
Issue number: `5470`
Fix directory separators and line-breaks on Windows, and fix some typos.
Closes #5470

Adapt paths and line breaks for Windows

---

clwb/BUILD
clwb/src/META-INF/clwb-oclang.xml
clwb/src/META-INF/clwb.xml
clwb/src/com/google/idea/blaze/clwb/oclang/run/BlazeCidrDebuggerSupportFactory.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/CidrGoogleTestUtilAdapter.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/producers/CppTestContextProvider.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/test/BlazeCidrTestEventsHandler.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/test/BlazeCppTestInfo.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/test/BlazeCppTestLocator.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/test/GoogleTestLocation.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/test/GoogleTestSpecification.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java
clwb/src/com/google/idea/blaze/clwb/run/GoogleTestUtilAdapter.java
clwb/src/com/google/idea/blaze/clwb/run/RunConfigurationUtils.java
clwb/tests/unittests/com/google/idea/blaze/clwb/oclang/run/test/BlazeCppTestInfoTest.java
cpp/BUILD
cpp/src/META-INF/blaze-cpp-oclang.xml
cpp/src/META-INF/blaze-cpp.xml
cpp/src/com/google/idea/blaze/cpp/BlazeResolveConfiguration.java
cpp/src/com/google/idea/blaze/cpp/SourceFileFinder.java
cpp/src/com/google/idea/blaze/cpp/oclang/BlazeCppAutoImportHelper.java
cpp/src/com/google/idea/blaze/cpp/oclang/BlazeCustomHeaderProvider.java
cpp/src/com/google/idea/blaze/cpp/oclang/BlazeIncludeHelper.java
cpp/src/com/google/idea/blaze/cpp/oclang/CppSyncStatusContributor.java
cpp/src/com/google/idea/blaze/cpp/oclang/OCSourceFileFinder.java

details.
Issue number: #5472
Long story short: `com.intellij.modules.cidr.lang` is going to become optional in CLion at some point. All the usages of code exported from `com.intellij.modules.cidr.lang` are moved to optional plugin xmls, so plugin won't emit lots of exceptions and break the IDE if the mentioned module is not available. 
A little bit more detailed here. We (CLion team) are working on deprecation of the old language engine. Parts of it which are not going to be deprecated are moved to `cidr-base-plugin` library, which is a part of `CIDR Base (com.intellij.cidr.base)` …

Make //clwb(plugin) and //cpp(plugin) dependency on cidr.lang optional: plugin xmls split

---

base/src/com/google/idea/blaze/base/lang/buildfile/references/FileLookupData.java

Discussed offline with @blorente. This looks like a regression.
Mark package with BUILD.bazel file in completion
In this repo under example/go/with_proto
Behavior: proto is a directory, it should be a package
In this repo under example/go/with_proto
Behavior: proto is a package, as expected

fix: Mark package with BUILD.bazel file in completion

---

java/tests/unittests/com/google/idea/blaze/java/libraries/JarCacheTest.java

details.
Discovered while trying to set up CI for our internal mirror of the plugin.
The combination of running these tests from macOS in bazel doesn't seem to work for these tests, because the `BlazeJavaUserSettings` default to `useJarCache=false` when we're not running with Blaze.
To solve it, we:
- Force `BlazeJavaUserSettings.useJarCache` to `true`, because that's what we're testing. 
- Make the tests believe that they are running under Bazel, because JarCaches are only allowed in Mac if they are under Bazel (and not Blaze).

fix: Force JarCache to be on on JarCache tests

---

WORKSPACE
testing/test_defs.bzl

details.
Discovered while trying to set up CI for our internal mirror of the plugin.
We test cross-platform (from mac arm to linux x86, for instance). Most of the tests  complained that they couldn't find the JNA library. As far as I can tell, we just rely on the JNA that comes bundled with the plugin SDK. However, that implicit dependency doesn't handle Bazel's platform definition.
Therefore, we add a dependency to proper `jna` upstream to be able to run the tests from any combination of platforms.

fix: Depend on upstream jna instead of the bundled one

---

WORKSPACE

details.
The new version of grpc-java has the fix for the migration of [Automatic Exec Groups - AEGs](https://github.com/bazelbuild/bazel/issues/19981). In order to move forward with enabling AEGs inside Bazel, this new release must be used.

Bump grpc-java version

---

java/src/com/google/idea/blaze/java/JavaBlazeRules.java
java/src/com/google/idea/blaze/java/TargetKindUtil.java
java/src/com/google/idea/blaze/java/sync/source/JavaLikeLanguage.java
java/tests/unittests/com/google/idea/blaze/java/run/BlazeJavaRunProfileStateTest.java

details.
Issue number: Change implemented internally, upstreaming.
[`java_test_suite`](https://github.com/bazel-contrib/rules_jvm#java_test_suite) is a common way to define java tests for users of https://github.com/bazel-contrib/rules_jvm. Running them is roughly trivial as it acts just like a `test_suite` that generates `java_test` targets. Just making the plugin aware of the target kind is enough to make it work. All of the individual `java_test` are indexed by the aspect normally.

feat: Support gutter icons in `java_test_suite`

---

base/src/com/google/idea/blaze/base/lang/buildfile/references/AttributeSpecificStringLiteralReferenceProvider.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/references/AttributeSpecificStringLiteralReferenceProviderTest.java

Discussed offline with @blorente as part of implementing an attribute specific completion for visibility.
Allow for multiple implementation of AttributeSpecificStringLiteralReferenceProvider to coexist. If more than one is registered, all the references should be considered.

fix: Allow multiple providers to contribute attribute specific references

---

.bazelci/android-studio.yml

So the internal team can know if their changes break the canary version.

Remove fail soft for ASwB Canary

---

base/src/com/google/idea/blaze/base/toolwindow/TasksTreeConsoleView.java

details.
Issue number: [`5664`](https://github.com/bazelbuild/intellij/issues/5664)

Work around NPE for toolwindow

---

examples/java/greetings_project/WORKSPACE
examples/java/greetings_project/hello/hello.bazelproject

The java example loaded `org.junit.jupiter:junit-jupiter-api:5.9.1` in its WORKSPACE but it was not used and the library from `Runner_deploy-ijar.jar` was used instead. Fixing this to make it clear which version of junit is used. I think junit 5 is not yet supported by the plugin.

Update java example

---

base/src/com/google/idea/blaze/base/lang/buildfile/highlighting/BuildSyntaxHighlighter.java
base/src/com/google/idea/blaze/base/lang/buildfile/language/semantics/BuiltInNamesProvider.java
base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java
base/src/com/google/idea/blaze/base/lang/buildfile/lexer/TokenKind.java
base/src/com/google/idea/blaze/base/lang/buildfile/parser/ExpressionParsing.java
base/src/com/google/idea/blaze/base/lang/buildfile/psi/BuildElementTypes.java
base/src/com/google/idea/blaze/base/lang/buildfile/psi/BuildElementVisitor.java
base/src/com/google/idea/blaze/base/lang/buildfile/psi/FloatLiteral.java
base/tests/unittests/com/google/idea/blaze/base/lang/buildfile/lexer/BlazeLexerTest.java
base/tests/unittests/com/google/idea/blaze/base/lang/buildfile/lexer/HighlightingLexerTest.java
skylark/src/com/google/idea/blaze/skylark/debugger/impl/SkylarkDebugValue.java

details.
Issue number: #5677
Add support for Starlark floating-point literals. Also add `float` as a built-in function, and consider float values primitives in the debugger.
Before:
After:
Much of the lexer implementation is ported from [starlark-go](https://github.com/google/starlark-go/blob/556fd59b42f68a2fb1f84957741b72811c714e51/syntax/scan.go#L909)

feat: Add support for Starlark float literals

---

BUILD
base/src/com/google/idea/blaze/base/settings/Blaze.java
skylark/BUILD
skylark/src/com/google/idea/blaze/skylark/debugger/SkylarkDebuggingUtils.java
skylark/tests/unittests/com/google/idea/blaze/skylark/debugger/SkylarkDebuggingUtilsTest.java

details.
This is a rebase of https://github.com/bazelbuild/intellij/pull/5674. While the issue was fixed by https://github.com/bazelbuild/intellij/commit/59ddcbe54739726f32e2953002d8a49d8f91c5cf, the tests might be useful.

Add unittest for SkylarkDebuggingUtils to check that no exception occurs for non-bazel projects

---

base/src/com/google/idea/blaze/base/buildmodifier/BuildFileFormatter.java

details.
Ensures that `MODULE.bazel` and `WORKSPACE` file contents are formatted according to the specific file type.

Fix buildifier formatting for `MODULE.bazel` and `WORKSPACE`

---

golang/src/com/google/idea/blaze/golang/GoBlazeRules.java

Allow debugging gazelle (use the `gazelle_binary` target and not the `gazelle` one).

feat: Enable debugging the gazelle binary

---

.bazelrc

If the default Java version on the host is "lower" (in my case, 11), the following happens on master:
```
$ java -version
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
$ bazel build //base:integration_tests --define=ij_product=intellij-2023.3
ERROR: /home/motiejus/code/intellij/base/BUILD:535:32: Building base/integration_tests.jar (72 source files) failed: (Exit 1): java failed: error executing Javac command (from target //base:integration_tests) external/remotejdk17_linux/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 19 arguments …
```

bazelrc: set java_runtime_version for builds too

---

java/src/com/google/idea/blaze/java/libraries/AddLibraryTargetDirectoryToProjectViewAttachSourcesProvider.java

fix: Don't throw "Non-blaze project is provided error"

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java
base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java
base/tests/integrationtests/com/google/idea/blaze/base/sync/ImportRootsTest.java
base/tests/unittests/com/google/idea/blaze/base/sync/projectview/TargetExpressionListTest.java

The warnings look like this
WARNING: Pattern '//dist/...:all' was filtered out by ignored directory 'dist'
They occur because the plugin passes paths from bazelignore into "bazel query" as exclusions. Bazel warns about this, as excluding a path that Bazel already knows should be ignored is likely a user error.
The reason bazelignore paths are ending up in the query is that we want the IDE to mark the paths as excluded from the project. For that reason, the plugin parses the bazelignore file, and adds the paths to an exclusion list. That list happens to also be passed to "bazel query".
This commit keeps bazelignore paths in the general exclusion list, but generates a separate list of paths to use for "bazel query", which only contains exclusions not listed in bazelignore.

Fix warnings when syncing a workspace containing a bazelignore file

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/5909
Bazel allows overriding the names of the default symlinks via --symlink_prefix, or omitting them entirely via --experimental_convenience_symlinks=ignore.
When a workspace does this, the default symlinks with names like bazel-out and bazel-bin don't exist. This causes Bazel to emit an error when running "bazel query", since the plugin hardcodes these names as excluded paths.
This commit addresses this by only including paths in "bazel query" that actually exist. Workspaces that change the symlink names can …

Fix bazel sync errors when using non-default convenience symlinks

---

base/src/com/google/idea/blaze/base/run/filter/BlazeTargetFilter.java
base/tests/unittests/com/google/idea/blaze/base/run/filter/BlazeTargetFilterTest.java

details.
Issue number: #4431
Changed the regex used by BlazeTargetFilter to include more valid target names. I used [this](https://bazel.build/concepts/labels#target-names) documentation page to lookup the valid characters.

Changes to BlazeTargetFilter regex to match more target names

---

.github/workflows/stale.yml

Update stale bot messages to be more clear and match what's in the [Bazel repo](https://github.com/bazelbuild/bazel/blob/master/.github/workflows/stale.yml).

Update stale bot messages

---

WORKSPACE
aspect/tools/BUILD
build-visibility.bzl
intellij_platform_sdk/BUILD

It's hard to reason what is included in *_deploy.jar files and what is not
details.

Remove aspect-tools dependency on the platform.

---

base/src/com/google/idea/blaze/base/projectview/section/sections/AutomaticallyDeriveTargetsSection.java
base/src/com/google/idea/blaze/base/projectview/section/sections/BooleanSectionParser.java
base/src/com/google/idea/blaze/base/projectview/section/sections/Sections.java
base/src/com/google/idea/blaze/base/projectview/section/sections/UseExclusionPatternsSection.java
base/src/com/google/idea/blaze/base/sync/projectstructure/ContentEntryEditor.java
base/tests/unittests/com/google/idea/blaze/base/projectview/ProjectViewSetTest.java

Prior to this change, IntelliJ excluded convenience symlinks by using the `addExcludeFolder` method. Its drawback was that it didn't work perfectly when the file didn't exist during exclusion. This might cause a race condition where some IntelliJ indexers detected new file creation in these directories while the exclusion mechanism hadn't detected the existence of the symlinks themselves.
This issue is addressed by using 'exclusion patterns' instead of 'excluded folders'. Patterns do not require the files to actually exist. However, their drawback is that they will catch files named `bazel-bin` and `bazel-out` nested deep inside the directory hierarchy, not just the top-level ones.
To address this, a project view setting has been added to disable the new behavior.
Fixes #6082
Please note …

perf: avoid scanning convenience symlink directories during initial import

---

base/src/com/google/idea/blaze/base/buildmodifier/BuildFileFormatter.java

Use path to workspace root as `pwd` for `buildifier`

---

base/src/com/google/idea/blaze/base/actions/BlazeMenuGroup.java
base/src/com/google/idea/blaze/base/actions/BlazeProjectAction.java
base/src/com/google/idea/blaze/base/actions/BlazeProjectToggleAction.java
base/src/com/google/idea/blaze/base/ext/IntelliJExtMenu.java
base/src/com/google/idea/blaze/base/ext/IntelliJExtStatusAction.java
base/src/com/google/idea/blaze/base/qsync/ComposePreviewQuerySyncInspectionWidgetActionProvider.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncInspectionWidgetActionProvider.java
base/src/com/google/idea/blaze/base/qsync/action/ReloadProject.java
base/src/com/google/idea/blaze/base/run/exporter/ExportRunConfigurationDialog.java
base/src/com/google/idea/blaze/base/toolwindow/ConsoleView.java
base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java
base/src/com/google/idea/blaze/base/wizard2/BlazeImportProjectAction.java
common/actions/src/com/google/idea/common/actions/ReplaceActionHelper.java

details.
Issue number: #5993
I tired to check every action if EDT is required or BGT is fine. I found no action were as far as I understand BGT would not be fine. I still have limited understanding of this code base and if there is any action where this is unlikely I am happy to check it again more thoroughly.

Added getActionUpdateThread to all actions

---

clwb/src/META-INF/clwb.xml
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeGDBServerProvider.java

details.
Issue number: #5604 
Adds a new registry key `bazel.clwb.debug.fission.disabled` which can be used to prevent CLion from adding the `--fission=yes` flag automatically. This was mentioned as a workaround in the discussion of the issue.

Added registry key to disable fission flag

---

common/util/BUILD
cpp/sdkcompat/BUILD
intellij_platform_sdk/build_defs.bzl

details.
Some users would like to build the plugin for IJ versions outside of release channels. Since changes 5fdf7c36617912b877f288c3f71dc4bbd1dac7bc, one cannot build an IJ version that is not in a release channel (because we hardcode a release channel into a Java file for runtime access).
As a result, this stopped working:
```
bazel build --define=ij_product=intellij-2023.1 //ijwb:ijwb_bazel_zip
```
This PR adds a "freeform" release channel containing all the `DIRECT_IJ_PRODUCTS` that are not in a channel already.

fix(build): Allow for targets outside of release channels

---

build_defs/stamp_plugin_xml.py

to be not bounded to the current EAP build

Fix until-build in EAP compatible plugin releases 

---

base/src/com/google/idea/blaze/base/model/primitives/Label.java
base/src/com/google/idea/blaze/base/sync/workspace/ExecutionRootPathResolver.java
base/src/com/google/idea/blaze/base/sync/workspace/VirtualIncludesHandler.java
base/tests/unittests/com/google/idea/blaze/base/sync/workspace/ExecutionRootPathResolverTest.java
cpp/src/META-INF/blaze-cpp.xml
cpp/src/com/google/idea/blaze/cpp/BlazeCWorkspace.java
cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationResolver.java
cpp/src/com/google/idea/blaze/cpp/IncludeRootFlagsProcessor.java
cpp/tests/integrationtests/com/google/idea/blaze/cpp/BlazeCppResolvingTestCase.java

details.
Issue number: #5300
Followup for #5301. Pass all headers in targets with `include_prefix` with special "-ibazel" flag like that they can be handled by CLion. Also I tried to address all open comments in the pull request.

Followup for Pass path associations as special compiler flags

---

base/src/com/google/idea/blaze/base/actions/BlazeMenuGroup.java
base/src/com/google/idea/blaze/base/actions/BlazeProjectAction.java
base/src/com/google/idea/blaze/base/actions/BlazeProjectToggleAction.java
base/src/com/google/idea/blaze/base/run/exporter/ExportRunConfigurationDialog.java
base/src/com/google/idea/blaze/base/sync/actions/IncrementalSyncProjectAction.java
base/src/com/google/idea/blaze/base/toolwindow/ConsoleView.java
base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java
base/src/com/google/idea/blaze/base/wizard2/BlazeImportProjectAction.java
java/src/com/google/idea/blaze/java/run/hotswap/BlazeHotSwapAction.java

details.
Issue number: #5993
Cherry picked e3b3fa3 and resolved conflicts. Follow up to #6101.

Fixed getActionUpdateThread (backport of e3b3fa3)

---

base/src/com/google/idea/blaze/base/qsync/QuerySync.java
common/experiments/src/com/google/idea/common/experiments/experiment.properties

details.
Recently, upstream has started rolling out a new way of syncing a project (https://github.com/bazelbuild/intellij/pull/5646). This is still in beta, and we've seen some issues reported internally.
We disable it for now, until they stabilize the feature. Users that want to try it can still do so, from their settings menu.

fix(sync): Disable query-sync by default

---

base/src/com/google/idea/blaze/base/sync/workspace/ArtifactLocationDecoderImpl.java

details.
Issue number: #6309
In case of an IOException, only the message and the type of error is logged as a warning. The stack trace is logged only at the lowest level, so as to limit the amount of logs when there are many problematic artifacts.

Reduced the logging level for the stack traces produced when resolving external artifacts.

---

examples/go/with_proto/MODULE.bazel
examples/go/with_proto/go/external/BUILD.bazel
examples/go/with_proto/go/external/README.md
examples/go/with_proto/go/external/external.go
examples/go/with_proto/go/main.go
examples/go/with_proto/go/main_test.go
golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java

Fixes #6324
details.
Issue number: #6324
If the package is literally named "external", the transformation was incorrect. Example:
String from real logs: `/private/var/tmp/_bazel_muldrik/79e0cc1117c2f3c124d7043e835ad8a1/execroot/_main/external/gazelle~~go_deps~io_k8s_sigs_cluster_api/controllers/external/doc.go`
Actual resulting transformation (breaks intellij imports):
`/private/var/tmp/_bazel_muldrik/79e0cc1117c2f3c124d7043e835ad8a1/external/doc.go`
Expected:
`/private/var/tmp/_bazel_muldrik/79e0cc1117c2f3c124d7043e835ad8a1/external/gazelle~~go_deps~io_k8s_sigs_cluster_api/controll …

Fix imports for go modules named "external"

---

base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java

In these cases, bazel reports an error with empty (`''`) package
Follow up of #6262
details.

Fix: Silence false positive "No such target" errors for files in the project root

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/workspace/ExecutionRootPathResolver.java
base/src/com/google/idea/blaze/base/sync/workspace/VirtualIncludesHandler.java
base/tests/unittests/com/google/idea/blaze/base/sync/workspace/ExecutionRootPathResolverTest.java
cpp/src/META-INF/blaze-cpp.xml
cpp/src/com/google/idea/blaze/cpp/BlazeCWorkspace.java
cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationResolver.java
cpp/src/com/google/idea/blaze/cpp/IncludeRootFlagsProcessor.java
cpp/tests/integrationtests/com/google/idea/blaze/cpp/BlazeCppResolvingTestCase.java
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeCompilerSettingsTest.java

details.
Issue number: #6375
Since using clangd (-ibazel) to resolve virtual includes only works with the legacy engine and currently breaks it under some circumstances (see #6375) revert back to the old heuristics based approach by default. To enable the usage of clangd the `bazel.sync.clangd.virtual.include` registry flag can be set to true.

Feature flags for resolve virtual includes using heuristics or clangd

---

base/src/com/google/idea/blaze/base/wizard2/BlazeImportProjectAction.java

details.
Issue number: #6305
Adds invoke later call to project open. Fixes #6305.

Add invoke later call to import project action

---

base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectHelper.java
base/src/com/google/idea/blaze/base/dependencies/ExternalFileProjectManagementHelper.java

Based on #6359 by @dkashyn-sfdc
details.

feat: create "Add package" EditorNotificationPanel if derive_targets_from_directories is on

---

examples/go/with_go_source/with_go_source.bazelproject

fix: disable bzlmod for"with_go_source" example

---

base/src/com/google/idea/blaze/base/projectview/section/sections/Sections.java
base/src/com/google/idea/blaze/base/projectview/section/sections/ViewProjectRootSection.java
base/src/com/google/idea/blaze/base/sync/projectstructure/ContentEntryEditor.java
base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java
base/tests/unittests/com/google/idea/blaze/base/projectview/ProjectViewSetTest.java
base/tests/unittests/com/google/idea/blaze/base/projectview/parser/ProjectViewParserTest.java

details.
https://github.com/bazelbuild/intellij/assets/1066003/29720ae3-bc31-4b05-b9d6-da26d2e9b760

Add 'View project root' flag

---

aswb/BUILD
build_defs/intellij_plugin.bzl
clwb/BUILD
cpp/BUILD
golang/BUILD
ijwb/BUILD
java/BUILD
java/src/META-INF/java-coverage-contents.xml
javascript/BUILD
kotlin/BUILD
plugin_dev/BUILD
python/BUILD
scala/BUILD
terminal/BUILD

fixes #2053
Description in `build_defs/intellij_plugin.bzl`
details.

Allow optional_xml to depend on more than one plugin

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTestRunner.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/aspects/strategy/RenderResolveOutputGroupProviderTest.java
base/src/com/google/idea/blaze/base/command/BlazeCommand.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategy.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java
base/tests/unittests/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyTest.java

Using this flag ensures consistency across commands and prevents large portions of the Skyframe cache from being evicted. This avoids longer analysis phases. To experiment, view the cache summary with `bazel dump --skyframe=summary`.

perf: Pass --override_repository flag to all commands for faster analysis phase

---

intellij_platform_sdk/build_defs.bzl

details.
N/A
Not all environments have `zip` in their path. For instance, some Remote Execution environments like to have very lean workers. Furthermore, we shouldn't rely on all environments having the same version. We replace zip with the bazel jar handler.
We have been using this change internally to build the plugin against our build environment for a few months now.

fix: Rely on the bazel zipper instead of zip

---

java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageData.java
java/tests/unittests/com/google/idea/blaze/java/run/coverage/BlazeCoverageDataTest.java

details.
N/A
Some coverage formats include a SHA in their report. In those cases, the parser failed and no coverage was reported. This PR fixes that.

fix(coverage): Account for SHA in lcov DA parsing

---

intellij_platform_sdk/build_defs.bzl

details.
Issue number: #6468
Switch to use the `@argfile` pattern. As a bonus, we delete a line of Bash, which is always a good thing. I don't have access to a Windows machine, so I'd appreciate if someone with access to one could give it a shot.

fix: Use argfile with bazel zipper

---

aspect/build_dependencies.bzl
aspect/fast_build_info.bzl
aspect/intellij_info_impl.bzl
aspect/java_classpath.bzl

This reverts commit 697b9a9a9fe4d0b3c0672a694d8bbd3a5e5a5d4e.
details.
Issue number: #6474
It seems to be the case that if a project:
- depends directly or transitively on rules_java < 5.3.5 
- or uses bazel <= 6.3.2 
The project can no longer be synced because of an error like this:
```
ERROR: Traceback (most recent call last):
File "<redacted>/external/intellij_aspect/intellij_info_impl_bundled.bzl", line 3, column 37, in <toplevel>
load("@rules_java//java:defs.bzl", "JavaInfo", "java_common")
Error: file '@rules_java//java:defs.bzl' does not contain symbol 'JavaInfo'
```
I would …

Revert "Automatic code cleanup." - Remove dependency on rules_java

---

base/src/com/google/idea/blaze/base/syncstatus/SyncStatusEditorTabTitleProvider.java

It is not executed in read mode by default since 242 https://github.com/JetBrains/intellij-community/commit/c92a99d43581659231d24b22f8c5ac04279c9c4d
fixes #6473
details.

fix: "Read access is allowed from inside read-action" exception when opening a file

---

base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java

fix: Missing directories when view_project_root is on

---

BUILD
WORKSPACE.bzlmod

it is no longer needed as the aspect tools are being built for java 8 via a transition in `repackaged_files` rule (https://github.com/bazelbuild/intellij/blob/master/build_defs/build_defs.bzl#L198)

Remove unused custom java 17 toolchain

---

.bazelci/clion.yml
.bazelci/intellij-ue.yml
.bazelci/intellij.yml

CI build on Windows

---

base/src/META-INF/blaze-base.xml

details.
Issue number: 
There seem to be more issues related to the -ibazel approach then initial discovered. Disable -ibazel collection by default.

Disable include hints (-ibazel) by default

---

base/src/com/google/idea/blaze/base/project/TrustAwareProjectCreator.java

details.
Do not show dialogs to trust if trust checks are disabled in the intellij platform. Project creation code is handled in a custom way in bazel plugin because any project is trusted by default in intellij. However, bazel plugin always creates a fake project in .cl/ij/aswb folder, so the plugin should handle trust checks by itself.

trusted project: respect intellij settings controlling project trustness

---

WORKSPACE.bzlmod
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java
sdkcompat/v223/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v231/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v232/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v233/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v241/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v242/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java

details.
in CLion 2024.2 I change contract for createProcess/createDebugProcess and moved them to background thread from UI thread. However historically CidrDebugProcess and derived classes cannot be created outside of UI thread and it requires local wraps in launchers.

clion: fix broken debug in 2024.2

---

base/src/com/google/idea/blaze/base/actions/FileGitHubIssueAction.java
common/util/src/com/google/idea/async/process/CommandLineTask.java
cpp/src/com/google/idea/blaze/cpp/BlazeCSyncPlugin.java

details.
Issue number: 
CLion freezes every time after sync because the `XcodeCompilerSettings` are resolved under read lock. 
I think we can drop the read lock for the entire workspace update since as far as I can tell nothing actually requires a read lock. And the actual update of the workspace is performed under write lock.
Or we could just move the compiler settings resolution before the read lock is taken. But dropping the read lock might prevent freezes in future.

Fixes after sync freeze on MacOS 

---

base/src/com/google/idea/blaze/base/sync/workspace/WorkspaceHelper.java
cpp/BUILD
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeConfigurationResolverTest.java

details.
Issue number: [5719](https://github.com/bazelbuild/intellij/issues/5719) 
We have pretty big bazel project, and we are using the `rule_jvm_external` pinned feature, which download all the external dependencies to the `{baze-base}/external` dir.  The `external` folder could grow very big. One example the smallest cache folder for us:
```
% echo "Total directories:" $(find {root}/.cache/bazel/arm64/96fb5a4ccfb8aa9cafd25443b98fa7e6/external -type d | wc -l) && du -sh {root}.cache/bazel/arm64/96fb5a4ccfb8aa9cafd25443b98fa7e6/external
Total directories: 54733
5.8G …
```

Improve performance when resolving the workspace root

---

base/src/META-INF/blaze-base.xml

no longer needed after https://github.com/bazelbuild/intellij/commit/aee0a55ad7c54e88535855e72731eb8756f8df86

Remove registration of `IntelliJExtManager`

---

MODULE.bazel.lock
aspect/intellij_info_impl.bzl
aspect/testing/rules/intellij_aspect_test_fixture.bzl
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/noide/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/general/noide/NoIdeTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/dependencies/DependenciesTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javabinary/JavaBinaryTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/JavaLibraryTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl/JavaProtoLibraryTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalalibrary/ScalaLibraryTest.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategy.java
common/experiments/src/com/google/idea/common/experiments/experiment.properties

details.
Issue number: https://github.com/bazelbuild/intellij/issues/1785
reopened https://github.com/bazelbuild/intellij/pull/1786 - Don't build the class jar if source jars are available, as we can use that in conjunction with the interface jar to index the code instead.
For our app it reduces `~30%` of the Jars the IDE will index (from `14484` to `10072`)
As per PR review request I put this feature behind `optimize_building_jars` experiment which is enabled by default. In case an issue is found with this feature this experiment can be disabled by disabled it in the IntelliJ …

Don't build unnecessary jars.

---

cpp/src/com/google/idea/blaze/cpp/CompilerWrapperProviderImpl.java

details.
Issue number: 
My initial perception that bazel only uses a wrapper script on mac was wrong. Checked the bazel sources and as far as I can tell it generates a script on all unix systems.

Fix wrong heuristic for when bazel uses a wrapper script

---

aspect/intellij_info_impl.bzl
base/src/com/google/idea/blaze/base/ideinfo/PyIdeInfo.java
proto/intellij_ide_info.proto
python/src/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategy.java
python/src/com/google/idea/blaze/python/resolve/provider/BazelPyImportResolverStrategy.java
python/tests/unittests/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategyTest.java
python/tests/unittests/com/google/idea/blaze/python/resolve/provider/MockArtifactLocationPsiElement.java

details.
Issue number: [6599](https://github.com/bazelbuild/intellij/issues/6599)
Some `py_...` rules such as `py_binary` and `py_library` allow for an `imports` attribute. The `imports` attribute allows control over how the Python files are vended in terms of modules. This change will mean that the use of the `imports` attribute in Bazel targets is reflected in how the modules are auto-completed and recognized in the IDE.

Implement py imports handling

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTestRunner.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/pluginprocessorjars/BazelPluginProcessorJarTest.java
querysync/javatests/com/google/idea/blaze/qsync/QuerySyncTestUtils.java

Update labels cleanup in tests to account for the new label format with bazel @ head
Fixes: https://github.com/bazelbuild/intellij/issues/6607

Fix test with bazel@head

---

common/util/src/com/google/idea/async/process/CommandLineTask.java

details.
Issue number: 
These assertions should not cause a failure in production. However, java assertions seem to enabled in production.

Use Logger.assertTrue in CommandLineTask

---

base/BUILD
base/src/META-INF/dependency-on-lvcs-impl.xml

fix: "NoClassDefFoundError: com/intellij/history/core/Paths"

---

base/src/com/google/idea/blaze/base/model/primitives/Kind.java

details.
Issue number: [6600](https://github.com/bazelbuild/intellij/issues/6600)
When a Python rule is used such as `py_binary` and the rule is using a pinned Python interpreter, the `ruleName` is coming through as `_transition_py_binary` from the aspect but is still a `py_binary`. This change will still detect the transitioned rule name as `Kind.Provider.create("py_binary", LanguageClass.PYTHON, RuleType.BINARY)` from `PythonBlazeRules.java` so that debugging works for `py_binary`-s that are using the pinned interpreter.
See the issue discussion for further details and an …

handling for rules that involve transitions

---

javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptLibrarySource.java

fix: Exception when opening a JavaScript project

---

base/src/com/google/idea/blaze/base/model/AspectSyncProjectData.java
base/src/com/google/idea/blaze/base/model/BlazeProjectData.java
base/src/com/google/idea/blaze/base/model/ExternalWorkspaceData.java
base/src/com/google/idea/blaze/base/model/primitives/ExternalWorkspace.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProjectData.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/tests/utils/unit/com/google/idea/blaze/base/model/MockBlazeProjectDataBuilder.java
proto/project_data.proto

Issue number: `#6664`
This adds a basic data model for `ExternalWorkspace`. Will be followed up with a runner hooked into the sync machinery that will get / update this internal piece of data. Once this is landed and proper invalidated on sync will be followed by a PR changing `ExternalWorkspaceReferenceFragment` to use this data in completion and resolution.

[#6664] Add basic model for ExternalWorkspaces - 1/n

---

WORKSPACE.bzlmod

chore: Drop support IntelliJ 2021.3 - part 2

---

base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java

fix: Resolve collision between view_project_root and "directories: ."

---

base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/validation/BuiltInRuleAnnotatorTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/validation/GlobValidationTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/validation/LoadStatementAnnotatorTest.java
testing/testcompat/v221/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v222/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v223/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v231/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v232/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v233/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v241/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v242/com/google/idea/sdkcompat/BaseSdkTestCompat.java

It was required to provide backward compatiblity with 212
details.

chore: inline `testAnnotator` wrapper method

---

java/src/com/google/idea/blaze/java/run/producers/NonBlazeProducerSuppressor.java

chore: Remove 212 kotlin producers from the Supressor

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/command/mod/BlazeModRunner.java
base/src/com/google/idea/blaze/base/command/mod/BlazeModRunnerImpl.java
base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java
base/src/com/google/idea/blaze/base/sync/ProjectStateSyncTask.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncProjectState.java
base/tests/unittests/com/google/idea/blaze/base/sync/BlazeSyncManagerTest.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
cpp/src/com/google/idea/blaze/cpp/CppAspectArgsProvider.java

Issue number: `#6664` (#6664)
This adds `ExternalWorkspaceDataProvider` to  pull the output of `blaze mod dumo_repo_mapping` from the sync process and in memory. 
This should be latest bit of "wiring". The next PR should start changing the external reference fragment for completion / resolving.

[#6664] Add a ExternalWorkspaceDataProvider and wire inside the sync - 3/n

---

sdkcompat/v222/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v223/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v231/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v232/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v233/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v241/com/google/idea/sdkcompat/kotlin/KotlinCompat.java

chore: drop 213: Align KotlinCompat among multiple sdkcompat versions

---

base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java

Some blaze workspaces with blaze > MINIMUM_BLAZE_VERSION (7.1.0
have explicitly disabled bzlmod support and this causes
`blaze mod` to fail (which fails the whole sync).
disable the Provider until a more reliable opt-in is found.
Issue number: `6703`, `6664` ( #6703, #6664) 
Disable ExternalWorkspaceDataProvider until a more reliable opt-in mechanism is chosen.
Some blaze workspaces with blaze > MINIMUM_BLAZE_VERSION 
have explicitly disabled bzlmod support and this causes `blaze mod` to fail.

[#6664] Default disable `ExternalWorkspaceDataProvider`

---

base/src/com/google/idea/blaze/base/command/info/BlazeInfo.java
base/src/com/google/idea/blaze/base/command/info/BlazeInfoRunnerImpl.java
base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java
base/src/com/google/idea/blaze/base/sync/ProjectStateSyncTask.java

Issue number: `6664` (#6664)
Issue number: `6703` (#6703)
This change enhances the BlazeInfo collection to also collect the value of `startlark-semantics`. This will tell if any Starlark specific flags have been flipped from default. The flag we care about it `bzlmod`. 
Use this info key contents to gate running of `ExternalWorkspaceDataProvider` (in addition to bazel version).
One thing to note here is: 
it will always run two `blaze info` commands back to back since making it run only one requires whitelisting all the used info flags in one command. If that can be a problem I can change it back to a whitelist but that has the risk of not pulling all the  used flags.

[#6664] Gate `ExternalWorkspaceDataProvider` on bzlmod being enabled

---

WORKSPACE.bzlmod

chore: drop 212: Remove IJ/CL links

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/lang/buildfile/completion/BuildLabelCharFilter.java
base/src/com/google/idea/blaze/base/lang/buildfile/completion/BuildLookupElement.java
base/src/com/google/idea/blaze/base/lang/buildfile/completion/ExternalWorkspaceLookupElement.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/ExternalWorkspaceReferenceFragment.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/LabelReference.java
base/src/com/google/idea/blaze/base/sync/workspace/WorkspaceHelper.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/ExternalWorkspaceCompletionTest.java
base/tests/utils/integration/com/google/idea/blaze/base/lang/buildfile/BuildFileIntegrationTestCase.java
cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationResolver.java
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeConfigurationResolverTest.java

Issue number: #6664, #505
Also add a CharFilter that enable:
* '@' to filter the lookup elements and not hide the lookup.
* '/' to autocomplete selected item

[#6664,#505]: Enable External Workspace completions and tests - 5/n

---

base/src/com/google/idea/blaze/base/bazel/BazelVersion.java
base/src/com/google/idea/blaze/base/command/info/BlazeInfo.java
base/src/com/google/idea/blaze/base/command/info/BlazeInfoRunner.java
base/src/com/google/idea/blaze/base/command/info/BlazeInfoRunnerImpl.java
base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java
base/src/com/google/idea/blaze/base/run/coverage/CoverageUtils.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java

Issue number: #6664 
In PR #6711 I added two back to back bazel info calls.
This PR collapsed  those calls into one.
Also trying to remove an obsolete Service registration.

[#6664]: Collapse two bazel info invocations into one

---

.bazelrc
MODULE.bazel.lock
WORKSPACE.bzlmod

- Add `--enable_workspace` so we can load `rules_scala` from `WORKSPACE.bzlmod`
- Use `--android_sdk=@androidsdk//:sdk` instead of `android_sdk_repository(name = "androidsdk")` which is not available with bazel@head

Changes to prepare for Bazel 8

---

base/src/com/google/idea/blaze/base/command/BlazeFlags.java

Build flags defined in the project view are forwarded to `bazel mod` which breaks sync, since `--define` is not a known option for the mod command.
Not sure if excluding build flags from the mod command is the right way to go. But fixes the sync.

Fix unrecognized options by bazel mod command

---

golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java

Fixes #2213
details.
Issue number: https://github.com/bazelbuild/intellij/issues/2213
I have ran into the same issue and wanted to fix it. I don't know if it is desirable for someone to have a different working directory for "run" and "debug" actions and I'm not familiar enough with the project to make a feature flag for this.
I have tested multiple project layouts to figure out the working directory used for bazel test and the "run" action for the ide. The mattern always seems to match the `<path_to_workspace>/<package_path>` which I went for and which fixed the issues for me. …

Set go DebugConfguration working directory for tests

---

base/src/com/google/idea/blaze/base/lang/buildfile/completion/LabelRuleLookupElement.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/BuildReferenceManager.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/FileLookupData.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/LabelReference.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/LabelUtils.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/PackageReferenceFragment.java
base/src/com/google/idea/blaze/base/lang/projectview/references/ProjectViewLabelReference.java
base/src/com/google/idea/blaze/base/sync/workspace/WorkspaceHelper.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/ExternalWorkspaceCompletionTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/FilePathInExternalWorkspaceCompletionTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/RuleTargetCompletionTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/RuleTargetInExternalWorkspaceCompletionTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/findusages/ExternalWorkspaceFindUsagesTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/references/ExternalWorkspaceReferenceBzlModeTest.java
base/tests/utils/integration/com/google/idea/blaze/base/ExternalWorkspaceFixture.java
base/tests/utils/integration/com/google/idea/blaze/base/lang/buildfile/BuildFileIntegrationTestCase.java

Issue number: #6664, #505
This hould be the last big PR closing those two issues. It adds external workspace prefixed path and rule completion. Semantics should be similar to the current completion semantics. Added tests for it and tweaked the test fixtures to help.

[#6664] Completion of FilePath and targets from external repositories

---

aspect/intellij_info_impl.bzl

details.
Issue number: [6659](https://github.com/bazelbuild/intellij/issues/6659)
For CPP aspect `intellij_info` , check `additional_compiler_inputs` field and use that in swtring expansion as well

Add extra_target

---

base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java
sdkcompat/v223/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java
sdkcompat/v231/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java
sdkcompat/v232/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java
sdkcompat/v233/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java
sdkcompat/v241/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java
sdkcompat/v242/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java
sdkcompat/v243/com/google/idea/sdkcompat/general/AsyncVfsEventsPostProcessorCompat.java

chore: Prepare for 243 bump: move addListeners to SDK compat

---

golang/BUILD
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.ue223
intellij_platform_sdk/BUILD.ue231
intellij_platform_sdk/BUILD.ue232
intellij_platform_sdk/BUILD.ue233
intellij_platform_sdk/BUILD.ue241
intellij_platform_sdk/BUILD.ue242
intellij_platform_sdk/BUILD.ue243
javascript/BUILD

chore: Support Jetbrains IDEs 243 - go and js plugin require json plugin since 243

---

base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java

details.
When `view_project_root: true` and there are overlapping directories, for example:
The repo contains these directories:
- foo
- foo/bar
- foo/baz
And .bazelproject is:
```
view_project_root: true
directories:
foo
foo/bar
```
Then, `foo/baz` will incorrectly be excluded. This is unexpected because it's contained under the `foo` directory.
This commit fixes the behavior, so that files are not excluded if they are under any root directory.

Fix view_project_root with overlapping directories

---

aspect/BUILD
aspect/build_dependencies.bzl
aspect/fast_build_info.bzl
aspect/intellij_info_impl.bzl
aspect/java_classpath.bzl
aspect/java_info.bzl

chore: Aspect templating - 1/n

---

base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java

Issue number: #6807
This makes any failure to execute `bazel mod dump_repo_mapping` a console warning instead of breaking the sync.

[#6807] Make failures `bazel mod dump_repo_mapping` failures silent

---

base/src/com/google/idea/blaze/base/command/mod/BlazeModRunner.java
base/src/com/google/idea/blaze/base/command/mod/BlazeModRunnerImpl.java
base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java

chore: Aspect templating - 2/n

---

base/src/com/google/idea/blaze/base/command/info/BlazeInfo.java
base/src/com/google/idea/blaze/base/command/info/BlazeInfoRunnerImpl.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
java/tests/integrationtests/com/google/idea/blaze/java/fastbuild/FastBuildChangedFilesServiceTest.java

details.
Related to 
Related to #6728. We were relying on the info cache to have java home that bazel uses. After that change the value is no longer provided causing issues on our extension plugin.

Add java home to the blaze info

---

aspect/build_dependencies.bzl
querysync/java/com/google/idea/blaze/qsync/project/ProjectDefinition.java

fix: Query Sync doesn't crash on projects using BUILD.bazel file names

---

.bazelci/android-studio.yml
.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij-ue.yml
.bazelci/intellij.yml

gcc compiler on ubuntu1804 is too old for Bazel@HEAD
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4152#019231ab-a1e4-46bd-916c-7be8b8028756

Update testing platform for ubuntu

---

base/src/com/google/idea/blaze/base/command/info/BlazeInfoProvider.java

[fix] Use parent context in getCachedBlazeInfo

---

aspect/BUILD
aspect/BUILD.aspect
aspect/flag_hack.bzl
aspect/intellij_info_impl.bzl

chore: Aspect templating - 4/n - extract apply_hack.bzl

---

base/src/com/google/idea/blaze/base/command/mod/BlazeModRunnerImpl.java

It is still not documented well, but "<root>" caused crashes on Windows
closes https://github.com/bazelbuild/intellij/issues/6850
details.

fix: Use "" alias for for the root module back

---

base/src/com/google/idea/blaze/base/model/ExternalWorkspaceDataProvider.java

https://github.com/bazelbuild/bazel/issues/22691
details.

Disable bazel deps call. It's unused yet, and could fail

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/BlazeSyncManager.java
base/src/com/google/idea/blaze/base/sync/SyncScope.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectRepositoryProvider.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java
base/src/com/google/idea/blaze/base/util/TemplateWriter.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
clwb/BUILD
clwb/test_defs.bzl
testing/src/com/google/idea/testing/ServiceHelper.java

Moved the aspect templating code to a new SyncListener. This allows for tighter integration with the rest of the plugin and for proper error handling.

SyncListener for aspect templating

---

python/src/com/google/idea/blaze/python/run/BlazePyDebugRunner.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java

[fix] Fix python debugging

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/buildmodifier/BuildifierDownloader.java
base/src/com/google/idea/blaze/base/buildmodifier/BuildifierFormattingService.java
base/src/com/google/idea/blaze/base/buildmodifier/BuildifierNotification.java
base/src/com/google/idea/blaze/base/buildmodifier/DefaultBuildifierBinaryProvider.java
base/tests/integrationtests/com/google/idea/blaze/base/buildmodifier/BuildifierDownloaderTest.java

details.
Issue number: #6626
Adds a new notification with a "download" button. Buildifier is downloaded from the GitHub releases.

Download Buildifier Binary

---

.bazelci/clion.yml
base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java

Scenario
1. Import the project correctly
2. Download a new version of the plugin that contains new templates
Result:
The templates won't be re-realized, old java_info.bzl fil will persist
details.

fix: Re-realize aspect files after plugin update

---

golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java

details.
Issue number: https://github.com/bazelbuild/intellij/pull/6748#issuecomment-2407350654
Ensure that runfiles vars are not incorrectly interpreted relative to the modified working directory (used as of #6748) by making their paths absolute. This matches the logic in Bazel's test setup script.

Set runfiles vars to absolute paths when debugging Go tests

---

base/src/com/google/idea/blaze/base/projectview/section/sections/EnablePythonCodegenSupport.java
base/src/com/google/idea/blaze/base/projectview/section/sections/Sections.java
base/src/com/google/idea/blaze/base/sync/SyncProjectTargetsHelper.java
base/tests/unittests/com/google/idea/blaze/base/projectview/ProjectViewSetTest.java
examples/python/simple_code_generator/tools/intellij/.managed.bazelproject

fix: Disable python codegen support by default

---

docs/starlark_debugger.md

doc: Document the starlark debugger

---

docs/fastbuild.md

doc: Document fast builds

---

java/src/com/google/idea/blaze/java/run/fastbuild/BazelFastBuildTestEnvironmentCreator.java

fix: fast sync with bazel 8 or when --incompatible_use_plus_in_repo_names is on

---

README.md
base/src/com/google/idea/blaze/base/bazel/BazelBuildSystemProvider.java
ijwb/src/META-INF/description.html

doc: Refer to the new docpage

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/editor/BazelEditorTabTitleProvider.java

details.
Since BUILD files all have the same name it's hard to distinguish them, so we can use EditorTabTitleProvider to write full label in the editor tab title
Before: 
After:

Decorate tabs for BUILD files with package name

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/coptsmakevars/CoptsMakeVarsTest.java

details.
Issue number: [6917](https://github.com/bazelbuild/intellij/issues/6917)
This resolves a problem in the test where the pattern for matching `bazel-out` does not accommodate the Mac's directory paths.

Resolve aspect test build issue on mac

---

base/src/com/google/idea/blaze/base/editor/BazelEditorTabTitleProvider.java

details.
If a project isn't imported then do not try to decorate as otherwise tab name has a full path to file.

Do not decorate tabs for BUILD files in non-bazel projects

---

MODULE.bazel

chore: bump bazel version for tests

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/qsync/QuerySyncHighlightingFilter.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncHighlightingSettingProvider.java

fix(qsync): Enable basic syntax highlighting in 'analysis disabled' mode

---

base/src/com/google/idea/blaze/base/qsync/ProjectQuerierImpl.java
base/src/com/google/idea/blaze/base/sync/ProjectStateSyncTask.java

details.
Issue number: (https://github.com/bazelbuild/intellij/issues/6943)

Use git info only when Expand to Working Set is enabled

---

.bazelrc
aspect/intellij_info_impl.bzl
clwb/BUILD
clwb/tests/integrationtests/com/google/idea/blaze/clwb/ExternalIncludesTest.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/SimpleTest.java
clwb/tests/projects/external_includes/.bazelrc
clwb/tests/projects/external_includes/MODULE.bazel
clwb/tests/projects/external_includes/main/BUILD
clwb/tests/projects/external_includes/main/test.cc
clwb/tests/projects/simple/WORKSPACE
clwb/tests/projects/simple/main/BUILD
clwb/tests/projects/simple/main/test.cc

Issue number: #4980
Forwards all external_includes from the compilation context to system includes since they are treated the same. Also modifies the simple integration test to test for external includes. Closes #4980

CLion external include support

---

base/src/com/google/idea/blaze/base/ui/BlazeModuleRendererFactory.java

fix: NPE in location provider

---

base/src/com/google/idea/blaze/base/qsync/CandidatePackageFinder.java
base/src/com/google/idea/blaze/base/qsync/action/AddToProjectAction.java

A comment contains a warning that there should be at least two packages found in order to provide user a choice. However in some cases there is only a single package to add.
For this reason, we stop the lookup if it reaches project root, but we don't add a package automatically, so a user can always reject the change.
closes #6966
https://github.com/user-attachments/assets/593377c4-84d6-48e1-89a5-6ebc9beb0c9e
details.

fix(qsync): NPE in "Add to project" panel action

---

clwb/BUILD
common/BUILD
common/pluginIcon.svg
ijwb/BUILD

details.
We'd like to make plugin more discoverable in the
search output on the marketplace and also make its tile 
look nice on the staff-picked plugins page.
approved by @meistert by email

Use bazel icon for plugin logo

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTestRunner.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectRepositoryProvider.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/OverrideFlags.java
java/src/com/google/idea/blaze/java/fastbuild/BazelFastBuildAspectStrategy.java
java/src/com/google/idea/blaze/java/run/hotswap/JavaClasspathAspectStrategy.java

closes #6984
there's still a known limitation - you can't downgrade Bazel from 8 to 7, but I'll handle that later
details.

fix: Support bazel 8 and `--noenable_workspace` mode

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/qsync/QuerySyncInspectionWidgetActionProvider.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncNotificationProvider.java

Fix querysync widget for remote dev

---

base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java

Previously, the condition to load rules_java was based on the "additional languages" field, which led to issues as Java is always present in IntelliJ (unlike PyCharm). This change modifies the condition to explicitly check if rules_java is actually loaded in the project, ensuring proper handling of non-Java projects in IntelliJ.
details.

fix: Properly support non-Java Bazel 8 projects in IntelliJ

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoader.java
base/src/com/google/idea/blaze/base/vcs/BlazeVcsHandlerProvider.java

Cherry pick AOSP commit [1ceafed6aad1f8ac6a737ac5012f4ee3022b9a2c](https://cs.android.com/android-studio/platform/tools/adt/idea/+/1ceafed6aad1f8ac6a737ac5012f4ee3022b9a2c).
Helper methods should not be implemented as interface default methods.
They should be static methods.
Bug: n/a
Test: n/a
Change-Id: I02abafe3e981df4540589d727bdd30a3d9e18bd5

[AOSP-pick] Inline trivial default interface method

---

base/src/com/google/idea/blaze/base/project/indexing/FileSystemWarmUpService.kt

we've received this change from AOSP recently and then discovered that on large projects it does 50-threads rescans every minute and makes the IDE basically unusable.
details.

disable warmup service

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncNotificationProvider.java

buildDepsHelper.getSourceFileMissingDepsCount will check if toBuild is really a SOURCE one
details.

fix(qsync): NPE in QuerySyncNotificationProvider

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/qsync/ProjectLoader.java

Cherry pick AOSP commit [9c2f4c7143874defeb9cb9c69f69168975f38d5b](https://cs.android.com/android-studio/platform/tools/adt/idea/+/9c2f4c7143874defeb9cb9c69f69168975f38d5b).
Fetching multiple info files sequentially is slow especially whey they
are enormous in size. (The total size reaching 6gb+).
Instead fetch artifacts through the `BuildArtifactCache` which already
handles parallel and asynchronous downloading well.
Also, remove the `qsync.parallel.artifact.info.fetch` experiment as it
not longer controls anything. Info files are not different to other
artifacts and thus the same mode that works for other artifacts should
work for info files.
Bug: n/a
Test: n/a
Change-Id: I6f023154ca318af390956e78678dc899a359d31d
AOSP: 9c2f4c7143874defeb9cb9c69f69168975f38d5b

[AOSP-pick] Use BuildArtifactCache to fetch -info.txt files

---

querysync/javatests/com/google/idea/blaze/qsync/AspectUnitTest.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/BUILD
querysync/javatests/com/google/idea/blaze/qsync/testdata/JavaInfoTxt.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/TestData.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/workspacerootincluded/BUILD
querysync/javatests/com/google/idea/blaze/qsync/testdata/workspacerootincluded/MyClass.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/workspacerootincluded/collect_deps.bzl

Cherry pick AOSP commit [43bfac8a806e125bdea33a7270f359fc1454b33b](https://cs.android.com/android-studio/platform/tools/adt/idea/+/43bfac8a806e125bdea33a7270f359fc1454b33b).
NOTE: conflicts with our changes to `aspect/build_dependencies.bzl`, but as far as I can tell ours handles more edge cases.
Change-Id: I2d28bf336e95c410da5f159b6bc37a38b7139f72
Bug: 309706901
Tests: manual and presubmit tests
AOSP: 43bfac8a806e125bdea33a7270f359fc1454b33b

[AOSP-pick] [querysync] Fix building dependencies when workspace root is included

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java
java/src/com/google/idea/blaze/java/run/producers/JavaBinaryContextProvider.java
querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java
querysync/java/com/google/idea/blaze/qsync/GraphToProjectConverter.java
querysync/java/com/google/idea/blaze/qsync/QuerySyncProjectSnapshot.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/query/QuerySummary.java
querysync/java/com/google/idea/blaze/qsync/query/querysummary.proto
querysync/javatests/com/google/idea/blaze/qsync/BUILD
querysync/javatests/com/google/idea/blaze/qsync/GraphToProjectConverterTest.java
querysync/javatests/com/google/idea/blaze/qsync/PartialProjectRefreshTest.java
querysync/javatests/com/google/idea/blaze/qsync/project/BuildGraphDataTest.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySummaryTestBuilder.java
shared/java/com/google/idea/blaze/common/BUILD

Cherry pick AOSP commit [11ec4229bdd494a9bcb466728abc3a201cc2423d](https://cs.android.com/android-studio/platform/tools/adt/idea/+/11ec4229bdd494a9bcb466728abc3a201cc2423d).
It is not needed. Labels can be made more efficient in the future by
splitting package and name parts.
Bug: 362727747
Test: existing unit tests
Change-Id: I05af42a434a238729a8d63ee756bf6e44c18a814
AOSP: 11ec4229bdd494a9bcb466728abc3a201cc2423d

[AOSP-pick] Do not store file to label map

---

base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java

Before the change: debug on java binary is failing due to not having access to aspect templates
After the change: debug on java binary is successful

fix issues with aspect templates not available in query sync mode

---

base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java

fix: Don't require rules_java and rules_python for bazel 7 and older

---

CHANGELOG
aspect/intellij_info_impl.bzl
aspect_template/BUILD
aspect_template/python_info.bzl
base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java

V2024.11.05 hotfix

---

base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/src/com/google/idea/blaze/base/vcs/BlazeVcsHandlerProvider.java
base/src/com/google/idea/blaze/base/vcs/FallbackBlazeVcsHandlerProvider.java
base/src/com/google/idea/blaze/base/vcs/git/GitBlazeVcsHandlerProvider.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/MockBlazeVcsHandlerProvider.java

Cherry pick AOSP commit [cb89e1d2aff31858d26a4044de9253c972e0c219](https://cs.android.com/android-studio/platform/tools/adt/idea/+/cb89e1d2aff31858d26a4044de9253c972e0c219).
There is no need to parse URIs when their components are accessible
directly.
This is in preparation to a unified Bazel VCS handler.
Bug: n/a
Test: n/a
Change-Id: I9c97f6e4ddcf56a76a6b9831c34972a4e7e7c2c3
AOSP: cb89e1d2aff31858d26a4044de9253c972e0c219

[AOSP-pick] Expose bazel workspace_status to handlers

---

golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java

This fixed the indexing problem caused by retrieving the wrong package name.
fixes #7010
details.
Issue number: `7010`
getPackageName wrongly returns "ignore" which should be ignored. This change will check "build ignore" (the build tag) and respect this tag (that is, ignore files containing this tag).

Fix getPackageName which didn't respect "build ignore"

---

java/src/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlags.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaAbstractTestCaseConfigurationProducerTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaTestClassConfigurationProducerTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/MultipleJavaClassesTestContextProviderTest.java
java/tests/unittests/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlagsTest.java

The JUnit 5 selector for methods does not support a trailing #.
This is easy to verify:
```
> java -jar junit-platform-console-standalone-<version>.jar execute -cp <my tests jar> --select-class=<my test class>
```
will work, while
```
> java -jar junit-platform-console-standalone-<version>.jar execute -cp <my tests jar> --select-class=<my test class>#
```
will fail.
This will change `--test_filter`'s value from `<my test class>#` to `<my test class>` when filtering for classes. The new value requires no postprocessing and is directly compatible with JUnit's selector "language".
The trailing # was introduced in https://github.com/bazelbuild/intellij/pull/4473/. This undocumented breaking change created issues for our own test runner.
Please note that the maintainers will not be reviewing …

Stop adding a trailing # when filtering tests for JUnit 5

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/buildview/BuildViewScope.kt
base/src/com/google/idea/blaze/base/buildview/PtyConsoleView.kt
base/src/com/google/idea/blaze/base/command/BuildFlagsProviderImpl.java
gazelle/tests/integrationtests/com/google/idea/blaze/gazelle/sync/RunGazelleOnSyncTest.java
shared/java/com/google/idea/blaze/common/PrintOutput.java

In order to get all the relevant information form bazel it has to be executed with `--curses=yes` and connected to a pty enabled terminal. This shows use full information like the download progress.

PTY enabled terminal for the new sync view

---

querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/query/QuerySummary.java

fix(qsync): Include runtime_deps in the target graph

---

base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java

details.
https: //github.com/bazelbuild/intellij/pull/6767 introduces a regression. While it fixes the bug with overlapping directories, it causes too many directories to now become included. This happens because the change avoids excluding files under any root directory, however the project root itself is a root directory when `view_project_root` is set. This results in nothing getting excluded, which defeats the purpose of view_project_root (it behaves the same as just adding `.` into directories).
The fix is to only …

Fix over-including when view_project_root is set.

---

aspect/build_dependencies.bzl
aspect/build_dependencies_deps.bzl

Cherry pick AOSP commit [489884f04a1e4be2d3df6b6758989c26ac0c1654](https://cs.android.com/android-studio/platform/tools/adt/idea/+/489884f04a1e4be2d3df6b6758989c26ac0c1654).
1. Include `srcs` like attributes
2. Wrap `JavaInfo` provider
Bug: 379999838
Test: n/a
Change-Id: Ie9205f5fee2203c5aa3b1e80f2e1fd9171fbe645
AOSP: 489884f04a1e4be2d3df6b6758989c26ac0c1654

[AOSP-pick] Begin extracting IDE_JAVA aspect interface

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt

fix: Sync failure after non-fatal bazel failure

---

aspect/intellij_info_impl.bzl
kotlin/src/com/google/idea/blaze/kotlin/KotlinBlazeRules.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/7114
Fixes https://github.com/bazelbuild/intellij/issues/7114.
rules_kotlin has moved to using a special _kt_toolchain attribute, but it looks like the plugin is unable to properly read them. This commit fixes the output group `intellij-info-kt` (instead of `intellij-info-kotlin`) and adds rule kinds so that the plugin recognizes the toolchain.

Fix reading of _kt_toolchain attribute

---

aspect/intellij_info_impl.bzl

It has been accidentally removed here
https://github.com/bazelbuild/intellij/commit/a88c6db967cd173fa73aeb76d8c8c7bbd0f8be3d#diff-7e834e0a725805ad4dfd127ba905e50964c78307ddb756da99d15a0a1ea28a46L1117-R1124
details.

fix: Kotlin toolchain detection

---

querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java
querysync/java/com/google/idea/blaze/qsync/PartialProjectRefresh.java
querysync/java/com/google/idea/blaze/qsync/query/QueryData.java
querysync/java/com/google/idea/blaze/qsync/query/QuerySummary.java
querysync/java/com/google/idea/blaze/qsync/query/querysummary.proto
querysync/javatests/com/google/idea/blaze/qsync/AffectedPackagesTest.java
querysync/javatests/com/google/idea/blaze/qsync/BUILD
querysync/javatests/com/google/idea/blaze/qsync/PartialProjectRefreshTest.java
querysync/javatests/com/google/idea/blaze/qsync/TestDataSyncRunner.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySummaryTest.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySummaryTestBuilder.java
shared/java/com/google/idea/blaze/common/Label.java

Cherry pick AOSP commit [fc03bee23b88e04806ed4eacc8b521f9a25b7880](https://cs.android.com/android-studio/platform/tools/adt/idea/+/fc03bee23b88e04806ed4eacc8b521f9a25b7880).
1. Finish transitioning query sync phase storage to indexed strings
2. Break labels up into workspace, package and name. This is to make
unique strings shorter and faster to compare.
3. Use `Label`s in internal data structures instead of strings to avoid
frequent parsing string parsing and conversion to labels.
Bug: 362727747
Test: existing unit tests
Change-Id: I149f751c0498c13e61208e7314b8a2be636eedcc
AOSP: fc03bee23b88e04806ed4eacc8b521f9a25b7880

[AOSP-pick] Improve performance and decrease memory usage

---

base/src/META-INF/blaze-base.xml

I am always looking for the "import bazel project" action in this drop down, until I remember it is under file. Thus, I would like to suggest to also add it there.

Add import project action to project drop down

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/toolwindow/ConsoleView.java

In #7001 I accidentally also enabled curses when using the old sync view. This PR adds the appropriate checks to disable curses when using the old sync view.

Do not use curses with the old sync view

---

kotlin/src/META-INF/blaze-kotlin.xml

Addresses https://github.com/bazelbuild/intellij/issues/7121
details.
Issue number: https://github.com/bazelbuild/intellij/issues/7121
To support K2 mode, plugins need to explicitly opt-into it even if they don't use the Analysis APIs. https://kotlin.github.io/analysis-api/declaring-k2-compatibility.html
I built the plugin manually locally and verified with IDE with
```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-2024.2
```
After adding this and enabling K2 mode, the Kotlin plugin works

Add support for K2 mode

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt

Since Bazel is invoked using the PtyCommandLine it seems to automatically enable curses. Therefore, to prevent this when using the old sync view this PR adds the explicit --curses=no option.

Keep bazel from automatically enabling curses with the old sync view

---

.bazelignore

It seems to affect Renovate
details.

chore: Remove examples from bazelignore

---

java/src/com/google/idea/blaze/java/qsync/GeneratedSourcesStripper.java

fix: IndexNotReadyException during 'Enable Analysis'

---

maintenance/BUILD
maintenance/maintenance.kt

Maintenance script

---

aspect/build_dependencies.bzl

fix(qsync): Handle codegen - generic case

---

java/src/com/google/idea/blaze/java/sync/importer/emptylibrary/EmptyLibraryFilter.java
java/tests/unittests/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporterTest.java

Partially related to https://github.com/bazelbuild/intellij/issues/6547
The EmptyJarFilter is using a heuristic that is really not robust
https://github.com/bazelbuild/intellij/blob/3f81565b4aede217e160adc97a3f3b619bfa0498/java/src/com/google/idea/blaze/java/sync/importer/emptylibrary/EmptyLibraryFilter.java#L42-L50
details.

fix: Small codegen libraries were removed from the Project Structure

---

clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java

it wasn't checked back in the days that the change did not break the flow on mac/windows/linux with gdbserver disabled
fixes #7166
details.
Issue number: #7166

clion: fix non-passed env vars for gdbserverless debugging

---

base/src/com/google/idea/blaze/base/settings/Blaze.java

stick to the existing project type if project view is not valid
fixes #7155
details.
Issue number: `#7155`

handle non-valid project view file on reload

---

aspect/build_dependencies.bzl
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
clwb/BUILD
clwb/test_defs.bzl
clwb/tests/integrationtests/com/google/idea/blaze/clwb/QuerySyncTest.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/base/ClwbIntegrationTestCase.java
cpp/src/com/google/idea/blaze/cpp/qsync/CcProjectModelUpdateOperation.java

This PR provides basic support for qsync in CLion, but only for linux with gcc so far. Issues addressed:
- cc_info_file and cc_toolchain_info propagation in the aspect
- project model setup in CLion
Also adds a simple integration test that imports the project using query sync.

Basic qsync support in CLion for linux

---

clwb/src/com/google/idea/blaze/clwb/radler/RadBinaryContextProvider.kt
clwb/src/com/google/idea/blaze/clwb/radler/optional-plugin.xml
clwb/src/com/google/idea/blaze/clwb/run/producers/NonBlazeProducerSuppressor.java

Builds up on the work of #7062 and adds support for binary run configurations in CLion. Double run button in nova will be fixed in 251.

Adds support for the run button on main functions in nova 

---

clwb/src/com/google/idea/blaze/clwb/radler/RadCatchTestContextProvider.kt
clwb/src/com/google/idea/blaze/clwb/radler/RadTestContextProvider.kt
clwb/src/com/google/idea/blaze/clwb/radler/optional-plugin.xml

Adds a test context provider for catch2 tests based on the work done for google tests. I also tried to provide a context provider for boost tests, however they don't play nicely with our current test infrastructure in the plugin.

Add catch2 test support in CLion

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/toolwindow/ConsoleView.java

bugfix for v2024.12.03 release

---

base/tests/unittests/com/google/idea/blaze/base/sync/workspace/ExecutionRootPathResolverTest.java
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeCompilerSettingsTest.java

details.
Cleanup for a registry key removed a while ago.

cleanup: remove non-existing key

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java

details.
Issue number: [`7200`](https://github.com/bazelbuild/intellij/issues/7200)

Allow to boost `.ijwb` over BSP and .idea folder.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java

* Allow to boost `.ijwb` over BSP and .idea folder.
* Smarter default in case BSP not installed
* Google plugin has no priority by default and used if JetBrains Bazel is not installed. If BSP is there then registry key value is used.
fixes #7200
(cherry picked from commit d407faba3e52e32a929aa9581f4412f474b01a96)
details.

Allow to boost `.ijwb` over BSP and .idea folder. (#7201)

---

base/src/com/google/idea/blaze/base/lang/buildfile/psi/FuncallExpression.java
base/src/com/google/idea/blaze/base/lang/buildfile/validation/BuiltInRuleAnnotator.java
cpp/src/com/google/idea/blaze/cpp/HeaderRootTrimmer.java

Fixes false positives like this:

Fix red code in MODULE.bazel

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
clwb/test_defs.bzl

Cherry pick AOSP commit [acc58667d8d5a37593bb0b161a4df0628694e9cd](https://cs.android.com/android-studio/platform/tools/adt/idea/+/acc58667d8d5a37593bb0b161a4df0628694e9cd).
locations in order to ignore any user configured values after a
workaround was suggested.
Bug: 379999838
Test: n/a
Change-Id: I4a00df094ad044c28802a83511a199624142e10f
AOSP: acc58667d8d5a37593bb0b161a4df0628694e9cd

[AOSP-pick] Rename properties that specify aspect file

---

java/src/com/google/idea/blaze/java/run/BlazeJavaRunProfileState.java

Cherry pick AOSP commit [8e747db32fde69d20ae904fdcfed0c2b502c5585](https://cs.android.com/android-studio/platform/tools/adt/idea/+/8e747db32fde69d20ae904fdcfed0c2b502c5585).
Bug: n/a
Test: n/a
Change-Id: I5b2579d0e7a829073913d5586d27745003b59f4c
AOSP: 8e747db32fde69d20ae904fdcfed0c2b502c5585

[AOSP-pick] Break a huge method into two

---

base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java

Cherry pick AOSP commit [d151fd6f42820d7993c60350bd3a65b8dff2eef9](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d151fd6f42820d7993c60350bd3a65b8dff2eef9).
Bug: n/a
Test: n/a
Change-Id: Iaf9ce8351a5d1c8cf43455ae65e3d753a3e26f9e
AOSP: d151fd6f42820d7993c60350bd3a65b8dff2eef9

[AOSP-pick] Allow limiting parallel BEP parsing

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelper.java
clwb/BUILD
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/BUILD
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/BUILD
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [ccf72a5c77927d76c9e7cf55378ea1fc6aec6334](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ccf72a5c77927d76c9e7cf55378ea1fc6aec6334).
Utility methods are supposed to be static in preferably in utility
classes or as Kotlin extension methods.
This is to enable safe and bigger refactoring of this area of code.
Bug: n/a
Test: n/a
Change-Id: I9dd7c5515c3289b05042299c6aea3d5c70c70180
AOSP: ccf72a5c77927d76c9e7cf55378ea1fc6aec6334

[AOSP-pick] Remove default helper methods in BuildResultHelper

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java

Cherry pick AOSP commit [a63da90df16ee9a14c116045b95dcb60c0992b27](https://cs.android.com/android-studio/platform/tools/adt/idea/+/a63da90df16ee9a14c116045b95dcb60c0992b27).
Do not parse build output twice.
Bug: n/a
Test: n/a
Change-Id: I1a002a69cd6e3f2fbbbe445c7e1d4833449c2b9f
AOSP: a63da90df16ee9a14c116045b95dcb60c0992b27

[AOSP-pick] Tiny optimization when handling errors

---

querysync/java/com/google/idea/blaze/qsync/query/QuerySummary.java
shared/java/com/google/idea/blaze/common/Label.java
shared/javatests/com/google/idea/blaze/common/LabelTest.java

Cherry pick AOSP commit [ac4b2a16dcabf514cc200d6a5b802cb170ab7482](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ac4b2a16dcabf514cc200d6a5b802cb170ab7482).
Skip empty attributes as empty labels cannot be created.
Bug: 380927265
Test: n/a (To be added separately as it requires some preparation)
Change-Id: I3f43f9ae18d6953129fa2c65f14844e3472f9352
AOSP: ac4b2a16dcabf514cc200d6a5b802cb170ab7482

[AOSP-pick] Do not instantiate empty labels

---

.managed.bazelproject
clwb/clwb.bazelproject
ijwb/ijwb.bazelproject

This is the configuration I am currently using for query sync to develop either ijwb or clwb. Since this configuration can be used for both products I would suggest creating one managed project view file in the root of the project, but keep the product specific ones for aspect sync.

Add a managed project view file for query sync

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestLaunchTask.java
base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/command/CommandLineBlazeCommandRunner.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildEventStreamProvider.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperBep.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/run/testlogs/LocalBuildEventProtocolTestFinderStrategy.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
base/tests/unittests/com/google/idea/blaze/base/run/testlogs/LocalBuildEventProtocolTestFinderStrategyTest.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BepUtils.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildResultHelperBep.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [47436ebddcad73d6a5d4bf1d8ab8a8ccbe1c2235](https://cs.android.com/android-studio/platform/tools/adt/idea/+/47436ebddcad73d6a5d4bf1d8ab8a8ccbe1c2235).
Separate BEP fetching and parsing
This is to enable independent changes to both processes.
1. Introduce a `BuildResultHelper.getBepStream()` method that knows
how to get a BEP stream. Each `BuildResultHelper` gets its own
implementation.
2. Re-implement other methods like `getBuildOutput()` to operate on
externally supplied `BuildEventStreamProvider`. These methods should
not eventually depend on a specific implementation of
`BuildResultHelper` and will be moved out soon.
3. Update tests accordingly.
Bug: n/a
Test: existing
Change-Id: I48f6cf5d19889e60c6795c1b097243cd7006c686
AOSP: …

[AOSP-pick] Separate BEP fetching and parsing

---

base/src/com/google/idea/blaze/base/dependencies/TargetInfo.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProjectData.java

In some cases query sync might return some labels that cannot be validated later on. The actual fix would be to fix query sync to exclude these invalid labels; this just addresses the symptom.

make label parsing more resilient

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoader.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java
base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java
querysync/java/com/google/idea/blaze/qsync/project/PostQuerySyncData.java
querysync/java/com/google/idea/blaze/qsync/project/ProjectDefinition.java
querysync/java/com/google/idea/blaze/qsync/project/SnapshotDeserializer.java
querysync/java/com/google/idea/blaze/qsync/project/snapshot.proto
querysync/javatests/com/google/idea/blaze/qsync/GraphToProjectConverters.java
querysync/javatests/com/google/idea/blaze/qsync/ProjectRefresherTest.java
querysync/javatests/com/google/idea/blaze/qsync/TestDataSyncRunner.java
querysync/javatests/com/google/idea/blaze/qsync/project/ProjectDefinitionTest.java
querysync/javatests/com/google/idea/blaze/qsync/project/SnapshotSerializationTest.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/ProjectProtos.java

Cherry pick AOSP commit [f57818820af2d29c97334904bc4b643511b4d711](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f57818820af2d29c97334904bc4b643511b4d711).
these folders should be excluded and scanning them for BUILD files slows down the initial import step
Change-Id: Id2587b18ee38a7d4f99b7b9b8b88e7584e261a8f
Bug: 309706901
Tests: presubmits
AOSP: f57818820af2d29c97334904bc4b643511b4d711

[AOSP-pick] [querysync] Do not scan Bazel system directories for BUILD files

---

aspect/java_classpath.bzl
base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectStorageService.kt
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java

Issue number: #7260
One intellij_aspect_template reference was left in java_classpath.bzl causing it to fail at runtime. Also, just to make sure the aspects are present, call AspectStorageService.prepare before using them.

Fix aspect_template reference in java_classpath aspect

---

MODULE.bazel
MODULE.bazel.lock

I must have missed this during review. But the CLion version was pointing to the latest EAP, breaking builds due to sha mismatch.

Bump CLion to fixed version

---

base/src/com/google/idea/blaze/base/qsync/UnsyncedFileEditorNotificationProvider.java
base/src/com/google/idea/blaze/base/qsync/settings/QuerySyncConfigurable.java
base/src/com/google/idea/blaze/base/qsync/settings/QuerySyncSettings.java

Cherry pick AOSP commit [39d8b044d86236f31598799a368b787a7ad8f64f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/39d8b044d86236f31598799a368b787a7ad8f64f).
1. remove them from ui
2. set the value as false to disable them temporarily
3. remove enable auto sync option in banner
Bug: b/382306540
Test: manually
Change-Id: I16dbb5e14c7617454e7ced5268b65fd39c750a9b
AOSP: 39d8b044d86236f31598799a368b787a7ad8f64f

[AOSP-pick] Remove 2 options of query sync settings

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestLaunchTask.java
base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/command/CommandLineBlazeCommandRunner.java
base/src/com/google/idea/blaze/base/command/buildresult/BepArtifactData.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperBep.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultParser.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/run/testlogs/LocalBuildEventProtocolTestFinderStrategy.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildResultHelperBep.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [04942f41fd1bc7b11d9906c4ebeeea388fa9f3e4](https://cs.android.com/android-studio/platform/tools/adt/idea/+/04942f41fd1bc7b11d9906c4ebeeea388fa9f3e4).
This is to enable independent changes to both processes.
Replace almost identical copies of `getBuildOutput()` and similar
methods in `BuildResultHelper` implementations with `BuildResultParser`
utility methods.
Prefer exceptions to empty results where failures were reported
differently.
Bug: n/a
Test: existing
Change-Id: I23fbd78c8798795ba9a758ece35e4a0b8e2efeaf
AOSP: 04942f41fd1bc7b11d9906c4ebeeea388fa9f3e4

[AOSP-pick] Continue separating BEP fetching and parsing

---

aspect/BUILD
aspect/xcode_query.bzl
clwb/tests/integrationtests/com/google/idea/blaze/clwb/SimpleTest.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/base/Assertions.java
cpp/src/com/google/idea/blaze/cpp/XcodeCompilerSettingsProviderImpl.java

Followup for #7193 after #7202 was merged.
Bazel 8 introduced new provider located in apple_common module,
which is not available in cquery context, so the implementation
was updated to just find a provider with required attributes to
make implementation also work for bazel 7 and older.

Followup: query xcode parameters from provider based on attributes

---

querysync/java/com/google/idea/blaze/qsync/query/BUILD

Cherry pick AOSP commit [606614a93ac85d38cadab53c31536ae273c9b155](https://cs.android.com/android-studio/platform/tools/adt/idea/+/606614a93ac85d38cadab53c31536ae273c9b155).
This is to prevent upcoming changes break at runtime.
Bug: 383454198
Test: n/a
Change-Id: I4f79d39eab41d412f0d67ed34660d5c711d7bed4
AOSP: 606614a93ac85d38cadab53c31536ae273c9b155

[AOSP-pick] Fix _proto deps that are supposed to be proto_deps

---

base/src/com/google/idea/blaze/base/actions/FileGitHubIssueAction.java

This reverts commit 68cfd5f0ddc5da1406b45c1a1a29171876f6030f (#7277).

Revert "Hide `FileGitHubIssueAction` as Github is no longer used to track issues against ASwB (#7277)"

---

aspect/intellij_info_impl.bzl

If the configuration is not defined for the java runtime, this can cause toolchain resolution issues at runtime.

Add cfg exec to java runtime required by aspects

---

aspect/python_info.bzl
base/src/com/google/idea/blaze/base/run/testmap/ProjectSourceToTargetFinder.java
base/src/com/google/idea/blaze/base/run/testmap/TargetInfoComparator.java
base/tests/unittests/com/google/idea/blaze/base/run/testmap/TargetInfoComparatorTest.java
querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySpecTest.java

details.
Issue number: [7196](https://github.com/bazelbuild/intellij/issues/7196)
- The change will recognize Kinds with a `_transition_` prefix as being the Kind with with `_transition_` prefix stripped.
- The selection of the Target to map to from a source file will avoid, where possible, any with a `_` prefix.
- The Python templated aspect logic will allow the `rules_python` `PyInfo` provider to be considered with Bazel < 8. I am unsure of all the wider ramifications of this so it may require some discussion. I think internal Bazel rules were dropped on Bazel 5 so perhaps it is …

handling for debugging python test targets with transitions

---

base/src/com/google/idea/blaze/base/run/testmap/ProjectSourceToTargetFinder.java

details.
Issue number: #7198 
Immutability of collections that we return is an important part of the contract.

Return sorted sets (follow-up to #7198)

---

intellij_platform_sdk/BUILD.clion251

Update BUILD.clion251 to reflect layout changes in the latest EAP.

Fix CLion integration tests for EAP

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
querysync/java/com/google/idea/blaze/qsync/deps/ArtifactTrackerStateDeserializer.java
querysync/java/com/google/idea/blaze/qsync/deps/ArtifactTrackerStateSerializer.java
querysync/java/com/google/idea/blaze/qsync/deps/DependencyBuildContext.java
querysync/java/com/google/idea/blaze/qsync/deps/artifact_tracker_state.proto
querysync/javatests/com/google/idea/blaze/qsync/deps/ArtifactDirectoryBuilderTest.java
querysync/javatests/com/google/idea/blaze/qsync/deps/ArtifactTrackerStateSerializationTest.java
querysync/javatests/com/google/idea/blaze/qsync/java/AddProjectGenSrcsTest.java

Cherry pick AOSP commit [59eef1099056ea319a15d6afc36cd5b4ede11365](https://cs.android.com/android-studio/platform/tools/adt/idea/+/59eef1099056ea319a15d6afc36cd5b4ede11365).
as it complicates build output handling simplification.
VCS state in the artifact tracker is currently unused.
Bug: n/a
Test: n/a
Change-Id: If4d8d94538168024ef30fa327d7763049adce3d8
AOSP: 59eef1099056ea319a15d6afc36cd5b4ede11365

[AOSP-pick] Delete currently unused fields

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperBep.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/ParsedBepOutput.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BepUtils.java

Cherry pick AOSP commit [300518bc59dc4d72c797a07bbd786d779b5d68ac](https://cs.android.com/android-studio/platform/tools/adt/idea/+/300518bc59dc4d72c797a07bbd786d779b5d68ac).
This is a step towards having a simpler and faster implementation for
the needs of the query sync that does not support sharding.
Bug: 327638725
Test: n/a (existing)
Change-Id: I6a67096c23e18f433abaf24f74461cbe6f29638a
AOSP: 300518bc59dc4d72c797a07bbd786d779b5d68ac

[AOSP-pick] Separate BEP parsing and data

---

aswb/src/com/google/idea/blaze/android/libraries/RenderJarCache.java
aswb/src/com/google/idea/blaze/android/sync/aspects/strategy/RenderResolveOutputGroupProvider.java
base/src/com/google/idea/blaze/base/qsync/BazelAppInspectorBuilder.java
base/src/com/google/idea/blaze/base/qsync/BazelRenderJarBuilder.java
base/src/com/google/idea/blaze/base/qsync/GroupedOutputArtifacts.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java

Cherry pick AOSP commit [c47d961501bca50da2e2c5bfd4129f214cc69a46](https://cs.android.com/android-studio/platform/tools/adt/idea/+/c47d961501bca50da2e2c5bfd4129f214cc69a46).
with an explicit group name where possible. Query sync does not require
a more expensive output group name filtering applied to each artifact.
Separate legacy and query sync use cases and simplify support for the
query sync one.
Bug: 327638725
Test: n/a (existing)
Change-Id: If2b465a63ea3f7c65d425ad7b1ebca645f3e0556
AOSP: c47d961501bca50da2e2c5bfd4129f214cc69a46

[AOSP-pick] Replace output group name filter

---

base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Since the starlark file required by the xcode query is part of the aspects, the aspects also need to be provided at startup to run this query.

Copy aspects also during startup sync

---

base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java

Cherry pick AOSP commit [7f3f6a874e415d342ebd7b81fb01a1e64041d88f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/7f3f6a874e415d342ebd7b81fb01a1e64041d88f).
Bug: 385469770
Bug: 385546508
Test: existing
Change-Id: Id077b2cee98a4186e81e7222ae0ea65d5b310036
AOSP: 7f3f6a874e415d342ebd7b81fb01a1e64041d88f

[AOSP-pick] Handle output groups explicitly in deployment

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt

Fix for no pty output on windows. Also addresses the missing \r after printing the command to the terminal. And some api-comapt clean up.

Fixes for the PTY terminal on Windows

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/command/BlazeCommandRunner.java
base/src/com/google/idea/blaze/base/command/CommandLineBlazeCommandRunner.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java
base/src/com/google/idea/blaze/base/logging/utils/BuildPhaseSyncStats.java
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/qsync/GroupedOutputArtifacts.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncBuildResult.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterface.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginDeployer.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BuildPluginBeforeRunTaskProvider.java

Cherry pick AOSP commit [d6bbbf53d8b1da6b6ad70960d26130a883a3f821](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d6bbbf53d8b1da6b6ad70960d26130a883a3f821).
and begin separating the legacy sync use case, which requires more
computation than the query sync one.
Bug: n/a
Test: n/a
Change-Id: I02a85f235260672fd436ae22b390641e0abbf2ee
AOSP: d6bbbf53d8b1da6b6ad70960d26130a883a3f821

[AOSP-pick] Extract BuildOutputs interface

---

java/src/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlags.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlagsIntegrationTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaAbstractTestCaseConfigurationProducerTest.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaTestMethodConfigurationProducerTest.java
java/tests/unittests/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlagsTest.java

While `$` may be useful in other JUnit versions to determine where a "class boundary" ends, as the plugin is using `,` for enumeration in that case (i.e. `mypackage.myClass1#myMethod1,myMethod2$|...`), it is not needed when the enumeration is between `()` as in JUnit5 (i.e. `mypackage.myClass1#(myMethod1|myMethod2)|...`).
details.
Issue number: https://github.com/bazelbuild/intellij/issues/7061

Stop adding $ as "terminators" when filtering tests for JUnit 5

---

base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java

Cherry pick AOSP commit [22b93c09bf3b9cf161fe86246d7a982f26717ac6](https://cs.android.com/android-studio/platform/tools/adt/idea/+/22b93c09bf3b9cf161fe86246d7a982f26717ac6).
since the former is not needed in the query sync mode.
- Do not flatten the graph while processing events
- Instead collect data in a suitable for further processing form in
an instance of `OutputGroupTargetConfigFileSetMap`.
Bug: 327638725
Test: existing
Change-Id: I41bfb406f2f0432d825f7e41b1bf350f07bb6ed5
AOSP: 22b93c09bf3b9cf161fe86246d7a982f26717ac6

[AOSP-pick] Separate BEP analysis and parsing

---

aswb/tests/unittests/com/google/idea/blaze/android/filecache/LocalArtifactCacheTest.java
aswb/tests/unittests/com/google/idea/blaze/android/libraries/UnpackedAarsTest.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/src/com/google/idea/blaze/base/command/buildresult/LocalFileOutputArtifact.java
base/src/com/google/idea/blaze/base/command/buildresult/LocalFileOutputArtifactWithoutDigest.java
base/src/com/google/idea/blaze/base/command/buildresult/LocalFileParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/OutputArtifactParser.java
base/src/com/google/idea/blaze/base/command/info/BlazeConfigurationHandler.java
base/src/com/google/idea/blaze/base/model/RemoteOutputArtifacts.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/workspace/ArtifactLocationDecoderImpl.java
base/tests/utils/unit/com/google/idea/blaze/base/sync/FakeRemoteOutputArtifact.java
base/tests/utils/unit/com/google/idea/blaze/base/sync/workspace/MockArtifactLocationDecoder.java
shared/java/com/google/idea/blaze/common/artifact/OutputArtifactWithoutDigest.java
shared/javatests/com/google/idea/blaze/common/artifact/TestOutputArtifact.java

Cherry pick AOSP commit [1c670d4ec9fc74ec6afe716cc2d1cc2d8746b4c8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/1c670d4ec9fc74ec6afe716cc2d1cc2d8746b4c8).
Configuration mnemonics are computed as the second entry in the artifact
prefix path and can be computed the same way on demand.
This is to simplify BEP parsing.
Bug: n/a
Test: n/a
Change-Id: Ice44e0cadd93f529275a1b70e019bad6111479f4
AOSP: 1c670d4ec9fc74ec6afe716cc2d1cc2d8746b4c8

[AOSP-pick] Simplify handling of config mnemonics

---

.bazelci/clion.yml

Mark MacOS CI as soft fail, since MacOS runners are broken because of https://github.com/bazelbuild/continuous-integration/issues/2183.
Revert this after the issue is fixed.

Disable CLion MacOS CI

---

base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java

Cherry pick AOSP commit [3f24b2e65d884415dd816743c7fcf0d8e0d81349](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3f24b2e65d884415dd816743c7fcf0d8e0d81349).
in a way that allows it to be re-used in the query sync mode without
the analysis phase.
Bug: 327638725
Test: n/a
Change-Id: I091964beb0af544567e8348e7b95dfb9eb6ffdbb
AOSP: 3f24b2e65d884415dd816743c7fcf0d8e0d81349

[AOSP-pick] Extract core BEP parsing

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoader.java
base/src/com/google/idea/blaze/base/sync/data/BlazeDataStorage.java
querysync/java/com/google/idea/blaze/qsync/deps/ArtifactDirectories.java

Cherry pick AOSP commit [d78a5589d270b4459fadc4e356921bce6a445e97](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d78a5589d270b4459fadc4e356921bce6a445e97).
Bug: 366128721
Test: n/a
Change-Id: I0ff314d4ea419d06cadf329c41e2be810d2d95ef
AOSP: d78a5589d270b4459fadc4e356921bce6a445e97

[AOSP-pick] Enumerate all currently used cache directories.

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/ParsedBepOutput.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [7fbfbd9ad4ed3a2b6b5da32fba25f5c4429a19bc](https://cs.android.com/android-studio/platform/tools/adt/idea/+/7fbfbd9ad4ed3a2b6b5da32fba25f5c4429a19bc).
1. as a pre-requisite also reduce the amount of details logged when
the IDE is unable to find expected output artifacts.
2. drop artifact filtering support as it is rarely used and can filters
can be applied afterwards.
Bug: 327638725
Test: n/a
Change-Id: Ibc4008f6340d7f08c6b220e871e9a3c1c090dd97
AOSP: 7fbfbd9ad4ed3a2b6b5da32fba25f5c4429a19bc

[AOSP-pick] Simplify ParsedBepOutput public interface

---

aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/MobileInstallBuildStep.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeInstrumentationTestApkBuildStep.java
aswb/src/com/google/idea/blaze/android/run/runner/FullApkBuildStep.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeInstrumentationTestApkBuildStepIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/FullApkBuildStepIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/MobileInstallBuildStepIntegrationTest.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/ParsedBepOutput.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [b228d1ef2bdb093b73203176ec8158061042505e](https://cs.android.com/android-studio/platform/tools/adt/idea/+/b228d1ef2bdb093b73203176ec8158061042505e).
1. Builds may get multiple aspects applied resulting in multiple
additional artifacts returned.
2. Make `getOutputGroupTargetArtifacts` return all artifacts declared by
the target as its outputs instead of ambiguously defined direct
artifacts, which in its current implementation is implementation
dependent and returns top level named file sets only. Note, a single
target may itself produce multiple nested file sets without
participation of other targets at all. File sets basically follow the
structure fo depsets. Perhaps the amount of logging in callers
reflects the incorrect behavior.
3. When requesting …

[AOSP-pick] Never ask for artifacts without output group

---

querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/query/QuerySummary.java
querysync/javatests/com/google/idea/blaze/qsync/project/BuildGraphDataTest.java
shared/java/com/google/idea/blaze/common/Label.java
shared/java/com/google/idea/blaze/common/TargetTree.java
shared/javatests/com/google/idea/blaze/common/LabelTest.java

Store the package and name of a Label as strings rather than paths, to avoid occurrence of backslashes on Windows

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoader.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/QuerySyncTest.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/base/ClwbIntegrationTestCase.java
cpp/src/com/google/idea/blaze/cpp/qsync/CcProjectModelUpdateOperation.java
querysync/java/com/google/idea/blaze/qsync/deps/ArtifactDirectories.java
querysync/java/com/google/idea/blaze/qsync/deps/CcToolchain.java
querysync/java/com/google/idea/blaze/qsync/project/ProjectPath.java
querysync/java/com/google/idea/blaze/qsync/project/project.proto
querysync/javatests/com/google/idea/blaze/qsync/cc/CcWorkspaceBuilderTest.java
querysync/javatests/com/google/idea/blaze/qsync/cc/ConfigureCcCompilationTest.java
querysync/javatests/com/google/idea/blaze/qsync/java/AddDependencySrcJarsTest.java

1. Make cc compiler path exec root relative. The path was workspace relative before which is not correct.
2. Also make external include paths exec root relative.
Also added test for external include paths. To run qsync tests on mac we are still missing xcode integration.

CLion qsync improvements for Mac

---

base/src/com/google/idea/blaze/base/sync/data/BlazeDataStorage.java

Build was broken by accident due to conflicting commits. Since the offending function is not used, and also seems not to be used in future by the AOSP, I would suggest to just remove the function.

Fix build errors 

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [1c9f33b7a59023dd8e79a1092cbe23dfd149eedb](https://cs.android.com/android-studio/platform/tools/adt/idea/+/1c9f33b7a59023dd8e79a1092cbe23dfd149eedb).
instead of raw ParsedBepOutputs.  This is a step towards unifying them.
Bug: 327638725
Test: n/a
Change-Id: I23e3d9d0b4637ef8ac65458a4f4916f3e1dbd6a0
AOSP: 1c9f33b7a59023dd8e79a1092cbe23dfd149eedb

[AOSP-pick] Always use BlazeBuildOutputs

---

querysync/java/com/google/idea/blaze/qsync/deps/ArtifactTrackerStateDeserializer.java
querysync/java/com/google/idea/blaze/qsync/deps/ArtifactTrackerStateSerializer.java
querysync/java/com/google/idea/blaze/qsync/deps/DependencyBuildContext.java
querysync/java/com/google/idea/blaze/qsync/deps/NewArtifactTracker.java
querysync/java/com/google/idea/blaze/qsync/deps/artifact_tracker_state.proto

Cherry pick AOSP commit [f27d625a2c9a525fe23994e2b7b08acf0d004ee6](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f27d625a2c9a525fe23994e2b7b08acf0d004ee6).
to avoid misuse.
Bug: n/a
Test: n/a
Change-Id: I9e06e8c8eae748c381f381f111543ee4460dab1d
AOSP: f27d625a2c9a525fe23994e2b7b08acf0d004ee6

[AOSP-pick] Rename build_id to build_id_for_logging

---

clwb/BUILD

To improve CI runtime remove the LLVM tests from the test configuration.

CLion disable llvm tests

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/command/CommandLineBlazeCommandRunner.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelperBep.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderLegacyTest.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BepUtils.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [37e18eda7680a8c01922353f88ebdde516fd76ff](https://cs.android.com/android-studio/platform/tools/adt/idea/+/37e18eda7680a8c01922353f88ebdde516fd76ff).
STAT (diff to AOSP): 157 insertions(+), 41 deletion(-)
Bug: 327638725
Test: BuildEventProtocolOutputReaderTest
Test: BuildEventProtocolOutputReaderLegacyTest
Change-Id: Ia54df932fbf5f6bf090c7810962b0996f335b910
AOSP: 37e18eda7680a8c01922353f88ebdde516fd76ff

[AOSP-pick] Complete separation of legacy BepParser

---

kotlin/src/META-INF/blaze-kotlin.xml

Cherry pick AOSP commit [0b0d5f4723ab9035155be4fbc3e3e9921fccad36](https://cs.android.com/android-studio/platform/tools/adt/idea/+/0b0d5f4723ab9035155be4fbc3e3e9921fccad36).
Bug: 363410313
Test: bazel test //tools/adt/idea/aswb/kotlin:integration_tests \
--jvmopt="-Didea.kotlin.plugin.use.k2=true"
Change-Id: I81ef3129c7195d4795221b7847ae652ae7bcf173
AOSP: 0b0d5f4723ab9035155be4fbc3e3e9921fccad36

[AOSP-pick] Mark ASwB K2 compatible

---

aswb/src/com/google/idea/blaze/android/editor/ProjectUnresolvedResourceStatsCollector.java
aswb/src/com/google/idea/blaze/android/run/BlazeAndroidRunConfigurationCommonState.java
base/BUILD
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectAction.java
base/src/com/google/idea/blaze/base/lang/LegacyAdditionalLanguagesHelper.java
base/src/com/google/idea/blaze/base/model/LegacyLibraryToTargetResolver.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/syncstatus/LegacySyncStatusContributor.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusEditorTabColorProvider.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusEditorTabTitleProvider.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusNodeDecorator.java
base/tests/utils/unit/com/google/idea/blaze/base/model/FakeLibraryToTargetResolver.java
clwb/src/com/google/idea/blaze/clwb/oclang/run/test/GoogleTestLocation.java
cpp/src/com/google/idea/blaze/cpp/oclang/CppSyncStatusContributor.java
golang/src/com/google/idea/blaze/golang/sync/GoSyncStatusContributor.java
java/src/com/google/idea/blaze/java/syncstatus/JavaSyncStatusContributor.java
kotlin/src/com/google/idea/blaze/kotlin/syncstatus/KotlinSyncStatusContributor.java
python/src/com/google/idea/blaze/python/sync/PySyncStatusContributor.java
scala/src/com/google/idea/blaze/scala/sync/ScalaSyncStatusContributor.java

Cherry pick AOSP commit [e604e90c8a4f583184fcf4ade5ad3b69c2e282f9](https://cs.android.com/android-studio/platform/tools/adt/idea/+/e604e90c8a4f583184fcf4ade5ad3b69c2e282f9).
1. There is nothing to do in the query sync mode
2. Rename classes to make sure they are not used in the query sync mode
Bug: 260643753
Test: n/a
Change-Id: I4b4eb7f61169bc8034ac69faeb4771d0cd090b81
AOSP: e604e90c8a4f583184fcf4ade5ad3b69c2e282f9

[AOSP-pick] Remove TODOs and rename classes

---

base/src/com/google/idea/blaze/base/qsync/FileRefresher.java

Cherry pick AOSP commit [cd03c25523b886dc9686cc67199f17ee8270b913](https://cs.android.com/android-studio/platform/tools/adt/idea/+/cd03c25523b886dc9686cc67199f17ee8270b913).
When skipping finding artifact roots on the EDT we still need to
refresh these files.
Rename the experiment so it can be safely re-enabled (already done for
this name).
Bug: n/a
Test: n/a
Change-Id: Icb1043e0fc6181a53f68f0f5284c0e377e989c8d
AOSP: cd03c25523b886dc9686cc67199f17ee8270b913

[AOSP-pick] Fix skip finding output experiment implementation

---

base/src/com/google/idea/blaze/base/qsync/ProjectUpdater.java
base/src/com/google/idea/blaze/base/qsync/ProjectUpdaterHelper.kt
base/src/com/google/idea/blaze/base/qsync/ProjectUpdaterThreadingUtils.kt

details.
Issue number: `https://github.com/bazelbuild/intellij/issues/7149`

Reduce freeze in ProjectUpdater

---

base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectStorageService.kt

Emit a warning during sync if the aspects can be found in the bazel ignore file. The sync will most likely fail if the user has added the aspects to the bazel ignore file.
Issue number: #7302, #7334

Add warning for ignored aspects

---

aspect/build_dependencies.bzl
base/BUILD
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/tests/integrationtests/com/google/idea/blaze/base/qsync/BazelDependencyBuilderTest.java
shared/java/com/google/idea/blaze/common/artifact/BUILD

Cherry pick AOSP commit [2e116b56c18f3c50f832e759537321ed0ba6fb34](https://cs.android.com/android-studio/platform/tools/adt/idea/+/2e116b56c18f3c50f832e759537321ed0ba6fb34).
This is to unify the test and production flows and make manual testing
from the command line tolerable.
It should also make the aspect configuration visible in CitC snapshots
and aspect builds easily reproducible in users' workspaces.
Bug: 327638725
Test: BazelDependencyBuilderTest
Change-Id: I4cf4b408097cecc7d324310d98c18ce36900468e
AOSP: 2e116b56c18f3c50f832e759537321ed0ba6fb34

[AOSP-pick] Parameterize aspect at instantiation

---

aspect/build_dependencies.bzl

Cherry pick AOSP commit [682e0b9658fd12c1c36278216fbd8cba2c7933e2](https://cs.android.com/android-studio/platform/tools/adt/idea/+/682e0b9658fd12c1c36278216fbd8cba2c7933e2).
This, for example, may reduce the size of BEP output from 289Mb to 18Mb.
Bug: 327638725
Test: SyncedInBazelProjectTest + manually
Change-Id: I2575ae61aa77582d7c39e149d8ca6eb0bcfeadb5
AOSP: 682e0b9658fd12c1c36278216fbd8cba2c7933e2

[AOSP-pick] Do not flatten depsets when reporting outputs

---

base/src/com/google/idea/blaze/base/command/BlazeCommandRunnerExperiments.java

Cherry pick AOSP commit [669b5ab0e54ec97a14a8723cdaf50e83cad33fa4](https://cs.android.com/android-studio/platform/tools/adt/idea/+/669b5ab0e54ec97a14a8723cdaf50e83cad33fa4).
The DBiP on-corp is no longer a pilot experiment, and the interested users should follow go/dbip-onboarding instead. Currently, only one ASwB user has this flag set to true, and we can safely delete it.
https://plx.corp.google.com/scripts2/script_f6._44cdd4_098e_4dcb_a994_13dee866f1b2
Bug:378707836
Test: n/a
Change-Id: I1244016a797b3da7bab6004e6dd16c4e25a21fd0
AOSP: 669b5ab0e54ec97a14a8723cdaf50e83cad33fa4

[AOSP-pick] Remove unused DBiP experimental flag

---

aswb/BUILD
testing/test_defs.bzl

Cherry pick AOSP commit [3358a60218376c733b8196f1f001e85ed1405c8b](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3358a60218376c733b8196f1f001e85ed1405c8b).
Bug: 333377957
Test: n/a
Change-Id: I111979e339decaa9d07c08ff049f2fc56804d6e1
AOSP: 3358a60218376c733b8196f1f001e85ed1405c8b

[AOSP-pick] Delete unused additional_class_rules attribute

---

aspect/build_dependencies.bzl
aswb/testdata/projects/test_projects.bzl
querysync/java/com/google/idea/blaze/qsync/deps/OutputGroup.java

Cherry pick AOSP commit [b2ae825899d167f1f08445d4f6ad29b8f3c14cf3](https://cs.android.com/android-studio/platform/tools/adt/idea/+/b2ae825899d167f1f08445d4f6ad29b8f3c14cf3).
and get rid of a nested function because ASwB editor doe snot support
them.
Bug: n/a
Test: SyncedInBazelProjectTest
Change-Id: Ib572b1aec4767a78a64f1027ac7fd04cb7d9fa18
AOSP: b2ae825899d167f1f08445d4f6ad29b8f3c14cf3

[AOSP-pick] Make output group names shorter and consistent

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncManager.java

Cherry pick AOSP commit [5e5d44f03d41187cd05cf8af016da6da0735fda1](https://cs.android.com/android-studio/platform/tools/adt/idea/+/5e5d44f03d41187cd05cf8af016da6da0735fda1).
Thread pools and executors are not different from all other services
that the project loader instantiates.
Bug: n/a
Test: n/a
Change-Id: I75026cdae75c1e4bafc39a116fa1f39fd03ea6ad
AOSP: 5e5d44f03d41187cd05cf8af016da6da0735fda1

[AOSP-pick] Make thread pools a concern of ProjectLoader

---

testing/test_deps/projects/java_and_deps/.bazelproject
testing/test_deps/projects/java_and_deps/BUILD
testing/test_deps/projects/java_and_deps/deps/top_level_lib_1/BUILD
testing/test_deps/projects/java_and_deps/deps/top_level_lib_1/java/com/example/top_level_lib_1/Lib1.java
testing/test_deps/projects/java_and_deps/deps/top_level_lib_2/BUILD
testing/test_deps/projects/java_and_deps/deps/top_level_lib_2/java/com/example/top_level_lib_2/Lib2.java
testing/test_deps/projects/java_and_deps/deps/transitive_dep_lib/BUILD
testing/test_deps/projects/java_and_deps/deps/transitive_dep_lib/java/com/example/transitive_dep_lib/DepLib.java
testing/test_deps/projects/java_and_deps/project/BUILD
testing/test_deps/projects/java_and_deps/project/java/com/example/lib/LibClass.java
testing/test_deps/projects/java_and_deps/project/java/com/example/sample/Class1.java
testing/test_deps/projects/java_and_deps/project/java/com/example/sample/nested/BUILD
testing/test_deps/projects/java_and_deps/project/java/com/example/sample/nested/NestedClass.java
testing/test_deps/projects/java_and_deps/project/java/com/example/sample/nested/NestedClass2.java

Cherry pick AOSP commit [f7fc4849a82b66eeb3c07b73c537c57f19778ee4](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f7fc4849a82b66eeb3c07b73c537c57f19778ee4).
that should enable tests that inspect details of external dependency
reporting since its targets do not depend on external dependencies.
Bug: 327638725
Test: n/a
Change-Id: Iaadc9d4dd2a33d84d0be1872d53b6cfe00d0e8e6
AOSP: f7fc4849a82b66eeb3c07b73c537c57f19778ee4

[AOSP-pick] Add java_and_deps test project

---

aswb/testdata/projects/android1/external/BUILD
aswb/testdata/projects/android1/project/BUILD

Cherry pick AOSP commit [eaa36d02bb623ebe7f1cdda68488bf1b95d0a144](https://cs.android.com/android-studio/platform/tools/adt/idea/+/eaa36d02bb623ebe7f1cdda68488bf1b95d0a144).
to keep targets compiling when `java_language_version` would be swithed
to 21 in `studio-main`
Bug: 390012852
Test: this is a test
Change-Id: I3b4875578177754aceb84e86a01435c3629c6d5a
AOSP: eaa36d02bb623ebe7f1cdda68488bf1b95d0a144

[AOSP-pick] Pin aswb test targets to java 17

---

base/BUILD
base/src/com/google/idea/blaze/base/qsync/cache/ArtifactFetchers.java
base/src/com/google/idea/blaze/base/qsync/cache/FileApiArtifactFetcher.java

Cherry pick AOSP commit [9bec8358b15d0579e6ae214588d6a5f2a27f5651](https://cs.android.com/android-studio/platform/tools/adt/idea/+/9bec8358b15d0579e6ae214588d6a5f2a27f5651).
via `aswb.file.api.artifact.fetcher.max.threads` experiment with the
default value of 128.
Bug: 327638725
Test: n/a
Change-Id: I788a1ac8165cc419dfd461e6ddeb32ca783e9376
AOSP: 9bec8358b15d0579e6ae214588d6a5f2a27f5651

[AOSP-pick] Make FileApiArtifactFetcher thread pool configurable

---

.bazelci/clion.yml

Since https://github.com/bazelbuild/continuous-integration/issues/2183 has been addressed we can hopefully enable the mac CI again.

Revert "Disable CLion MacOS CI (#7359)"

---

aspect/build_dependencies.bzl
aswb/testdata/projects/test_projects.bzl
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/tests/integrationtests/com/google/idea/blaze/base/qsync/BazelDependencyBuilderTest.java

Cherry pick AOSP commit [fb1c97bd657f78bd71d5f234363f986e0fdba369](https://cs.android.com/android-studio/platform/tools/adt/idea/+/fb1c97bd657f78bd71d5f234363f986e0fdba369).
STAT (diff to AOSP): 2 insertions(+), 2 deletion(-)
1. Make _write_java_target_info usable in other contexts
2. Make package_depedencies aspect depend on the config
Bug: 327638725
Test: SyncedInBazelProjectTest
Change-Id: I5b095323ece99e11636c74cc84c807b06fa92b80
AOSP: fb1c97bd657f78bd71d5f234363f986e0fdba369

[AOSP-pick] Prepare for multi-info-file experiment

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
querysync/java/com/google/idea/blaze/qsync/deps/OutputInfo.java

Cherry pick AOSP commit [634ac56970c0b24819e52c2d583baecab5e421e9](https://cs.android.com/android-studio/platform/tools/adt/idea/+/634ac56970c0b24819e52c2d583baecab5e421e9).
Artifacts from these groups describe the input to the artifact tracker
and are already processed at this point. While there is no harm in
processing them twice they result in misleading messages to the build
output about the number of artifacts requested and actually fetched.
Bug: n/a
Test: n/a
Change-Id: I0ea69b11e5aba00f38fee80f57afe8009c9d86c0
AOSP: 634ac56970c0b24819e52c2d583baecab5e421e9

[AOSP-pick] qs_info groups are not concern of ArtifactTracker

---

common/experiments/src/com/google/idea/common/experiments/EnumExperiment.java
common/experiments/src/com/google/idea/common/experiments/StringExperiment.java
common/experiments/tests/unittests/com/google/idea/common/experiments/ExperimentServiceImplTest.java

Cherry pick AOSP commit [9d258111d252d18b41a12460faa99e608755c578](https://cs.android.com/android-studio/platform/tools/adt/idea/+/9d258111d252d18b41a12460faa99e608755c578).
Bug: n/a
Test: ExperimentServiceImplTest
Change-Id: I99e6541b3b77562dcc5bc4a67a34e37ca226dcc4
AOSP: 9d258111d252d18b41a12460faa99e608755c578

[AOSP-pick] Support enum experiments and string defaults

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java

Cherry pick AOSP commit [b563d739d6255c02200d1b468143af908eb03699](https://cs.android.com/android-studio/platform/tools/adt/idea/+/b563d739d6255c02200d1b468143af908eb03699).
STAT (diff to AOSP): 4 insertions(+), 4 deletion(-)
(pure refactoring)
Bug: n/a
Test: n/a
Change-Id: I106bc0656dd322f460a32c5d95ba99d9e4926180
AOSP: b563d739d6255c02200d1b468143af908eb03699

[AOSP-pick] Prepare BazelDependencyBuilder for upcoming change

---

aspect/BUILD
aspect/intellij_info.bzl
aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BUILD
base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectTemplateWriter.java

Followup: Use toolchains_aspects to propagate aspects to toolchains

---

base/BUILD
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/tests/integrationtests/com/google/idea/blaze/base/qsync/BazelDependencyBuilderTest.java

Cherry pick AOSP commit [cec59f254d4c35f0999d20d0d1fa8d74b55adadf](https://cs.android.com/android-studio/platform/tools/adt/idea/+/cec59f254d4c35f0999d20d0d1fa8d74b55adadf).
Bug: 327638725
Test: BazelDependencyBuilderTest
Change-Id: Ie0772a45ca86d20e65bee98b49b799b071b266c3
AOSP: cec59f254d4c35f0999d20d0d1fa8d74b55adadf

[AOSP-pick] Add experimental support for target pattern file

---

testing/test_deps/projects/java_and_deps/deps/no_ide/BUILD
testing/test_deps/projects/java_and_deps/deps/no_ide/java/com/example/no_ide/NoIdeLib.java
testing/test_deps/projects/java_and_deps/project/BUILD

Cherry pick AOSP commit [c20387d230b1b65127e4baa7c5145c220151dfb6](https://cs.android.com/android-studio/platform/tools/adt/idea/+/c20387d230b1b65127e4baa7c5145c220151dfb6).
Add test `no-ide` targets that result in target selection ambiguity,
which results in a test failure unless specifically handled in the test.
Disable `SyncedInBazelProjectTest.javaAndDeps` as it now catches the
issue.
Bug: 391112715
Test: n/a
Change-Id: I788f061b31d58bf7b958fcc0e15dc8daeb476f02
AOSP: c20387d230b1b65127e4baa7c5145c220151dfb6

[AOSP-pick] Reproduce no-ide test ignored in tests

---

querysync/java/com/google/idea/blaze/qsync/query/QuerySpec.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySpecTest.java

Cherry pick AOSP commit [a4267596e72fdfc3b22d6bbdc93ca15b181ac80a](https://cs.android.com/android-studio/platform/tools/adt/idea/+/a4267596e72fdfc3b22d6bbdc93ca15b181ac80a).
1. Filter out `no-ide` targets in the query phase.
2. Re-enable `SyncedInBazelProjectTest.javaAndDeps` test, which proves
that `no-ide` is targets are not in the query results.
Bug: n/a
Test: SyncedInBazelProjectTest.javaAndDeps
Change-Id: I7a0405a70415cb1e24ebe96b84e36643958fe14a
AOSP: a4267596e72fdfc3b22d6bbdc93ca15b181ac80a

[AOSP-pick] Exclude no-ide targets from query results

---

MODULE.bazel

Bazel 7.4.1 -> 7.5.0
Bazel 8.0.1 -> 8.1.1

Bump bazel version for headless tests 

---

MODULE.bazel
aspect/BUILD
aspect/testing/rules/intellij_aspect_test_fixture.bzl
aswb/testdata/projects/src_transform/BUILD
intellij_platform_sdk/build_defs.bzl

details.
Issue number: #7436 
This is an attempt to make our build easier to set up on Windows. Genrules depend on Bash, and Bash on Windows has some quirks.

Remove genrules where possible

---

aspect/build_dependencies.bzl
testing/test_deps/projects/java_and_deps/deps/no_ide/BUILD
testing/test_deps/projects/java_and_deps/project/BUILD
testing/test_deps/projects/java_and_deps/project/java/com/example/dep_on_no_ide/DepOnNoIde.java

Cherry pick AOSP commit [9e3e119028b077018793189e2fb52fc91732c31f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/9e3e119028b077018793189e2fb52fc91732c31f).
even if other targets depend on them. `no-ide` targets are marked as
such for a purpose. Usually their output is available by other means.
Do not even output warnings as it produces enough noise by not usable.
Bug: 391112715
Test: SyncedInBazelProjectTest.javaAndDeps
Change-Id: I3b4265cd9a400c1a16d7ba18f141122fb77e29d3
AOSP: 9e3e119028b077018793189e2fb52fc91732c31f

[AOSP-pick] Skip no-ide targets in the aspect

---

base/BUILD
base/src/com/google/idea/blaze/base/util/VersionChecker.java
base/tests/unittests/com/google/idea/blaze/base/util/VersionCheckerTest.java

Cherry pick AOSP commit [66cf6b4272639534964cd7cfd2056257c2fd8def](https://cs.android.com/android-studio/platform/tools/adt/idea/+/66cf6b4272639534964cd7cfd2056257c2fd8def).
It's used to detect if IDE get upgrade without a restart.Move it from g3plugin/ to a more common place for future usage.
Bug: b/391401923
Change-Id: Ic8ac58ca3df1aa7f00eb52a309ddb7e73a8e4191
AOSP: 66cf6b4272639534964cd7cfd2056257c2fd8def

[AOSP-pick] Provide a helper function to check IDE version mismatch

---

aswb/src/com/google/idea/blaze/android/resources/BlazeRClass.java

Cherry pick AOSP commit [0f4a002ba09dac1484490a98dd04dcea7776d0df](https://cs.android.com/android-studio/platform/tools/adt/idea/+/0f4a002ba09dac1484490a98dd04dcea7776d0df).
All AndroidLightClassBase implementations need to specify a containing
file, and they all do it in mostly-similar-but-not-quite-identical ways.
This change consolidates the logic in the super class, requiring the
data to be passed in the constructor.
Nothing should change with this commit; existing behavior for the
containing classes has been maintained. (In upcoming changes, I'll try
to reduce some of the differences; eg, making sure all in-memory Java
files have a package name set.)
Bug: n/a
Test: Covered by existing
Change-Id: …

[AOSP-pick] Consolidate containingFile in light class base

---

aspect/build_dependencies.bzl

Cherry pick AOSP commit [438ec2e7e532ddb92f948fc8176039077ddd2075](https://cs.android.com/android-studio/platform/tools/adt/idea/+/438ec2e7e532ddb92f948fc8176039077ddd2075).
We want to copybara this aspect from here to Google3. Google3 is
more strict and will complain about unused variables, undocumented
arguments and return values and uninitialized variables. This change
should make no semantic difference in this aspect code.
Bug: N/A
Test: N/A
Change-Id: I6f35ba50adc2f7c163fcb9a0e8910c4e52d7ecd7
AOSP: 438ec2e7e532ddb92f948fc8176039077ddd2075

[AOSP-pick] Changes required for Google3 Buildifier not to complain

---

aswb/src/com/google/idea/blaze/android/resources/BlazeRClass.java

Cherry pick AOSP commit [5e907fbd0f6a77a1f8afcc8bcf399bb9e3e78a0a](https://cs.android.com/android-studio/platform/tools/adt/idea/+/5e907fbd0f6a77a1f8afcc8bcf399bb9e3e78a0a).
The existing pattern is that derived classes are supposed to call
`setModuleInfo` during their initialization. Most do, but some have
missed it, and this results in the Kotlin plugin not being able to
appropriately identify the classes.
I'm changing the code pattern to require `ModuleInfo` to be passed in
via the constructor. The parameter is currently nullable in the super AndroidLightClassBase for the cases that don't have module information yet, so this change shouldn't affect any behavior. I'll follow up with another change to actually set the module information.
Bug: n/a
Test: covered by existing
Change-Id: …

[AOSP-pick] Set moduleInfo on light class construction

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystemBase.java
aswb/tests/unittests/com/google/idea/blaze/android/projectsystem/BazelModuleSystemTest.java

Cherry pick AOSP commit [397705719a4a75d6988862d409a4fdd5b1830d26](https://cs.android.com/android-studio/platform/tools/adt/idea/+/397705719a4a75d6988862d409a4fdd5b1830d26).
The one remaining production user of it is trivially convertible to
the two-argument form.
Bug: 279886738
Test: existing tests adjusted
Change-Id: I8e2bb60a8a618d7d471616ee941e1dfc1f740fc5
AOSP: 397705719a4a75d6988862d409a4fdd5b1830d26

[AOSP-pick] Remove one-argument form of registerDependency

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/util/VersionChecker.java

Cherry pick AOSP commit [ac3b81d24ca9cfb1e02e2c5234b230319fcd4cfd](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ac3b81d24ca9cfb1e02e2c5234b230319fcd4cfd).
when building dependencies to prevent cryptic error messages when aspect
files get overwritten by the installer while the IDE is running.
Bug: 391401923
Test: n/a
Change-Id: I3d0db5486371d6b0f261df27f02a3b450f2b75d3
AOSP: ac3b81d24ca9cfb1e02e2c5234b230319fcd4cfd

[AOSP-pick] Simplest possible version check

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/project/BlazeProjectOpenProcessor.java

In order to not automatically import every project as a Bazel project even if there are other project models available, the ProjectOpenProcessors cannot be strong info holders by default. 
The old behavior can be restored by setting the `bazel.project.auto.open` registry key to true.
Removes the following obsolete registry keys: 
- `bazel.project.prefer.google.plugin`
- `bazel.project.auto.open.if.present`

Make ProjectOpenProcessors no strong info holder by default

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/project/BlazeProjectOpenProcessor.java

Reverts bazelbuild/intellij#7440
Will reimplement this in 2 weeks.

Revert "Make ProjectOpenProcessors no strong info holder by default"

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystemBase.java

Cherry pick AOSP commit [d33b1db1cb84f9320718a889d346497db79362c8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d33b1db1cb84f9320718a889d346497db79362c8).
The check, for whether PNG generation is supported, and subsequent
check against the minSdk version, is substantially incomplete, eliding
as it does any mention of the support library's varying compatibility
support for vector drawables.
Given this, the check is of limited utility, and (worse) actively
prevents the user from doing what they need to in cases where their
action is completely valid.  Remove the check, which also makes the
question of whether the build system automatically generates PNGs for
vector drawables irrelevant.
Bug: none filed
Test: existing
Change-Id: I11a3df3b57df714f5f4e71ced88bae9a9ad7e0d2 …

[AOSP-pick] Remove build system check in NewVectorAssetAction

---

aspect/build_dependencies.bzl

Cherry pick AOSP commit [0320054c41615d65f59ce6bf724749178c9d831c](https://cs.android.com/android-studio/platform/tools/adt/idea/+/0320054c41615d65f59ce6bf724749178c9d831c).
Bug: n/a
Test: n/a (not trivial right now)
Change-Id: Ifa3f1e82579293bbc8afdc6505e8d76aaaadb659
AOSP: 0320054c41615d65f59ce6bf724749178c9d831c

[AOSP-pick] Fix incorrect application of `if` in cc_info handling

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java

Cherry pick AOSP commit [0e3f55d9877643728fef79d577442a7cbac1f0e8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/0e3f55d9877643728fef79d577442a7cbac1f0e8).
as it is not a project package.
Bug: 393157715
Test: n/a
Change-Id: I43ebec1ffa2aea943712a33172e53db52814dc3c
AOSP: 0e3f55d9877643728fef79d577442a7cbac1f0e8

[AOSP-pick] Automatically exclude `.aswb` from analysis

---

base/src/com/google/idea/blaze/base/qsync/artifacts/ProjectArtifactStore.java
querysync/java/com/google/idea/blaze/qsync/artifacts/ArtifactDirectoryUpdate.java
querysync/javatests/com/google/idea/blaze/qsync/artifacts/ArtifactDirectoryUpdateTest.java

Cherry pick AOSP commit [847140d5d2a566d0661e1a025812a913dd5c6b0f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/847140d5d2a566d0661e1a025812a913dd5c6b0f).
The value of an experiment should not change while updating artifacts.
Bug: n/a
Test: n/a
Change-Id: Ia1879d8bb880b0e520806447674903b9186319cf
AOSP: 847140d5d2a566d0661e1a025812a913dd5c6b0f

[AOSP-pick] Inline not needed callback

---

java/src/com/google/idea/blaze/java/qsync/ClassFileJavaSourceFinder.java
java/tests/integrationtests/com/google/idea/blaze/java/qsync/ClassFileJavaSourceFinderTest.java
querysync/java/com/google/idea/blaze/qsync/QuerySyncProjectSnapshot.java
querysync/java/com/google/idea/blaze/qsync/deps/ArtifactIndex.java
testing/test_deps/projects/java_and_deps/deps/top_level_lib_1/BUILD
testing/test_deps/projects/java_and_deps/project/BUILD

Cherry pick AOSP commit [8008feb3219353f1465abd868635689e3f6ead4f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/8008feb3219353f1465abd868635689e3f6ead4f).
when multiple targets report the same `compile_jar`` file.
Bug: 392565740
Test: ClassFileJavaSourceFinderTest
Change-Id: I5ba884a9a3360ea93a304f03004908679cd406f7
AOSP: 8008feb3219353f1465abd868635689e3f6ead4f

[AOSP-pick] Fix navigation to sources

---

aswb/src/com/google/idea/blaze/android/projectsystem/BazelProjectSystem.java

Cherry pick AOSP commit [900ecd1be2a015e7f9cd245e702d9a5949143700](https://cs.android.com/android-studio/platform/tools/adt/idea/+/900ecd1be2a015e7f9cd245e702d9a5949143700).
It is no longer used, and not really a project-system concept in any
case.
Bug: none filed
Test: existing
Change-Id: Ife023ce2a13bf9e5b61d766ab1b70c72edd58311
AOSP: 900ecd1be2a015e7f9cd245e702d9a5949143700

[AOSP-pick] Remove getPathToAapt from the Android Project System

---

aswb/src/com/google/idea/blaze/android/libraries/AndroidLintCollector.java

Cherry pick AOSP commit [96ae94e415aeb86b8f215d1bb7f1494c1035eb5c](https://cs.android.com/android-studio/platform/tools/adt/idea/+/96ae94e415aeb86b8f215d1bb7f1494c1035eb5c).
This experiment has been set since July 2022. This enables removing
of the experiment from g3-experiment.properties.
Bug: 391569121
Test: Manually build and run ASwB with this change
Change-Id: I0e88f15f0906fd78c39379571a74bca9e4ec1d2a
AOSP: 96ae94e415aeb86b8f215d1bb7f1494c1035eb5c

[AOSP-pick] Change code to always enable lint

---

aswb/src/com/google/idea/blaze/android/run/RuntimeArtifactCache.java
aswb/src/com/google/idea/blaze/android/run/RuntimeArtifactCacheImpl.java

Cherry pick AOSP commit [ec78bb0190607dace16c9e986513291956a9b7a8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ec78bb0190607dace16c9e986513291956a9b7a8).
Move RuntimeArtifactCache to tools/adt/idea as its independent of
google3 and is used to store Blaze and Bazel artifacts.
Bug: 385469770
Test: Existing test
Change-Id: I383da01ccc00c705499653cf10f558125883c550
AOSP: ec78bb0190607dace16c9e986513291956a9b7a8

[AOSP-pick] Move RuntimeArtifactCache to tools/adt/idea

---

base/src/com/google/idea/blaze/base/bazel/AbstractBuildInvoker.java
base/src/com/google/idea/blaze/base/bazel/AbstractBuildInvoker1.java
base/src/com/google/idea/blaze/base/bazel/BazelBuildSystem.java
base/src/com/google/idea/blaze/base/bazel/BuildSystem.java
base/src/com/google/idea/blaze/base/bazel/LocalInvoker.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BuildSystemProviderWrapper.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildInvoker.java

Cherry pick AOSP commit [f4b863f5a6e1b50b3e505cc7d52c521b16a34dec](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f4b863f5a6e1b50b3e505cc7d52c521b16a34dec).
The Blaze and Bazel invokers are pretty much the same, except the binary type and the binary path. Merge them into a single `LocalInvoker` to avoid duplicate code as part of the cleanup.
Prior to cleanup, they were two different classes, but shared the same command runner and the build result helper.
Bug:374906681
Test: n/a
Change-Id: I7a9a570c48191ba6b05e1b5d227fc8a97ebe9398
AOSP: f4b863f5a6e1b50b3e505cc7d52c521b16a34dec

[AOSP-pick] Merge Local Blaze and Bazel Invokers

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java
base/src/com/google/idea/blaze/base/qsync/action/ResetQuerySyncAction.java
querysync/java/com/google/idea/blaze/qsync/QuerySyncProjectSnapshot.java

Cherry pick AOSP commit [71e593cbc07a254b24f4815d9ae02d51f9c9b7e4](https://cs.android.com/android-studio/platform/tools/adt/idea/+/71e593cbc07a254b24f4815d9ae02d51f9c9b7e4).
Bug: 305956977
Test: n/a (manually only since only integration testing makes sense here)
Change-Id: I6c33643898798e403748849a915278f50c2e9496
AOSP: 71e593cbc07a254b24f4815d9ae02d51f9c9b7e4

[AOSP-pick] Query sync cache invalidator

---

aspect/build_dependencies.bzl
aspect/build_dependencies_deps.bzl

Cherry pick AOSP commit [84ce11ea8a16541ab619dfc34dc3114c1abf04d8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/84ce11ea8a16541ab619dfc34dc3114c1abf04d8).
1. Do not stop following java dependencies at proto-toolchain targets.
They do not get JavaInfo providers and need to be handled separately.
2. Prepare the aspect to propagate to proto toolchains instead of
propagating over hidden _toolchain like attributes.
Bug: n/a
Test: n/a (existing)
Change-Id: I95b37e043fcd24cacf60e7cc26a174c23dcb9360
AOSP: 84ce11ea8a16541ab619dfc34dc3114c1abf04d8

[AOSP-pick] ASwB can always follow required proto dependencies

---

aswb/src/com/google/idea/blaze/android/projectsystem/BazelProjectSystem.java

Cherry pick AOSP commit [5c3323ea1aec4860eda8563af1965d8e1df85c74](https://cs.android.com/android-studio/platform/tools/adt/idea/+/5c3323ea1aec4860eda8563af1965d8e1df85c74).
The deleted 'getDefaultApkFile' method from the project system implied
something much more generic than this actually is. Pull out the logic
into a separate token to make it specific to the APK analyzer, and move
the integration tests to be next to the new token.
Bug: 391620143
Bug: 191146142
Test: Moved integration tests.
Change-Id: I4de9fb6c9f0153cdc939de29d5752c90b0428cd7
AOSP: 5c3323ea1aec4860eda8563af1965d8e1df85c74

[AOSP-pick] Token for APK analyzer default APK

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/qsync/CacheCleaner.java
base/src/com/google/idea/blaze/base/qsync/DynamicallyDispatchingArtifactFetcher.java
base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncManager.java
querysync/java/com/google/idea/blaze/qsync/deps/BUILD
shared/java/com/google/idea/blaze/common/artifact/BUILD
shared/java/com/google/idea/blaze/common/artifact/BuildArtifactCacheDirectory.java

Cherry pick AOSP commit [dcad2a45d63a39ae85d52aaf7d3c8a4ac3af91af](https://cs.android.com/android-studio/platform/tools/adt/idea/+/dcad2a45d63a39ae85d52aaf7d3c8a4ac3af91af).
Make BuildArtifactCache an independent IntelliJ project service, so that
it may be invoked in both LegacySync and QuerySync projects.
Bug: 385469770
Bug: 392903689
Bug: 392903190
Test: Existing tests are deleted as am not sure how to test project
service
Change-Id: Id1605d87e596aaac84c9a7d77f5d0bd884761213
AOSP: dcad2a45d63a39ae85d52aaf7d3c8a4ac3af91af

[AOSP-pick] Make BuildArtifactCache an independent service

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/tests/unittests/com/google/idea/blaze/base/run/testlogs/LocalBuildEventProtocolTestFinderStrategyTest.java

Cherry pick AOSP commit [b5e9e7e11e5cc65423cef425c863fdf4afebe5d8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/b5e9e7e11e5cc65423cef425c863fdf4afebe5d8).
- ag/31040465 calculated configMnemonic in runtime using the artifact
prefix path, so it is no longer required to capture it from the BEP
event.
- It is also no longer required to parse local test files that do not
have a mnemonic in BEP event as SourceArtifact, because the
configMnemonic calculated in runtime by ag/31040465 in LocalFileParser.
Bug: 385469770
Change-Id: I8f2c8aea91b204d1e5a11ce5e7cc3ed278c4ffc6
AOSP: b5e9e7e11e5cc65423cef425c863fdf4afebe5d8

[AOSP-pick] Remove fetching configMnemonic from BEP event as its calculated from artifact prefix path

---

base/src/com/google/idea/blaze/base/command/buildresult/LocalFileArtifact.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderLegacyTest.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
java/src/com/google/idea/blaze/java/sync/jdeps/JdepsFileReader.java
java/src/com/google/idea/blaze/java/sync/source/PackageManifestReader.java

Cherry pick AOSP commit [ed8535e5178e2f3f0459e7c01de1902fb319d4c5](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ed8535e5178e2f3f0459e7c01de1902fb319d4c5).
- Add a method getLocalFilesForLegacySync to support processing
BlazeArtifact artifact types.
- Update existing getLocalFiles method to fetch local files for OutputArtifact type artifacts.
- This will help migrate LocalFileArtifact#getLocalFiles to using RuntimeArtifactCache, which
only supports OutputArtifact (as it expects artifacts to contain a
digest).
- Invokers of the method has been updated based on whether the flow is
used in LegacySync or QuerySync (Native debugging).
Bug: 385469770
Test: Existing tests for testing old and new methods as their
implementation …

[AOSP-pick] Add/Update getLocalFiles method to support both BlazeArtifact and OutputArtifact type artifacts

---

aswb/src/com/google/idea/blaze/android/projectsystem/BazelAddDestinationMenuToken.java
aswb/src/com/google/idea/blaze/android/projectsystem/BazelNavDesignSurfaceToken.java

Cherry pick AOSP commit [7810090c74d7072a8bcc94f4d97c3a34a7a5f617](https://cs.android.com/android-studio/platform/tools/adt/idea/+/7810090c74d7072a8bcc94f4d97c3a34a7a5f617).
Do not claim to work with arbitrary GradleCoordinates any more:
instead, restrict our domain to the set of artifacts encoded in
GoogleMavenArtifactId (and, specifically, do not allow requesting
specific versions from client code).
This is not a complete solution to the problem that the
DependencyManagement offers interfaces to functionality that it cannot
in general provide, but it's a start, and in particular it removes a
counterintuitive use of GradleCoordinate in the Blaze project system.
Bug: 279149611
Bug: 279886738
Test: existing test adjusted
Change-Id: …

[AOSP-pick] Somewhat de-generalize core DependencyManagement

---

querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java

Cherry pick AOSP commit [af5cecdf4d937b6e86bdb41bee2b9ecf255369e7](https://cs.android.com/android-studio/platform/tools/adt/idea/+/af5cecdf4d937b6e86bdb41bee2b9ecf255369e7).
reasonably fast.
Bug: n/a
Test: existing BuildGraphDataTest
Change-Id: Idf89eddb979528342a776944504ac53fd2aa7b89
AOSP: af5cecdf4d937b6e86bdb41bee2b9ecf255369e7

[AOSP-pick] Make external dependencies computation

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoader.java
base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncManager.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java

Cherry pick AOSP commit [6c758baed9cc3d2ed6da03e65a6066db52caadc8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/6c758baed9cc3d2ed6da03e65a6066db52caadc8).
STAT (diff to AOSP): 9 insertions(+), 2 deletion(-)
projects. The ways the project definition is constructed to load a
project and to determine whether it needs to be re-loaded have diverged
and now full query is used with each incremental sync.
Bug: 396605403
Test: n/a (upcoming; requires changes to blaze contexts)
Change-Id: I686d20113979efce7229f2cf6657e3eac559ab24
AOSP: 6c758baed9cc3d2ed6da03e65a6066db52caadc8

[AOSP-pick] Use the same project definition to load and reload

---

testing/test_deps/deps.bzl

Cherry pick AOSP commit [c4f7e8595e1b26dbbaef65337dc9e7575a257e4f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/c4f7e8595e1b26dbbaef65337dc9e7575a257e4f).
when building aswb_test_deps repository.
These directories are ignored by Git but are still visible to Bazel and
it becomes very time consuming to run tests locally.
Bug: n/a
Test: n/a
Change-Id: If0dd23ac88cf5e81cb5fba8020782fb56cbe1203
AOSP: c4f7e8595e1b26dbbaef65337dc9e7575a257e4f

[AOSP-pick] Ignore bazel-* directories

---

querysync/java/com/google/idea/blaze/qsync/artifacts/ArtifactDirectoryUpdate.java
querysync/java/com/google/idea/blaze/qsync/query/PackageSet.java
querysync/javatests/com/google/idea/blaze/qsync/artifacts/ArtifactDirectoryUpdateTest.java

Cherry pick AOSP commit [de82699cd31cc6d88b0049ac6fc135d2ee0c468e](https://cs.android.com/android-studio/platform/tools/adt/idea/+/de82699cd31cc6d88b0049ac6fc135d2ee0c468e).
with a reasonably fast implementation.
Bug: 370331576
Test: ArtifactDirectoryUpdateTest
Change-Id: Ie92745b1a6d8a563f079c62a83cd789c633e09ae
AOSP: de82699cd31cc6d88b0049ac6fc135d2ee0c468e

[AOSP-pick] Replace deleteUnnecessaryFiles

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/src/com/google/idea/blaze/base/run/testlogs/BlazeTestResult.java
java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildRunProfileState.java
java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestResultFinderStrategy.java

Cherry pick AOSP commit [682108b547ddae3227f3de260d237cefcef2bfe6](https://cs.android.com/android-studio/platform/tools/adt/idea/+/682108b547ddae3227f3de260d237cefcef2bfe6).
STAT (diff to AOSP): 0 insertions(+), 11 deletion(-)
Store output xml files as OutputArtifact instead of BlazeArtifact in
BlazeTestResult object as this allows those files to be stored in
RuntimeArtifactCache in later CLs, as RuntimeArtifactCache only stores
OutputArtifact type artifacts.
Bug: 385469770
Change-Id: I6f889eeec2f09c96b58229ce1528ca5ec9d4ac91
AOSP: 682108b547ddae3227f3de260d237cefcef2bfe6

[AOSP-pick] Store output xml files as OutputArtifact instead of BlazeArtifact in BlazeTestResult

---

base/BUILD
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/run/RuntimeArtifactCache.java
base/src/com/google/idea/blaze/base/run/RuntimeArtifactCacheImpl.java
base/tests/integrationtests/com/google/idea/blaze/base/artifact/TestOutputArtifact.java
base/tests/integrationtests/com/google/idea/blaze/base/run/RuntimeArtifactCacheImplTest.java

Cherry pick AOSP commit [912ea2cbac24299ee601832d2c78eb8e99a171e7](https://cs.android.com/android-studio/platform/tools/adt/idea/+/912ea2cbac24299ee601832d2c78eb8e99a171e7).
Move RuntimeArtifactCache to base folder to so it maybe used by
LocalFileArtifact. Also add TestOutputArtifact to base folder to use in
tests.
Bug: 385469770
Test: Existing test
Change-Id: I71edc228a951a7d7b20e9f3293089bbdd4719cb3
AOSP: 912ea2cbac24299ee601832d2c78eb8e99a171e7

[AOSP-pick] Move RuntimeArtifactCache to base folder

---

base/src/com/google/idea/blaze/base/qsync/DependencyTrackerImpl.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java

Cherry pick AOSP commit [c573902363b91b2413036746f2cf66845bd16cb4](https://cs.android.com/android-studio/platform/tools/adt/idea/+/c573902363b91b2413036746f2cf66845bd16cb4).
regardless of how the targets to build were collected, i.e. build
whole project as if all its targets were selected manually.
Note that this change removes special handling of aliases as they have
not been handled in the non-whole-project case. This may result in code
analysis not being enabled in some targets even after enabling analysis
in the whole project. This will be fixed for all builds by transitioning
to a simplified project graph that only tracks targets of known kinds.
Bug: n/a
Test: existing
Change-Id: Ifae478999feb2b7ea4f98b3a38818cef102891e1
AOSP: …

[AOSP-pick] Build dependencies in the same way

---

base/src/com/google/idea/blaze/base/bazel/BazelBuildSystem.java
base/src/com/google/idea/blaze/base/bazel/BuildSystem.java
base/src/com/google/idea/blaze/base/qsync/BazelQueryRunner.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BuildSystemProviderWrapper.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildSystem.java

Cherry pick AOSP commit [1c23b04cd4ed55ff931add5a73a8dfbb0f82a058](https://cs.android.com/android-studio/platform/tools/adt/idea/+/1c23b04cd4ed55ff931add5a73a8dfbb0f82a058).
STAT (diff to AOSP): 1 insertions(+), 1 deletion(-)
Removes the getParallelBuildInvoker method from the BuildSystem interface for simplification.
Bug:374906681
Test: n/a
Change-Id: I518da730cca67f23cb23d970d079f35e296cf3f9
AOSP: 1c23b04cd4ed55ff931add5a73a8dfbb0f82a058

[AOSP-pick] Remove getParallelBuildInvoker method

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/project/BlazeProjectOpenProcessor.java
ijwb/src/META-INF/ijwb.xml

Follow up for #7440.
In order to not automatically import every project as a Bazel project even if there are other project models available, the ProjectOpenProcessors cannot be strong info holders by default.
The old behavior can be restored in clwb by setting the bazel.project.auto.open registry key to true and is kept for ijwb.

 Make ProjectOpenProcessors no strong info holder by default in CLion

---

aswb/src/com/google/idea/blaze/android/run/NativeSymbolFinder.java
aswb/src/com/google/idea/blaze/android/run/runner/FullApkBuildStep.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/FullApkBuildStepIntegrationTest.java
base/src/com/google/idea/blaze/base/command/buildresult/LocalFileArtifact.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [06ee9d025d81da3104feb7efc875d9b61f46a134](https://cs.android.com/android-studio/platform/tools/adt/idea/+/06ee9d025d81da3104feb7efc875d9b61f46a134).
STAT (diff to AOSP): 65 insertions(+), 16 deletion(-)
Add project, target and BlazeContext parameters to getLocalFiles method as they
are required to invoke RuntimeArtifactCache.
Bug: 385469770
Test: Update existing tests and manually test by debugging java_binary
Change-Id: I625b22264bda11fb5fa4010ce0008fceb7cd1188
AOSP: 06ee9d025d81da3104feb7efc875d9b61f46a134

[AOSP-pick] Update getLocalFiles method to support RuntimeArtifactCache usage

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java

Cherry pick AOSP commit [89f52f6b0e05938e4ea778653bc91c0c8dd69f10](https://cs.android.com/android-studio/platform/tools/adt/idea/+/89f52f6b0e05938e4ea778653bc91c0c8dd69f10).
Note `externalDependenciesFor()` does what it says. It returns external
dependencies of a label but it does not return transitive dependencies.
The replacement methods added in this change do the same, however their
name reflect the intention of these methods, which is different. These
methods are supposed to tell whether a label depends directly or
indirectly on one of the well-known targets. The existing implementation
and its replacement, which is supposed to do the same as the existing
implementation, do not do what is needed, hence the new name.
Bug: 397354312 …

[AOSP-pick] Isolate kotlin coroutine debugging use case

---

querysync/java/com/google/idea/blaze/qsync/artifacts/ArtifactDirectoryUpdate.java

Cherry pick AOSP commit [9e010cda99cb3deaca4e9ae1a69e695988c0d929](https://cs.android.com/android-studio/platform/tools/adt/idea/+/9e010cda99cb3deaca4e9ae1a69e695988c0d929).
A path like `/some/path/.` cannot be deleted even though
`/some/path/./dir` can be. Also, the artifact directory itself should
not be deleted anyway.
Bug: n/a
Test: caught by tests in upcoming changes
Change-Id: I716a7f80ca9af89ab94518253af201e36945e8d8
AOSP: 9e010cda99cb3deaca4e9ae1a69e695988c0d929

[AOSP-pick] Fix deletion of all files in artifact directory

---

base/src/com/google/idea/blaze/base/command/buildresult/LocalFileArtifact.java

Cherry pick AOSP commit [21c61024727b2b5dd0e2c7e171307b3976177a84](https://cs.android.com/android-studio/platform/tools/adt/idea/+/21c61024727b2b5dd0e2c7e171307b3976177a84).
Update LocalFileArtifact to use RuntimeArtifactCache for storing the
artifacts for QuerySync.
Bug: 385469770
Test: Existing tests updated
Change-Id: If5f8e648f16a58820cf4a40fd58c67c600390182
AOSP: 21c61024727b2b5dd0e2c7e171307b3976177a84

[AOSP-pick] Update LocalFileArtifact to use RuntimeArtifactCache

---

querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/javatests/com/google/idea/blaze/qsync/project/BuildGraphDataTest.java

Cherry pick AOSP commit [ceacc934f248f3a1fd9a096eb5938f83b1542bca](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ceacc934f248f3a1fd9a096eb5938f83b1542bca).
STAT (diff to AOSP): 7 insertions(+), 13 deletion(-)
and temporarily introduce `getTransitiveExternalDependencies()`
to preserve tests that will be re-used.
Bug: 397354312
Test: n/a
Change-Id: Ie541cc2e6a43914605c2628e0bb4df4ad66fe592
AOSP: ceacc934f248f3a1fd9a096eb5938f83b1542bca

[AOSP-pick] Delete unused getFileDependencies()

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystemBase.java

Cherry pick AOSP commit [fed618721adcf20dd73c25ea384a8a4e4370d293](https://cs.android.com/android-studio/platform/tools/adt/idea/+/fed618721adcf20dd73c25ea384a8a4e4370d293).
STAT (diff to AOSP): 1 insertions(+), 1 deletion(-)
Preserve it within the Gradle Module System for the sake of its one
caller using it with the full generality of arbitrary version
additions.
Bug: 279886738
Test: existing
Change-Id: Ie42a07f796e2dc1a5d2926a2e5b2444716803d42
AOSP: fed618721adcf20dd73c25ea384a8a4e4370d293

[AOSP-pick] Remove analyzeCoordinateCompatiblity from AndroidModuleSystem

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java
base/src/com/google/idea/blaze/base/qsync/QuerySync.java
querysync/java/com/google/idea/blaze/qsync/GraphToProjectConverter.java
querysync/java/com/google/idea/blaze/qsync/SnapshotBuilder.java
querysync/java/com/google/idea/blaze/qsync/util/ProjectSpecBuilder.java

Cherry pick AOSP commit [481bd8c48d97b5bddbe3f8f9983b8b1d8a66e446](https://cs.android.com/android-studio/platform/tools/adt/idea/+/481bd8c48d97b5bddbe3f8f9983b8b1d8a66e446).
STAT (diff to AOSP): 1 insertions(+), 2 deletion(-)
query.sync.new.resdir.logic
query.sync.respackages.at.build.time
These experiments have not been changed recently and have not been
mentioned in bug reports.
Bug: n/a
Test: n/a
Change-Id: Ie753aa0967895e3e90cfeebf6c233f52acd0665b
AOSP: 481bd8c48d97b5bddbe3f8f9983b8b1d8a66e446

[AOSP-pick] Drop outdated experiments

---

base/src/com/google/idea/blaze/base/bazel/LocalInvoker.java
base/src/com/google/idea/blaze/base/run/BlazeBeforeRunCommandHelper.java
java/src/com/google/idea/blaze/java/run/BlazeJavaRunProfileState.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java

Cherry pick AOSP commit [3b43602f002a583dec99a57843bb5f4122df7789](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3b43602f002a583dec99a57843bb5f4122df7789).
STAT (diff to AOSP): 4 insertions(+), 9 deletion(-)
1. Updates ClassFileManifestBuilder so that the output is parsed from
the build event stream only once (fixes b/397735292 ).
2. Avoids creating a new BlazeContext in BlazebeforeRunCommandhelper.
3. Adds output sink to the context so that output is printed to the
debug console. Updates the ProcessHandler in BlazeJavaRunProfileState so
that the process terminates when destroyed (fixes b/397869417).
This change along with I3fa6311a269bbc18af9118de81d29d1eb73078f7
disabled Java code hotswapping while debugging, there's a bug
b/399392908 to track re-enabling it. …

[AOSP-pick] Fix java_binary debugging

---

base/src/com/google/idea/blaze/base/model/AspectSyncProjectData.java
base/src/com/google/idea/blaze/base/model/BlazeProjectData.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProjectData.java
base/src/com/google/idea/blaze/base/run/ui/TargetExpressionListUi.java
plugin_dev/src/com/google/idea/blaze/plugin/IntellijPluginRule.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfiguration.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfigurationType.java
python/src/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategy.java
querysync/java/com/google/idea/blaze/qsync/QuerySyncProjectSnapshot.java

Cherry pick AOSP commit [656359f19d35c563b89e58493fce2b32cd6de4dc](https://cs.android.com/android-studio/platform/tools/adt/idea/+/656359f19d35c563b89e58493fce2b32cd6de4dc).
STAT (diff to AOSP): 30 insertions(+), 1 deletion(-)
where possible. These are simpler data structures.
Bug: n/a
Test: n/a
Change-Id: Ib3cd3e303e0016dbe32788f63979f9b71c0dd95a
AOSP: 656359f19d35c563b89e58493fce2b32cd6de4dc

[AOSP-pick] Return simple labels instead of TargetTree

---

aswb/src/com/google/idea/blaze/android/sdk/BlazeSdkProviderImpl.java

Cherry pick AOSP commit [3e44a7cc182d0d19ba8167bb938d7265b7f1a2c9](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3e44a7cc182d0d19ba8167bb938d7265b7f1a2c9).
Or to getRepoManagerAndLoadSynchronously(), if needed.
Bug: 339641500
Test: n/a
Change-Id: I382078a3fb5b7b0524e4302c84ae656964dc9061
AOSP: 3e44a7cc182d0d19ba8167bb938d7265b7f1a2c9

[AOSP-pick] Migrate getSdkManager() to getRepoManager()

---

base/src/com/google/idea/blaze/base/qsync/ProjectStatsLogger.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProjectData.java
base/src/com/google/idea/blaze/base/qsync/action/BuildDependenciesForProjectAction.java
java/src/com/google/idea/blaze/java/run/producers/JavaBinaryContextProvider.java
python/src/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategy.java
querysync/java/com/google/idea/blaze/qsync/BUILD.bazel
querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java
querysync/java/com/google/idea/blaze/qsync/GraphToProjectConverter.java
querysync/java/com/google/idea/blaze/qsync/cc/CcWorkspaceBuilder.java
querysync/java/com/google/idea/blaze/qsync/cc/ConfigureCcCompilation.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphDataImpl.java
querysync/javatests/com/google/idea/blaze/qsync/project/BUILD
querysync/javatests/com/google/idea/blaze/qsync/project/BuildGraphDataImplTest.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/BuildGraphs.java

Cherry pick AOSP commit [3ebf215d7d36b00bf458042525892a7751211f03](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3ebf215d7d36b00bf458042525892a7751211f03).
STAT (diff to AOSP): 25 insertions(+), 32 deletion(-)
Bug: n/a
Test: n/a
Change-Id: I40ea0fcc4fda3680a4248aa836be7a5e050ae675
AOSP: 3ebf215d7d36b00bf458042525892a7751211f03

[AOSP-pick] Separate storage and logic in BuildGraphData

---

aswb/src/com/android/tools/idea/rendering/tokens/BazelBuildSystemFilePreviewServices.java

Cherry pick AOSP commit [1260875b8b38a76ccb436c819d791bbd317b686e](https://cs.android.com/android-studio/platform/tools/adt/idea/+/1260875b8b38a76ccb436c819d791bbd317b686e).
Bug: 400656413
Test: Existing
Change-Id: I61df7c7bb4d2f2d3c2557e2e7643c817bd964cc3
AOSP: 1260875b8b38a76ccb436c819d791bbd317b686e

[AOSP-pick] Skip throwing UnsupportedOperationException to avoid crash

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java

Cherry pick AOSP commit [a3305d03303e897f3f00f6dd7e4578d04fedce81](https://cs.android.com/android-studio/platform/tools/adt/idea/+/a3305d03303e897f3f00f6dd7e4578d04fedce81).
The BES does not send a TEST_RESULT event if the tests were not run (for
reasons such as build failures). Consequently, ASwB displays an
incorrect `All tests passed` message to the user.
This change isn't ideal, but works towards fixing this by adding a
`NO_STATUS` test result while parsing the BEP.
Bug: 400687547
Test: n/a
Change-Id: Ie2b694506515e80df6b3bcc4d33b1f3d5e7f8a5e
AOSP: a3305d03303e897f3f00f6dd7e4578d04fedce81

[AOSP-pick] Return NO_STATUS test result if no tests were run

---

querysync/java/com/google/idea/blaze/qsync/BUILD.bazel
querysync/java/com/google/idea/blaze/qsync/GraphToProjectConverter.java
querysync/java/com/google/idea/blaze/qsync/artifacts/BUILD
querysync/java/com/google/idea/blaze/qsync/cc/BUILD
querysync/java/com/google/idea/blaze/qsync/deps/BUILD
querysync/java/com/google/idea/blaze/qsync/deps/NewArtifactTracker.java
querysync/java/com/google/idea/blaze/qsync/java/AddProjectGenSrcs.java
querysync/java/com/google/idea/blaze/qsync/java/BUILD
querysync/java/com/google/idea/blaze/qsync/project/BUILD
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/project/PostQuerySyncData.java
querysync/java/com/google/idea/blaze/qsync/query/BUILD

Cherry pick AOSP commit [2b5c5154eeedf6b301ff955c37a564bd71b049e6](https://cs.android.com/android-studio/platform/tools/adt/idea/+/2b5c5154eeedf6b301ff955c37a564bd71b049e6).
STAT (diff to AOSP): 13 insertions(+), 2 deletion(-)
and this way enable Kotlin usage in the `querysync` library.
Also, fix issues detected by Android lint.
Bug: n/a
Test: n/a
Change-Id: I81544bdd6ff64da091b2e98c026cee41328d24f6
AOSP: 2b5c5154eeedf6b301ff955c37a564bd71b049e6

[AOSP-pick] Migrate querysync library to aswb_library rule

---

aswb/tests/unittests/com/google/idea/blaze/android/rendering/BlazeRenderErrorContributorTest.java

Cherry pick AOSP commit [dfbad115042e8fbd75852e8f610ce52497b157e6](https://cs.android.com/android-studio/platform/tools/adt/idea/+/dfbad115042e8fbd75852e8f610ce52497b157e6).
...temporarily, since it fails with IntelliJ 2025.1.
Bug: 401277613
Test: BlazeRenderErrorContributorTest
Change-Id: If0b766cd919cbb2f1bcb16aa13bb88c76fe8c6b0
AOSP: dfbad115042e8fbd75852e8f610ce52497b157e6

[AOSP-pick] Disable BlazeRenderErrorContributorTest

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java
base/src/com/google/idea/blaze/base/qsync/ProjectUpdater.java
base/src/com/google/idea/blaze/base/qsync/ProjectUpdaterHelper.kt
base/src/com/google/idea/blaze/base/qsync/QuerySync.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncBazelAdditionalLibraryRootsProvider.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncBazelOrderEnumeratorHandler.java
querysync/java/com/google/idea/blaze/qsync/DependenciesProjectProtoUpdater.java
querysync/java/com/google/idea/blaze/qsync/deps/BUILD
querysync/java/com/google/idea/blaze/qsync/deps/ProjectProtoUpdateOperation.java
querysync/java/com/google/idea/blaze/qsync/java/AddCompiledJavaDeps.java
querysync/java/com/google/idea/blaze/qsync/java/AddDependencyGenSrcsJars.java
querysync/java/com/google/idea/blaze/qsync/java/AddDependencySrcJars.java
querysync/javatests/com/google/idea/blaze/qsync/java/AddCompiledJavaDepsTest.java
querysync/javatests/com/google/idea/blaze/qsync/java/AddDependencyGenSrcsJarsTest.java
querysync/javatests/com/google/idea/blaze/qsync/java/AddDependencySrcJarsTest.java

Cherry pick AOSP commit [3f0a86a4e241c4fb46d8340335856b99542df849](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3f0a86a4e241c4fb46d8340335856b99542df849).
STAT (diff to AOSP): 38 insertions(+), 192 deletion(-)
Proivdes libraries and module root via api instead of registering via
library table. When there are too many libraries in library table, it
will lead to peformances issues e.g. rescan in one not cancellable
thread, O(N^2) scanning complexity.
Bug: b/374810387
Change-Id: I31c73a06b9e7dea6f82a6ba578ea35119f5a275e
AOSP: 3f0a86a4e241c4fb46d8340335856b99542df849

[AOSP-pick] Provides libraries via extension point instead of library table

---

querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphDataImpl.java

Cherry pick AOSP commit [0d5c5de6bae452f6687c9b07c7915c35191ff96f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/0d5c5de6bae452f6687c9b07c7915c35191ff96f).
instead of relying on on-demand `@Memoized`, which may be invoked on the
EDT.
Bug: 400652211
Test: n/a
Change-Id: I6b385c6c26980a05ba71430e3a54092d46c9314e
AOSP: 0d5c5de6bae452f6687c9b07c7915c35191ff96f

[AOSP-pick] Build useful maps explicitly

---

aswb/src/com/google/idea/blaze/android/run/runner/BlazeInstrumentationTestApkBuildStep.java
base/src/com/google/idea/blaze/base/bazel/BazelBuildSystem.java
base/src/com/google/idea/blaze/base/bazel/BuildSystem.java
base/src/com/google/idea/blaze/base/bazel/LocalInvoker.java
base/src/com/google/idea/blaze/base/qsync/BazelQueryRunner.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/sharding/ShardedTargetList.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BuildSystemProviderWrapper.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildSystem.java
java/src/com/google/idea/blaze/java/run/BlazeJavaRunProfileState.java

Cherry pick AOSP commit [226defcef8928f0846b8fb4346e840b5a2b38864](https://cs.android.com/android-studio/platform/tools/adt/idea/+/226defcef8928f0846b8fb4346e840b5a2b38864).
The capabilities of a build invoker are used like the hard requirements
by the callers to obtain an appropriate invoker. For example, if a
caller needs to build an android instrumentation test, it calls
getBuildInvoker with a required capability BUILDS_AIT.
This change updates the capabilities in such a way that they represent
what caller requires, instead of what a build system can do.
There is no behavior change in the IDE, the following changes are made
to the capabilities based on what they're used for.
1. IS_LOCAL -> BUILD_AIT.
2. SUPPORTS_PARALLELISM -> …

[AOSP-pick] Improve BuildInvoker capablities

---

base/src/com/google/idea/blaze/base/model/AspectSyncProjectData.java
base/src/com/google/idea/blaze/base/sync/ProjectStateSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncProjectState.java
base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectStorageService.kt
base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectTemplateWriter.kt
base/tests/unittests/com/google/idea/blaze/base/sync/BlazeSyncManagerTest.java

This is a fix for #7432 with a workaround applied to the latest codebase. The main problem was the fact, that we were not setting up `externalWorkspaceData` at all if bzlmod was disabled.
details.

Workaround fix for java project sync without bzlmod for bazel 8+

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java

Since #7562 introduces #7586 I'd suggest to revert this pick for the release tomorrow. Reverting this commit will reintroduce #472, however I already have an idea how to properly address this issue. 
I'll prepare a proper fix for #472 as part of the next beta release.

Revert "Return NO_STATUS test result if no tests were run (#7562)"

---

aspect/fast_build_info.bzl
aspect/intellij_info_impl.bzl

This is cherrypick of: 15bdabea953ae75a4b38acb0df5dd15981bb0576
PiperOrigin-RevId: 745510931
Strings used to refer to legacy struct providers, which were removed from Bazel.
Legacy struct providers have been deprecated by Bazel. Replacing them with modern providers, will make it possible to simplify and remove legacy handling from Blaze.
The change is a no-op.
More information: https://github.com/bazelbuild/bazel/issues/25836

fix: replace string with modern providers

---

clwb/BUILD
clwb/tests/headlesstests/com/google/idea/blaze/clwb/ExecutionTest.java
clwb/tests/headlesstests/com/google/idea/blaze/clwb/base/ClwbHeadlessTestCase.java

- Enable llvm integration test, since we paused AOSP picks we can enable these tests again
- Enable further tests for cc_test run configs after the fix in #7609

Enable CLion headless tests

---

clwb/src/META-INF/clwb-oclang.xml
clwb/src/META-INF/clwb.xml
clwb/src/com/google/idea/blaze/clwb/radler/RadTestEventsHandler.kt
clwb/src/com/google/idea/blaze/clwb/radler/optional-plugin.xml

oclang specific code was accidentally located in a shared library.

clion: fix CNFE for nova mode

---

base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/findusages/ExternalWorkspaceFindUsagesTest.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/references/ExternalWorkspaceReferenceTest.java
kotlin/tests/integrationtests/com/google/idea/blaze/kotlin/run/debug/BazelKotlinxCoroutinesLibFinderTest.java
python/tests/integrationtests/com/google/idea/blaze/python/resolve/provider/BazelPyGenfilesImportResolverStrategyTest.java
python/tests/integrationtests/com/google/idea/blaze/python/resolve/provider/BazelPyImportResolverStrategyTest.java
scala/tests/integrationtests/com/google/idea/blaze/scala/run/producers/DeployableJarRunConfigurationProducerTest.java

This is a small refactor of integration tests that has no effect on their execution. `BuildSystemName.Bazel` has been the default since 330f255dd3a06fd5133b9d6884e86572506f7f3a, and we will probably never run any tests for Blaze at all.

Remove redundant overrides of BlazeIntegrationTestCase.buildSystem()

---

base/src/com/google/idea/blaze/base/scope/output/IssueOutput.kt
testing/src/com/google/idea/testing/headless/SyncOutput.java

Truth just prints `toString()` version of asserted elements that does not have required information.
* Let truth print the issue itself
* Also assert with an extra message for debugging purposes

headless tests: improve error logging

---

aspect/fast_build_info.bzl

Previously java_info was shadowed with a new structure, so annotation_processing was certainly missing.

Fix annotation_processing in fast_build aspect

---

plugin_dev/src/com/google/idea/blaze/plugin/IntellijPluginRule.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfiguration.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfigurationType.java
querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySpecTest.java
shared/java/com/google/idea/blaze/common/RuleKinds.java

Fixes regression caused by #7548 that breaks the Bazel IntelliJ Plugin run configuration when using qsync.

Fix intellij plugin target collection with qsync

---

examples/scala/with_bzlmod/MODULE.bazel

Since the rules_scala version [7.0.0](https://github.com/bazel-contrib/rules_scala/releases/tag/v7.0.0) has been officially released, the repository override is no longer needed.
Fixes #7649.

Updated the example Scala project with Bzlmod.

---

base/src/com/google/idea/blaze/base/command/BlazeFlags.java
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java

This flag has been [renamed](https://blog.bazel.build/2022/01/19/bazel-5.0.html) in Bazel 5.0.

Changed '--noexperimental_run_validations' to '--norun_validations'.

---

base/src/com/google/idea/blaze/base/run/confighandler/BlazeCommandGenericRunConfigurationRunner.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java

Follow up for: #7622
Revert to previous behaviour of using the ScopedProcess Handler in the BlazeCommandGenericRunConfigurationRunner and remove support for the generic process handler.
FYI, the entire logic with BuildResultHelperBep and LocalBuildEventProtocolTestFinderStrategy is pretty messy. The result helper is closed before the strategy is executed, causing all the 'could not delete BEP file' warnings. This needs a proper refactor later.

Use scoped process handler in BlazeCommandGenericRunConfigurationRunner

---

base/src/com/google/idea/blaze/base/bazel/LocalInvoker.java
base/src/com/google/idea/blaze/base/command/CommandLineBlazeCommandRunner.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultParser.java
base/src/com/google/idea/blaze/base/command/buildresult/GetArtifactsException.java
base/src/com/google/idea/blaze/base/run/smrunner/BlazeXmlToTestEventsConverter.java
base/src/com/google/idea/blaze/base/run/testlogs/BlazeTestResultFinderStrategy.java
base/src/com/google/idea/blaze/base/run/testlogs/LocalBuildEventProtocolTestFinderStrategy.java
base/tests/unittests/com/google/idea/blaze/base/run/testlogs/LocalBuildEventProtocolTestFinderStrategyTest.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildResultHelperBep.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifestBuilder.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginDeployer.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BuildPluginBeforeRunTaskProvider.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [1b413f38e00ac9d4533b66012cec51bd81ff700b](https://cs.android.com/android-studio/platform/tools/adt/idea/+/1b413f38e00ac9d4533b66012cec51bd81ff700b).
STAT (diff to AOSP): 54 insertions(+), 20 deletion(-)
The BuildResultHelper abstraction is no longer used post-cleanup, and
will be deleted. The GetArtifactsException that currently is inside the
interface is used, so this change extracts it out into a separate class.
Bug:374906681
Change-Id: Ic89a342707a3b1b562fcfcc03f2260956a726eb8
AOSP: 1b413f38e00ac9d4533b66012cec51bd81ff700b

[AOSP-pick] Extract out GetArtifactsException from BuildResultHelper

---

base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java
base/src/com/google/idea/blaze/base/lang/buildfile/lexer/TokenKind.java
base/src/com/google/idea/blaze/base/lang/buildfile/parser/ExpressionParsing.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/parser/BuildParserTest.java

Supported operators: `& ^ >> << &= ^= |= >>= <<=`
Fixes #7733.

Highlighting support for binary operators and augmented assignments in BUILD files.

---

scala/src/META-INF/blaze-scala.xml
scala/src/META-INF/scala-contents.xml
scala/src/com/google/idea/blaze/scala/BlazeScalaBuildToolModuleHandler.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/7703
Use `BuildToolModuleHandler` API to register that the project is already imported via Bazel.

Implement `BuildToolModuleHandler` for Scala Projects to register Bazel Imported Scala Projects

---

base/src/com/google/idea/blaze/base/settings/BlazeUserSettings.java

For me "Expand Sync to Working Set" always causes problems. Let's disable it by default?

Disable expand sync to workings set by default

---

cpp/src/META-INF/blaze-cpp.xml
cpp/src/com/google/idea/blaze/cpp/HeaderRootTrimmerImpl.kt

Issue number: #7794
Add a registry flag to allow bazel-bin as a header search path again and enable it by default for now until we find a proper solution.

CLion: add registry key to allow bazel-bin as header search path

---

base/src/com/google/idea/blaze/base/bazel/BazelBuildSystem.java
base/src/com/google/idea/blaze/base/bazel/BuildSystem.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BuildSystemProviderWrapper.java

Cherry pick AOSP commit [6233a6e18098d592fb42842406b8678ec9e520c0](https://cs.android.com/android-studio/platform/tools/adt/idea/+/6233a6e18098d592fb42842406b8678ec9e520c0).
as they are only requested in the Bazel mode where the default one is
provided in this case.
Bug: n/a
Test: n/a
Change-Id: I2afb7d844bd7a5873982b87003201457e412f0f8
AOSP: 6233a6e18098d592fb42842406b8678ec9e520c0

[AOSP-pick] No need for special mobile_install invokers

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/qsync/analysis/QuerySyncEssentialHighlightingRestarterDisablement.java

Adding implementation for EssentialHighlightingRestarterDisablement

---

base/src/com/google/idea/blaze/base/bazel/BazelBuildSystem.java
base/src/com/google/idea/blaze/base/bazel/BuildSystem.java

Cherry pick AOSP commit [54b229050bff65aa93116357b756b9a38bc4688c](https://cs.android.com/android-studio/platform/tools/adt/idea/+/54b229050bff65aa93116357b756b9a38bc4688c).
Bug: n/a
Test: n/a
Change-Id: I1627c7a2aaedae582e8dc75d4ebea64d713cafa3
AOSP: 54b229050bff65aa93116357b756b9a38bc4688c

[AOSP-pick] Delete unused variant of getBuildInvoker()

---

aspect/BUILD
base/BUILD
base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectModuleWriter.kt
base/src/com/google/idea/blaze/base/sync/aspects/storage/AspectRepositoryProvider.kt

In preparation for modularization of the aspect. An aspect module is a collection of functions that can declare different dependencies. Only if all dependencies are fulfilled will the aspect module be written, otherwise only stubs will be generated.
Extracted from: #7834

Include Cache: AspectModuleWriter
