bazelbuild/intellij

aswb/2.3/tests/integrationtests/com/google/idea/blaze/android/sync/model/idea/BlazeClassJarProviderIntegrationTest.java
aswb/2.3/tests/unittests/com/google/idea/blaze/android/project/BlazeBuildSystemServiceTest.java
aswb/2.3/tests/unittests/com/google/idea/blaze/android/project/BlazeFeatureEnabledServiceTest.java
aswb/2.3/tests/unittests/com/google/idea/blaze/android/rendering/BlazeRenderErrorContributorTest.java
aswb/src/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncer.java
base/src/com/google/idea/blaze/base/model/BlazeProjectData.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncTask.java
base/src/com/google/idea/blaze/base/sync/data/BlazeProjectDataManagerImpl.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/projectview/ProjectViewIntegrationTestCase.java
base/tests/integrationtests/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationGenericHandlerIntegrationTest.java
base/tests/integrationtests/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationRunManagerImplTest.java
base/tests/integrationtests/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationSettingsEditorTest.java
base/tests/integrationtests/com/google/idea/blaze/base/run/exporter/RunConfigurationSerializerTest.java
base/tests/unittests/com/google/idea/blaze/base/actions/BlazeBuildServiceTest.java
base/tests/unittests/com/google/idea/blaze/base/targetmaps/TransitiveDependencyMapTest.java
base/tests/utils/integration/com/google/idea/blaze/base/BlazeIntegrationTestCase.java
base/tests/utils/integration/com/google/idea/blaze/base/lang/buildfile/BuildFileIntegrationTestCase.java
base/tests/utils/unit/com/google/idea/blaze/base/model/MockBlazeProjectDataBuilder.java
base/tests/utils/unit/com/google/idea/blaze/base/model/MockBlazeProjectDataManager.java
intellij_platform_sdk/BUILD.android_studio
intellij_platform_sdk/missing/src/dummy/pkg/DummyClassToAvoidAnEmptyJavaLibrary.java
intellij_platform_sdk/missing/tests/com/jetbrains/cidr/modulemap/resolve/MockModuleMapManagerImpl.java

Import of bazel plugin using copybara

---

CHANGELOG

Automatic GitHub Sync with Copybara

Automatic GitHub Sync with Copybara

---

CODEOWNERS

(So I don't get constant emails about reviewing pull requests.)

Remove myself from CODEOWNERS.

---

aswb/src/com/google/idea/blaze/android/sync/importer/BlazeAndroidWorkspaceImporter.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/importer/BlazeAndroidWorkspaceImporterTest.java

Choose best match Manifest file

Choose best match Manifest file

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/run/filter/TestLogFilter.java
base/tests/unittests/com/google/idea/blaze/base/run/filter/TestLogFilterTest.java

Hyperlink test log output file in console output.

Hyperlink test log output file in console output.

---

base/src/com/google/idea/blaze/base/dependencies/TargetInfo.java
base/src/com/google/idea/blaze/base/ideinfo/TargetIdeInfo.java
java/src/META-INF/java-contents.xml
java/src/com/google/idea/blaze/java/run/TestClassHeuristic.java
java/tests/integrationtests/com/google/idea/blaze/java/run/TestClassHeuristicTest.java

Add a test heuristic matching by 'test_class' attribute

Add a test heuristic matching by 'test_class' attribute

---

base/src/com/google/idea/blaze/base/prefetch/PrefetchIndexingTask.java
base/src/com/google/idea/blaze/base/prefetch/PrefetchProjectInitializer.java

Do initial project prefetching inside a dumb mode task with progress dialog.

Do initial project prefetching inside a dumb mode task with progress dialog.

---

java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java

Java language level selection: choose the maximum language level, not the first.

Java language level selection: choose the maximum language level, not the first.

---

base/src/com/google/idea/blaze/base/run/smrunner/BlazeXmlSchema.java
base/src/com/google/idea/blaze/base/run/smrunner/BlazeXmlToTestEventsConverter.java
base/tests/unittests/com/google/idea/blaze/base/run/smrunner/BlazeXmlSchemaTest.java

Test xml parsing: handle missing error content field

Test xml parsing: handle missing error content field

---

java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java

Fix fast-build exception when targets are built against multiple configurations.

Fix fast-build exception when targets are built against multiple configurations.

---

golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java

Fix BlazeGoPackage processing files by directory.

Fix BlazeGoPackage processing files by directory.

---

aspect/java_classpath.bzl

Fix indirect loads in java_classpath.bzl

Fix indirect loads in java_classpath.bzl

---

aspect/intellij_info_impl.bzl
base/src/com/google/idea/blaze/base/ideinfo/GoIdeInfo.java
golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java
golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackageFactory.java
golang/tests/integrationtests/com/google/idea/blaze/golang/resolve/BlazeGoImportResolverTest.java
proto/intellij_ide_info.proto

Fix embeded libraries for bazel go_test.

Fix embeded libraries for bazel go_test.

---

base/src/com/google/idea/blaze/base/command/BuildFlagsProviderImpl.java

Don't specify an 'experimental_ui' blaze flag.

Don't specify an 'experimental_ui' blaze flag.

---

build_defs/build_defs.bzl
build_defs/zip_plugin_files.py

zip_plugin_files: preserve file modes of inputs

zip_plugin_files: preserve file modes of inputs

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/actions/FullSyncProjectAction.java

Remove 'non-incremental' sync option from the sync menu.

Remove 'non-incremental' sync option from the sync menu.

---

base/src/com/google/idea/blaze/base/console/BlazeConsoleView.java

Fix console filters not being properly set up on first project open.

Fix console filters not being properly set up on first project open.

---

CHANGELOG

Update changelogs for the 2019.05.13 release

Update changelogs for the 2019.05.13 release

---

WORKSPACE

Update IJ CE 2019.1.1 to 2019.1.2

Update IJ CE 2019.1.1 to 2019.1.2

---

WORKSPACE

Update IJ UE 2019.1.1 to 2019.1.2

Update IJ UE 2019.1.1 to 2019.1.2

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.android_studio34
intellij_platform_sdk/build_defs.bzl

Switch aswb-beta to point to AS 3.5

Switch aswb-beta to point to AS 3.5

---

WORKSPACE

Update CLion 2019.1.2 to CLion 2019.1.3

Update CLion 2019.1.2 to CLion 2019.1.3

---

base/BUILD
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/vcs/VcsSyncListener.java

Add a mechanism for listening to VCS syncs.

Add a mechanism for listening to VCS syncs.

---

WORKSPACE

Import Android Studio 3.4.1 (3.4.1.0)

Import Android Studio 3.4.1 (3.4.1.0)

---

base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java

Fix configuration handling in BEP parsing.

Fix configuration handling in BEP parsing.

---

WORKSPACE

Update mockito library.

---

aswb/tests/unittests/com/google/idea/blaze/android/projectsystem/BlazeModuleSystemTest.java
aswb/tests/unittests/com/google/idea/blaze/android/rendering/BlazeRenderErrorContributorTest.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/importer/BlazeAndroidWorkspaceImporterTest.java
aswb/tests/unittests/com/google/idea/blaze/android/sync/model/idea/BlazeAndroidModelTest.java
base/src/com/google/idea/blaze/base/settings/BlazeImportSettingsManager.java
base/src/com/google/idea/blaze/base/wizard2/BlazeNewProjectBuilder.java
base/tests/unittests/com/google/idea/blaze/base/actions/BlazeBuildServiceTest.java
base/tests/unittests/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationTest.java
base/tests/unittests/com/google/idea/blaze/base/run/state/BlazeCommandRunConfigurationCommonStateTest.java
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeCompilerSettingsTest.java
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeConfigurationResolverTest.java
cpp/tests/unittests/com/google/idea/blaze/cpp/BlazeResolveConfigurationEquivalenceTest.java
golang/tests/unittests/com/google/idea/blaze/golang/run/BlazeDlvPositionConverterTest.java
java/tests/unittests/com/google/idea/blaze/java/run/BlazeJavaRunProfileStateTest.java
java/tests/unittests/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporterTest.java
python/tests/unittests/com/google/idea/blaze/python/issueparser/PyIssueParserProviderTest.java
scala/tests/unittests/com/google/idea/blaze/scala/sync/importer/BlazeScalaWorkspaceImporterTest.java

Ensure Blaze#isBlazeProject returns true during project setup for newly created projects.

Ensure Blaze#isBlazeProject returns true during project setup for newly created projects.

---

testing/src/com/google/idea/testing/IntellijRule.java
testing/src/com/google/idea/testing/TestUtils.java

Move IntellijRule to common test utilities.

Move IntellijRule to common test utilities.

---

testing/src/com/google/idea/testing/IntellijRule.java
testing/src/com/google/idea/testing/TestUtils.java

Clean up IntellijRule a bit; use ServiceHelper.

Clean up IntellijRule a bit; use ServiceHelper.

---

WORKSPACE

Update protobuf dependency

---

common/experiments/BUILD
common/experiments/src/com/google/idea/common/experiments/FeatureRolloutExperiment.java
common/experiments/src/com/google/idea/common/experiments/InternalDevFlag.java
common/experiments/tests/unittests/com/google/idea/common/experiments/FeatureRolloutExperimentTest.java

Add a developer flag for disabling all dogfooding experiments.

Add a developer flag for disabling all dogfooding experiments.

---

javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/javascript/run/producers/NonBlazeProducerSuppressor.java

Suppress javascript producers.

Suppress javascript producers.

---

WORKSPACE

Import Android Studio 3.5 Beta 2 (3.5.0.14)

Import Android Studio 3.5 Beta 2 (3.5.0.14)

---

common/experiments/src/com/google/idea/common/experiments/ExperimentUsernameProvider.java
common/experiments/src/com/google/idea/common/experiments/FeatureRolloutExperiment.java
common/experiments/src/com/google/idea/common/experiments/InternalDevFlag.java

Add a developer override for receiving another user's set of experiments.

Add a developer override for receiving another user's set of experiments.

---

common/experiments/src/com/google/idea/common/experiments/FeatureRolloutExperiment.java
common/experiments/tests/unittests/com/google/idea/common/experiments/FeatureRolloutExperimentTest.java

Fix FeatureRolloutExperimentTest#testUserHashesInCorrectRange and add more hash tests.

Fix FeatureRolloutExperimentTest#testUserHashesInCorrectRange and add more hash tests.

---

aswb/src/META-INF/aswb.xml
aswb/src/com/google/idea/blaze/android/libraries/UnpackedAars.java
aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystem.java
aswb/src/com/google/idea/blaze/android/projectsystem/PsiBasedClassFileFinder.java
aswb/src/com/google/idea/blaze/android/projectsystem/TransitiveClosureClassFileFinder.java
aswb/src/com/google/idea/blaze/android/rendering/BlazeRenderErrorContributor.java
aswb/src/com/google/idea/blaze/android/resources/actions/BlazeCreateResourceUtils.java
aswb/src/com/google/idea/blaze/android/sync/AndroidPrefetchFileSource.java
aswb/src/com/google/idea/blaze/android/sync/importer/BlazeModelConverter.java
aswb/src/com/google/idea/blaze/android/sync/importer/problems/GeneratedResourceClassifier.java
aswb/src/com/google/idea/blaze/android/sync/importer/problems/GeneratedResourceWarnings.java
aswb/src/com/google/idea/blaze/android/sync/model/BlazeResourceLibrary.java
aswb/src/com/google/idea/blaze/android/sync/model/idea/BlazeClassJarProvider.java
aswb/src/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncer.java
base/src/com/google/idea/blaze/base/command/buildresult/OutputArtifactResolver.java

Replace usage of ArtifactLocationDecoder in android plugins

Replace usage of ArtifactLocationDecoder in android plugins

---

aswb/tests/integrationtests/com/google/idea/blaze/android/projectsystem/BlazeSampleDataDirectoryProviderTest.java

Use NbAndroidTarget API in BlazeSampleDataDirectoryProviderTest

Use NbAndroidTarget API in BlazeSampleDataDirectoryProviderTest

---

clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeGDBServerProvider.java

BlazeCidrLauncher: Separate GDBServer-specific stuff

BlazeCidrLauncher: Separate GDBServer-specific stuff

---

base/src/com/google/idea/blaze/base/model/RemoteOutputArtifacts.java
java/src/com/google/idea/blaze/java/libraries/JarCache.java
java/src/com/google/idea/blaze/java/sync/model/BlazeJarLibrary.java
java/src/com/google/idea/blaze/java/sync/source/SourceDirectoryCalculator.java

Handle jars missing from the cache more gracefully.

Handle jars missing from the cache more gracefully.

---

base/src/com/google/idea/blaze/base/settings/BlazeUserSettings.java

Remove some now-unused settings.

Remove some now-unused settings.

---

scala/src/com/google/idea/blaze/scala/ScalaJavaLikeLanguage.java

Don't delegate scala tests to the java test handler.

Don't delegate scala tests to the java test handler.

---

WORKSPACE

Import Android Studio 3.5 Beta 3 (3.5.0.15)

Import Android Studio 3.5 Beta 3 (3.5.0.15)

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/settings/BlazeUserSettings.java
base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsConfigurable.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncStartupActivity.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncSettings.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncSettingsConfigurable.java
base/src/com/google/idea/blaze/base/sync/autosync/BuildFileAutoSyncProvider.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectViewAutoSyncProvider.java
base/src/com/google/idea/blaze/base/sync/autosync/ProtoAutoSyncProvider.java

Move auto-sync settings to a separate class, UI configurable

Move auto-sync settings to a separate class, UI configurable

---

CHANGELOG

Changelog for v2019.05.29

---

aspect/fast_build_info.bzl
aspect/intellij_info_impl.bzl

Stop reading java_toolchain.javac_jar

Stop reading java_toolchain.javac_jar

---

base/src/com/google/idea/blaze/base/ideinfo/JavaToolchainIdeInfo.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildBlazeData.java
proto/fast_build_info.proto
proto/intellij_ide_info.proto

Remove now unused fields from the java toolchain proto messages.

Remove now unused fields from the java toolchain proto messages.

---

common/experiments/src/com/google/idea/common/experiments/ExperimentServiceImpl.java
common/experiments/src/com/google/idea/common/experiments/FileExperimentLoader.java

Initialize experiments synchronously on startup.

Initialize experiments synchronously on startup.

---

intellij_platform_sdk/BUILD

Add AS 3.6 Canary 1 (3.6.0.1) plugin SDK

Add AS 3.6 Canary 1 (3.6.0.1) plugin SDK

---

java/src/com/google/idea/blaze/java/run/producers/NonBlazeProducerSuppressor.java

Suppress some additional run configuration producers in blaze projects.

Suppress some additional run configuration producers in blaze projects.

---

base/src/com/google/idea/blaze/base/run/producers/TestContext.java

Consolidate TestContext builder to always produce a PendingAsyncTestContext.
This will reduce the complexity if we need to apply any further
transformations after the target is resolved. Since we finish
resolving the target in one place, we only have to worry about one
location when applying the transformation.
If the target is immediately resolved, the listener on the future will
still run and should immediately replace the pending context with the
actual target.

Consolidate TestContext builder to always produce a PendingAsyncTestContext.

---

aswb/src/com/google/idea/blaze/android/rendering/BlazeRenderErrorContributor.java

Use Guava's Preconditions

---

aswb/sdkcompat/as34/com/google/idea/blaze/android/run/ApplyChangesCompat.java
aswb/sdkcompat/as35/com/google/idea/blaze/android/run/AndroidSessionInfoCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/AndroidSessionInfoCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/ApplyChangesCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/BlazeAndroidRunState.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/DeployTargetProviderCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/DeployTaskCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/LaunchStatusCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/LaunchTaskRunnerCompat.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryNormalBuildRunContext.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryProgramRunner.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryRunConfigurationHandler.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeAndroidRunConfigurationRunner.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestProgramRunner.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationHandler.java
aswb/src/com/google/idea/blaze/android/run/test/ConnectBlazeTestDebuggerTask.java

Create compat folder for AS 3.6

Create compat folder for AS 3.6

---

aswb/BUILD
intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
testing/BUILD
third_party/python/BUILD

Switch AS canary to point to 3.6

Switch AS canary to point to 3.6

---

base/BUILD

Update AS 3.6 plugin SDK to 3.6 Canary 2

Update AS 3.6 plugin SDK to 3.6 Canary 2

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/BlazeSyncManager.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncHandler.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncSettings.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncSettingsConfigurable.java
base/src/com/google/idea/blaze/base/sync/autosync/VcsAutoSyncProvider.java

Add support for automatically syncing on changes to the VCS base CL.

Add support for automatically syncing on changes to the VCS base CL.

---

common/experiments/src/com/google/idea/common/experiments/ExperimentServiceImpl.java

Fix experiments never updating after application startup.

Fix experiments never updating after application startup.

---

base/src/com/google/idea/blaze/base/run/producers/PendingAsyncTestContext.java
base/src/com/google/idea/blaze/base/run/producers/TestContext.java

Split PendingAsyncTestContext from TestContext.

Split PendingAsyncTestContext from TestContext.

---

javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/javascript/JavascriptBlazeRules.java
javascript/src/com/google/idea/blaze/javascript/run/producers/JavascriptTestContextProvider.java
javascript/src/com/google/idea/blaze/javascript/run/producers/JavascriptTestTargetHeuristic.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/producers/JavascriptTestContextProviderTest.java

Add javascript test context.

---

java/src/com/google/idea/blaze/java/libraries/BlazeAttachSourceProvider.java

Automatically attach source jars asynchronously

Automatically attach source jars asynchronously

---

aswb/src/com/google/idea/blaze/android/libraries/UnpackedAars.java
base/src/com/google/idea/blaze/base/filecache/FileCache.java
base/src/com/google/idea/blaze/base/filecache/FileCaches.java
base/src/com/google/idea/blaze/base/prefetch/PrefetchProjectInitializer.java
java/src/com/google/idea/blaze/java/libraries/JarCache.java

Read jar cache state on project open.

Read jar cache state on project open.

---

javascript/src/com/google/idea/blaze/javascript/run/producers/JavascriptTestContextProvider.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/producers/JavascriptTestContextProviderTest.java

Add test context for old style closure imports.

Add test context for old style closure imports.

---

scala/src/META-INF/scala-contents.xml
scala/src/com/google/idea/blaze/scala/sync/ScalaSyncStatusContributor.java

Add a sync status contributor for Scala

Add a sync status contributor for Scala

---

base/src/com/google/idea/blaze/base/ideinfo/TargetIdeInfo.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
proto/intellij_ide_info.proto

Store per-target last synced time in plugin's target map.
Will be used by automatic sync manager.

Store per-target last synced time in plugin's target map.

---

base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Fix race condition causing incorrect ProjectViewSet to be passed to SyncListener#onSyncComplete

Fix race condition causing incorrect ProjectViewSet to be passed to SyncListener#onSyncComplete

---

CHANGELOG

Changelog for v2019.06.03

---

base/src/META-INF/blaze-base.xml

Add the 'non-incremental' sync option back to the sync menu

Add the 'non-incremental' sync option back to the sync menu

---

clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java

Use LLDB driver for if debugger is LLDB.

Use LLDB driver for if debugger is LLDB.

---

aswb/BUILD
aswb/src/com/google/idea/blaze/android/libraries/UnpackedAars.java
aswb/tests/integrationtests/com/google/idea/blaze/android/AswbGotoDeclarationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/AswbMergedManifestTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeModuleSystemDependentLibrariesIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeModuleSystemExternalDependencyIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/sync/AndroidSyncTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/targetmapbuilder/NbTargetMapBuilderTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/targetmapbuilder/NbTargetMapUtilsTest.java
aswb/tests/utils/integration/com/google/idea/blaze/android/AswbIntegrationTestSetupRule.java
aswb/tests/utils/integration/com/google/idea/blaze/android/BlazeAndroidIntegrationTestCase.java
aswb/tests/utils/integration/com/google/idea/blaze/android/libraries/AarLibraryFileBuilder.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbAarTarget.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbAndroidTarget.java
aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/NbJavaTarget.java

Update aswb integration test

---

base/BUILD
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/dependencies/ExternalFileProjectManagementHelper.java
base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsCompositeConfigurable.java
base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsConfigurable.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncSettingsConfigurable.java
common/settings/BUILD
common/settings/src/com/google/idea/common/settings/SearchableOption.java
common/settings/src/com/google/idea/common/settings/SearchableOptionHelper.java
java/BUILD
java/src/com/google/idea/blaze/java/settings/BlazeJavaUserSettingsConfigurable.java

Register searchable settings on startup, not when the UI is displayed.

Register searchable settings on startup, not when the UI is displayed.

---

base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java

Fix NPE during sync

---

aswb/src/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncer.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/AswbMergedManifestTest.java

Add manifest as content root of AndroidResourceModules
Currently, there's an inconsistency in how we model projects regarding which module owns an AndroidManifest.xml file: ModuleUtilCore#findModuleForFile (and therefore AndroidFacet#getInstance) reports that all AndroidManifest.xml files belong to the .workspace module, whereas IdeaSourceProvider#getManifestFiles reports that the .workspace module has no manifest files and that every resource module has the manifest
that was specified in its corresponding BUILD target.
This CL reconciles the two methods by adding each manifest file as a content root of the resource module whose corresponding build target specifies that manifest. The end result is that ModuleUtilCore#findModuleForFile now returns the resource module instead of the …

Add manifest as content root of AndroidResourceModules

---

aswb/src/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncer.java

Add null check for manifest content roots

Add null check for manifest content roots

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestEventsHandler.java
base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestLocator.java
golang/src/com/google/idea/blaze/golang/run/smrunner/BlazeGoTestEventsHandler.java
golang/src/com/google/idea/blaze/golang/run/smrunner/BlazeGoTestLocator.java
golang/tests/integrationtests/com/google/idea/blaze/golang/run/smrunner/BlazeGoWebTestEventsHandlerTest.java
java/src/com/google/idea/blaze/java/run/producers/BlazeJUnitTestFilterFlags.java
java/tests/integrationtests/com/google/idea/blaze/java/run/BlazeJavaWebTestEventsHandlerTest.java

Add web test events handler and locator.

Add web test events handler and locator.

---

base/BUILD
base/src/com/google/idea/blaze/base/logging/LoggedSettingsProvider.java
common/experiments/src/com/google/idea/common/experiments/BoolExperiment.java
common/experiments/src/com/google/idea/common/experiments/Experiment.java
common/experiments/src/com/google/idea/common/experiments/ExperimentNameHashes.java
common/experiments/src/com/google/idea/common/experiments/ExperimentService.java
common/experiments/src/com/google/idea/common/experiments/ExperimentServiceImpl.java
common/experiments/src/com/google/idea/common/experiments/FeatureRolloutExperiment.java
common/experiments/src/com/google/idea/common/experiments/HashingExperimentLoader.java
common/experiments/src/com/google/idea/common/experiments/IntExperiment.java
common/experiments/src/com/google/idea/common/experiments/StringExperiment.java
common/experiments/tests/unittests/com/google/idea/common/experiments/ExperimentServiceImplTest.java
common/experiments/tests/unittests/com/google/idea/common/experiments/SystemPropertyExperimentLoaderTest.java
common/experiments/tests/utils/unit/com/google/idea/common/experiments/MockExperimentService.java

Logging for experiments.

---

base/src/com/google/idea/blaze/base/scope/scopes/PerformanceWarningScope.java

Tweak Blaze performance warnings output to make it clearer.

Tweak Blaze performance warnings output to make it clearer.

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystem.java

Update IntelliJ plugin SDKs to 3.6 Canary 3 (3.6.0.3)

Update IntelliJ plugin SDKs to 3.6 Canary 3 (3.6.0.3)

---

base/src/com/google/idea/blaze/base/ideinfo/JsIdeInfo.java
javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/javascript/run/smrunner/BlazeJavascriptTestEventsHandler.java
javascript/src/com/google/idea/blaze/javascript/run/smrunner/BlazeJavascriptTestLocator.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/smrunner/BlazeJavascriptWebTestEventsHandlerTest.java

Add test handler and locator for javascript tests.

Add test handler and locator for javascript tests.

---

base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestEventsHandler.java
base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestLocator.java
javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/javascript/run/producers/BlazeJavaScriptTestRunLineMarkerContributor.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/producers/BlazeJavaScriptTestRunLineMarkerContributorTest.java

Add gutter icons for javascript tests.

Add gutter icons for javascript tests.

---

base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestEventsHandler.java
base/src/com/google/idea/blaze/base/run/smrunner/BlazeXmlToTestEventsConverter.java

Fix display for nested test suites.

Fix display for nested test suites.

---

testing/src/com/google/idea/testing/BlazeTestSystemPropertiesRule.java
testing/src/com/google/idea/testing/TestUtils.java

Expose getTmpDir() in common TestUtils.

Expose getTmpDir() in common TestUtils.

---

testing/test_defs.bzl

Use intellij_unit_test_suite for IntelliJ tests.

Use intellij_unit_test_suite for IntelliJ tests.

---

golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java

Don't set import path on go native config. Fixes #850.

Don't set import path on go native config. Fixes #850.

---

golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java
golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackageFactory.java
golang/src/com/google/idea/blaze/golang/sync/BlazeGoAdditionalLibraryRootsProvider.java

Fix NPE during first sync.

---

aspect/intellij_info_impl.bzl

Avoid using resource provider in android

Avoid using resource provider in android

---

aswb/src/com/google/idea/blaze/android/libraries/UnpackedAars.java
aswb/tests/integrationtests/com/google/idea/blaze/android/AswbGotoDeclarationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeModuleSystemDependentLibrariesIntegrationTest.java
base/src/com/google/idea/blaze/base/filecache/FileCache.java
base/src/com/google/idea/blaze/base/filecache/FileCacheDiffer.java
base/src/com/google/idea/blaze/base/filecache/FileCaches.java
base/src/com/google/idea/blaze/base/prefetch/PrefetchProjectInitializer.java
java/src/com/google/idea/blaze/java/libraries/JarCache.java

Fix some bugs in our local jar caches.

Fix some bugs in our local jar caches.

---

aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeModuleSystemDependentLibrariesIntegrationTest.java

Re-enable BlazeModuleSystemDependentLibrariesIntegrationTest

Re-enable BlazeModuleSystemDependentLibrariesIntegrationTest

---

CHANGELOG

Changelog for v2019.06.17

---

base/src/com/google/idea/blaze/base/lang/buildfile/language/semantics/AttributeDefinition.java
base/src/com/google/idea/blaze/base/lang/buildfile/language/semantics/RuleDefinition.java

Update hack to work around blaze 'name' attribute bug.

Update hack to work around blaze 'name' attribute bug.

---

base/src/com/google/idea/blaze/base/lang/buildfile/completion/BuiltInFunctionCompletionContributor.java
base/src/com/google/idea/blaze/base/lang/buildfile/livetemplates/RulesTemplates.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/BuiltInFunctionCompletionContributorTest.java

Live Templates for basic java rules in BUILD files.

Live Templates for basic java rules in BUILD files.

---

base/BUILD
base/src/com/google/idea/blaze/base/lang/buildfile/livetemplates/RulesTemplates.java
base/src/com/google/idea/blaze/base/lang/buildfile/validation/AttributeTypeGroups.java
base/src/com/google/idea/blaze/base/lang/buildfile/validation/BuildElementValidation.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/BuiltInFunctionCompletionContributorTest.java

Default values for BUILD language templates and srcs+deps experiment.

Default values for BUILD language templates and srcs+deps experiment.

---

base/BUILD
base/src/com/google/idea/blaze/base/lang/buildfile/livetemplates/RulesTemplates.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/completion/BuiltInFunctionCompletionContributorTest.java

BUILD language Srcs+Deps experiment is simple boolean experiment

BUILD language Srcs+Deps experiment is simple boolean experiment

---

base/src/com/google/idea/blaze/base/run/producers/RunConfigurationContext.java

Ensure getSourceElementString happens under read access.

Ensure getSourceElementString happens under read access.

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
third_party/javascript/BUILD
third_party/python/BUILD

Import CLion 2019.2 EAP

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java

Move external library sync to before project update.

Move external library sync to before project update.

---

java/src/com/google/idea/blaze/java/sync/source/JavaLikeLanguage.java
java/src/com/google/idea/blaze/java/sync/workingset/JavaWorkingSet.java

Update modified file in JavaWorkingSet
Currently, we only include modified java file in JavaWorkingSet, however kotlin
which is java like language should be included in JavaWorkingSet as well to
make sure all Kotlin files can be treated similar with Java language when we
import jar for android project.

Update modified file in JavaWorkingSet

---

base/src/com/google/idea/blaze/base/run/BlazeRunConfigurationSyncListener.java
sdkcompat/v183/com/google/idea/sdkcompat/run/RunConfigurationBaseCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/run/RunConfigurationBaseCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/run/RunConfigurationBaseCompat.java

Inline compat method to add before run tasks

Inline compat method to add before run tasks

---

java/src/com/google/idea/blaze/java/plugin/JUnitPluginDependencyWarning.java

Adapt for signature change to AppLifecycleListener

Adapt for signature change to AppLifecycleListener

---

java/src/com/google/idea/blaze/java/run/BlazeCompilerManager.java
sdkcompat/v183/BUILD
sdkcompat/v183/com/google/idea/sdkcompat/java/CompatCompilerManagerImpl.java
sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/java/CompatCompilerManagerImpl.java
sdkcompat/v192/com/google/idea/sdkcompat/java/CompatCompilerManagerImpl.java

Adapt for signature changes to CompilerManagerImpl

Adapt for signature changes to CompilerManagerImpl

---

base/src/com/google/idea/blaze/base/sync/BlazeSyncStartupActivity.java

Run an initial directory-only sync when first creating a project.

Run an initial directory-only sync when first creating a project.

---

cpp/src/com/google/idea/blaze/cpp/BulkSymbolTableBuildingChangeListener.java
sdkcompat/v183/com/google/idea/sdkcompat/cidr/SymbolTableProviderCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/cidr/SymbolTableProviderCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/SymbolTableProviderCompat.java

Adapt for change in signature to SymbolTableProvider

Adapt for change in signature to SymbolTableProvider

---

WORKSPACE

Import Android Studio 3.5 Beta 5 (3.5.0.17)

Import Android Studio 3.5 Beta 5 (3.5.0.17)

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystem.java

Update IntelliJ plugin SDKs to 3.6 Canary 4 (3.6.0.4)

Update IntelliJ plugin SDKs to 3.6 Canary 4 (3.6.0.4)

---

aswb/src/com/google/idea/blaze/android/cppimpl/debug/BlazeAutoAndroidDebugger.java

Add logging for native debugger usage in BlazeAutoAndroidDebugger.

Add logging for native debugger usage in BlazeAutoAndroidDebugger.

---

base/src/com/google/idea/blaze/base/sync/BlazeSyncBuildResult.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/ProjectStateSyncTask.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/SyncScope.java

Blaze sync: extract SyncProjectState calculation from the blaze build step.

Blaze sync: extract SyncProjectState calculation from the blaze build step.

---

base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java
base/tests/unittests/com/google/idea/blaze/base/lang/buildfile/lexer/AbstractLexerTest.java

Update octal parsing for BUILD files

Update octal parsing for BUILD files

---

base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Fix NPE in the sync process

---

base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceState.java
proto/project_data.proto

Remove workspace language settings from BlazeIdeInterfaceState

Remove workspace language settings from BlazeIdeInterfaceState

---

base/src/com/google/idea/blaze/base/filecache/ArtifactState.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceState.java
java/src/com/google/idea/blaze/java/sync/jdeps/JdepsState.java
proto/project_data.proto

Remove some old migration code from the project data proto.

Remove some old migration code from the project data proto.

---

CHANGELOG

Update changelogs for 2019.07.01 release.

Update changelogs for 2019.07.01 release.

---

base/src/com/google/idea/blaze/base/model/ProjectTargetData.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterface.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceState.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java

Package all the target map related data together.

Package all the target map related data together.

---

javascript/BUILD
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfigServiceImpl.java
javascript/src/com/google/idea/blaze/typescript/DelegatingTypeScriptConfigService.java

Restart typescript service after running blaze sync.

Restart typescript service after running blaze sync.

---

base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterface.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java

Fix up null handling in sync target data calculation

Fix up null handling in sync target data calculation

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
third_party/javascript/BUILD
third_party/python/BUILD

Point CL stable branch to 2019.1

Point CL stable branch to 2019.1

---

base/src/com/google/idea/blaze/base/model/ProjectTargetData.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/SyncScope.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceState.java

Pull target data update task out of ProjectUpdateSyncTask.

Pull target data update task out of ProjectUpdateSyncTask.

---

base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Add a 'filter project targets' sync task.

Add a 'filter project targets' sync task.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/dependencies/SourceToTargetFilteringStrategy.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncManager.java

Add a 'remove deleted targets' sync action.

Add a 'remove deleted targets' sync action.

---

base/src/com/google/idea/blaze/base/model/primitives/WorkspaceRoot.java

Rearranging WorkspaceRoot methods.

Rearranging WorkspaceRoot methods.

---

build_defs/intellij_plugin_debug_target.bzl

Fixes for --incompatible_depset_is_not_iterable.

Fixes for --incompatible_depset_is_not_iterable.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java
base/src/com/google/idea/blaze/base/dependencies/DirectoryToTargetProvider.java
base/src/com/google/idea/blaze/base/settings/BlazeUserSettings.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/actions/DeriveSyncTargetsFromDirectoriesAction.java

Optionally derive targets from project directories

Optionally derive targets from project directories

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/projectview/section/sections/AutomaticallyDeriveTargetsSection.java
base/src/com/google/idea/blaze/base/projectview/section/sections/Sections.java
base/src/com/google/idea/blaze/base/projectview/section/sections/TargetSection.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/projectview/ProjectViewCompletionTest.java
base/tests/unittests/com/google/idea/blaze/base/projectview/ProjectViewSetTest.java

Add a blazeproject section to toggle deriving targets from directories.

Add a blazeproject section to toggle deriving targets from directories.

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java

Tweaks to automatic target listing

Tweaks to automatic target listing

---

aswb/src/com/google/idea/blaze/android/manifest/ManifestParser.java

Document and clean-up ManifestParser.
Added javadoc on the up-to-date-ness of manifests and the possible
long-blocking operation of refreshManifests.

Document and clean-up ManifestParser.

---

base/src/com/google/idea/blaze/base/async/process/ExternalTask.java

Trim logged command strings to 1000 chars.

Trim logged command strings to 1000 chars.

---

base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsCompositeConfigurable.java
base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsConfigurable.java
common/settings/src/com/google/idea/common/settings/SearchableText.java
common/settings/src/com/google/idea/common/settings/SearchableTextHelper.java
java/src/com/google/idea/blaze/java/settings/BlazeJavaUserSettingsConfigurable.java

Rename SearchableOption -> SearchableText.

Rename SearchableOption -> SearchableText.

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java

Further resolve blaze-bin path for tsconfig contents.

Further resolve blaze-bin path for tsconfig contents.

---

base/src/META-INF/blaze-base.xml

Fix bazel plugin XML setup.

---

WORKSPACE

Import Android Studio 3.4.2 (3.4.2.0)

Import Android Studio 3.4.2 (3.4.2.0)

---

base/src/com/google/idea/blaze/base/command/buildresult/RemoteOutputArtifact.java
base/src/com/google/idea/blaze/base/filecache/ArtifactState.java
proto/project_data.proto

Rename serialized state class for remote outputs.

Rename serialized state class for remote outputs.

---

base/src/com/google/idea/blaze/base/dependencies/ExternalFileProjectManagementHelper.java
base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsConfigurable.java
common/settings/src/com/google/idea/common/settings/AutoConfigurable.java
common/settings/src/com/google/idea/common/settings/ConfigurableSetting.java
common/settings/src/com/google/idea/common/settings/Property.java
common/settings/src/com/google/idea/common/settings/SearchableText.java
common/settings/src/com/google/idea/common/settings/SettingComponent.java
common/settings/src/com/google/idea/common/settings/SettingComponentBindings.java
java/src/com/google/idea/blaze/java/settings/BlazeJavaUserSettingsConfigurable.java

Create an AutoConfigurable utility for declarative settings configurables.

Create an AutoConfigurable utility for declarative settings configurables.

---

java/src/com/google/idea/blaze/java/sync/jdeps/JdepsFileReader.java
java/src/com/google/idea/blaze/java/sync/jdeps/JdepsState.java
proto/project_data.proto

Refactor jdeps serialization

---

base/src/com/google/idea/blaze/base/command/buildresult/LocalFileOutputArtifact.java
base/src/com/google/idea/blaze/base/command/buildresult/OutputArtifact.java
base/src/com/google/idea/blaze/base/command/buildresult/RemoteOutputArtifact.java
base/src/com/google/idea/blaze/base/filecache/ArtifactState.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceState.java
base/tests/unittests/com/google/idea/blaze/base/filecache/ArtifactStateTest.java
proto/project_data.proto

Migrate blaze artifact serialization keys for locally-available files.

Migrate blaze artifact serialization keys for locally-available files.

---

base/tests/utils/integration/com/google/idea/blaze/base/BlazeIntegrationTestCase.java

Launch synchronous RefreshSession before heavy test tear-down
Heavy implementations of BlazeIntegrationTestCase (i.e. ASwB's integration tests) use a temporary folder on disk instead of an in-memory file system. This leads to a platform-level race condition where RefreshQueue tries to respond to external file system events for files whose parent directory has already been deleted during test tear-down (https://youtrack.jetbrains.com/issue/IDEA-218773).

Launch synchronous RefreshSession before heavy test tear-down

---

aswb/tests/unittests/com/google/idea/blaze/android/sync/importer/BlazeAndroidWorkspaceImporterTest.java
java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java
java/src/com/google/idea/blaze/java/sync/importer/JavaSourceFilter.java
java/tests/unittests/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporterTest.java
scala/tests/unittests/com/google/idea/blaze/scala/sync/importer/BlazeScalaWorkspaceImporterTest.java

Always index generated jars from java proto library targets in the project.

Always index generated jars from java proto library targets in the project.

---

CHANGELOG

Update changelog for v2019.07.22

Update changelog for v2019.07.22

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java

Do not add "- //bazel-bin/... - //.ijwb/... " and friends into the excluded workspace paths for Bazel projects.
Since these directories don't have build files / targets in them, subtracting them in the final constructed query results in an error:
---
$ bazel query --tool_tag=ijwb:IDEA:community --output=label_kind 'attr("tags", "^((?!manual).)*$", //... - //.ijwb/... -//bazel-bin/...)' -k
ERROR: Skipping '//.ijwb/...': no targets found beneath '.ijwb'
ERROR: Skipping '//bazel-bin/...': no targets found beneath 'bazel-bin'
WARNING: --keep_going specified, ignoring errors.  Results may be inaccurate
test_suite rule //:test
scala_test rule //:test_test_suite_src_test_scala_hello_EndpointSpec.scala
scala_test rule //:test_test_suite_src_test_scala_hello_ConfigurationSpec.scala
scala_binary …

Do not add "- //bazel-bin/... - //.ijwb/... " and friends into the excluded workspace paths for Bazel projects.

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java
base/src/com/google/idea/blaze/base/command/buildresult/OutputArtifactParser.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncBuildResult.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/tests/unittests/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReaderTest.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java

Pass per-target outputs information through from BEP to sync.

Pass per-target outputs information through from BEP to sync.

---

base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java

Actually allow external repo targets in run configurations

Actually allow external repo targets in run configurations

---

base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectAction.java
base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectHelper.java
base/src/com/google/idea/blaze/base/dependencies/ExternalFileProjectManagementHelper.java
base/src/com/google/idea/blaze/base/settings/ui/AddDirectoryToProjectAction.java
base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java
base/src/com/google/idea/blaze/base/sync/projectview/ProjectTargetsHelper.java
base/tests/unittests/com/google/idea/blaze/base/sync/projectview/ProjectTargetsHelperTest.java

Add source/package/directory to project actions: respect the auto-derive targets form directories option.

Add source/package/directory to project actions: respect the auto-derive targets form directories option.

---

WORKSPACE

Import CLion 2019.2

---

base/src/com/google/idea/blaze/base/dependencies/BlazeQueryDirectoryToTargetProvider.java
base/src/com/google/idea/blaze/base/dependencies/DirectoryToTargetProvider.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java

Support calling herb during sync for never-synced git5 / fig-off-citc projects.

Support calling herb during sync for never-synced git5 / fig-off-citc projects.

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/BlazeTypeScriptConfigTest.java

Fix typescript module import path resolve order.

Fix typescript module import path resolve order.

---

build_defs/api_version_txt.py
build_defs/append_optional_xml_elements.py
build_defs/merge_xml.py
build_defs/package_meta_inf_files.py
build_defs/product_build_txt.py
build_defs/stamp_plugin_xml.py
build_defs/zip_plugin_files.py

Adds copyright headers to some shared build_defs files.

Adds copyright headers to some shared build_defs files.

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Drop IJ CE 2019.2 in plugin_api

Drop IJ CE 2019.2 in plugin_api

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Drop IJ UE 2019.2 in plugin_api.

Drop IJ UE 2019.2 in plugin_api.

---

WORKSPACE
intellij_platform_sdk/BUILD
sdkcompat/BUILD
third_party/go/BUILD
third_party/javascript/BUILD
third_party/python/BUILD
third_party/scala/BUILD

Drop in 2019.2 versions of plugins

Drop in 2019.2 versions of plugins

---

CHANGELOG

Changelog for v2019.08.05

---

base/src/com/google/idea/blaze/base/run/producers/PendingAsyncTestContext.java
base/src/com/google/idea/blaze/base/run/producers/PendingWebTestContext.java

Pending run config: derive project under a read lock.

Pending run config: derive project under a read lock.

---

golang/src/META-INF/go-contents.xml
golang/src/com/google/idea/blaze/golang/resolve/BlazeGoImportResolver.java
golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java
golang/src/com/google/idea/blaze/golang/resolve/GoFilesCache.java

Add a cache for go files contained in go packages.

Add a cache for go files contained in go packages.

---

java/src/com/google/idea/blaze/java/run/BlazeCompilerManager.java
scala/src/com/google/idea/blaze/scala/run/Specs2Utils.java
sdkcompat/v183/com/google/idea/sdkcompat/openapi/FileTypeManagerImplAdapter.java
sdkcompat/v183/com/google/idea/sdkcompat/openapi/HeadlessSaveAndSyncHandler.java
sdkcompat/v183/com/google/idea/sdkcompat/scala/TestConfigurationUtilCompat.java
sdkcompat/v183/com/google/idea/sdkcompat/vcs/BinaryMergeRequestImplAdapter.java
sdkcompat/v183/com/google/idea/sdkcompat/vcs/GeneralVcsCompatHelper.java
sdkcompat/v183/com/google/idea/sdkcompat/vcs/MergeSessionExAdapter.java
sdkcompat/v183/com/google/idea/sdkcompat/vcs/VcsChangesLazilyParsedDetailsAdapter.java
sdkcompat/v191/com/google/idea/sdkcompat/openapi/FileTypeManagerImplAdapter.java
sdkcompat/v191/com/google/idea/sdkcompat/openapi/HeadlessSaveAndSyncHandler.java
sdkcompat/v191/com/google/idea/sdkcompat/scala/TestConfigurationUtilCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/vcs/BinaryMergeRequestImplAdapter.java
sdkcompat/v191/com/google/idea/sdkcompat/vcs/GeneralVcsCompatHelper.java
sdkcompat/v191/com/google/idea/sdkcompat/vcs/MergeSessionExAdapter.java
sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsChangesLazilyParsedDetailsAdapter.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/java/CompatCompilerManagerImpl.java
sdkcompat/v192/com/google/idea/sdkcompat/openapi/FileTypeManagerImplAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/openapi/HeadlessSaveAndSyncHandler.java
sdkcompat/v192/com/google/idea/sdkcompat/scala/TestConfigurationUtilCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/BinaryMergeRequestImplAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/ChangeListManagerAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/GeneralVcsCompatHelper.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/MergeSessionExAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsChangesLazilyParsedDetailsAdapter.java

Some 2019.2 compatibility fixes.
First round of fixes, specific to IntelliJ.

Some 2019.2 compatibility fixes.

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptAdditionalLibraryRootsProvider.java

Remove in-project files from TypeScript synthetic library.

Remove in-project files from TypeScript synthetic library.

---

base/BUILD
base/tests/utils/integration/com/google/idea/blaze/base/run/producer/BlazeRunConfigurationProducerTestCase.java
sdkcompat/v183/com/google/idea/sdkcompat/openapi/HeadlessDataManagerAdapter.java
sdkcompat/v191/com/google/idea/sdkcompat/openapi/HeadlessDataManagerAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/openapi/HeadlessDataManagerAdapter.java

More 2019.2 plugin API compatibility fixes.

More 2019.2 plugin API compatibility fixes.

---

sdkcompat/v192/com/google/idea/sdkcompat/cidr/OCWorkspaceFileMapperCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/OCWorkspaceModifiableModelAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/WorkspaceFileMapper.java
testing/cidr/v192/com/google/idea/testing/cidr/StubOCCompilerSettings.java
testing/cidr/v192/com/google/idea/testing/cidr/StubOCResolveConfiguration.java
testing/cidr/v192/com/google/idea/testing/cidr/StubOCWorkspace.java

Adapt to changes that remove WorkspaceFileMapper in 192

Adapt to changes that remove WorkspaceFileMapper in 192

---

sdkcompat/v192/com/google/idea/sdkcompat/cidr/OCWorkspaceModifiableModelAdapter.java

Adapt to upstream API change in OCWorkspaceImplUtilKt.collectCompilerSettingsAsync

Adapt to upstream API change in OCWorkspaceImplUtilKt.collectCompilerSettingsAsync

---

base/BUILD
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/libraries/BlazeExternalLibraryProvider.java
base/src/com/google/idea/blaze/base/sync/libraries/BlazeExternalSyntheticLibrary.java
base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java
base/tests/unittests/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManagerTest.java
golang/src/com/google/idea/blaze/golang/sync/BlazeGoAdditionalLibraryRootsProvider.java
javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptAdditionalLibraryRootsProvider.java
javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptResolveScopeProvider.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptAdditionalLibraryRootsProvider.java
sdkcompat/v183/com/google/idea/sdkcompat/openapi/VFileCreateEventCompat.java
sdkcompat/v183/com/google/idea/sdkcompat/openapi/VirtualFileManagerCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/openapi/VFileCreateEventCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/openapi/VirtualFileManagerCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/openapi/VFileCreateEventCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/openapi/VirtualFileManagerCompat.java

Update external library files in response to VFS events.

Update external library files in response to VFS events.

---

aswb/tests/integrationtests/com/google/idea/blaze/android/cppimpl/debug/BlazeAndroidNativeDebuggingTest.java
cpp/tests/integrationtests/com/google/idea/blaze/cpp/BlazeCppResolvingTestCase.java
sdkcompat/v183/com/google/idea/sdkcompat/cidr/CidrDebuggerLanguageSupportManagerCompat.java
sdkcompat/v183/com/google/idea/sdkcompat/cidr/IncludedHeadersRootCompat.java
sdkcompat/v183/com/google/idea/sdkcompat/cidr/OCChangeUtilCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/cidr/CidrDebuggerLanguageSupportManagerCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/cidr/IncludedHeadersRootCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/cidr/OCChangeUtilCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/CidrDebuggerLanguageSupportManagerCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/IncludedHeadersRootCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/OCChangeUtilCompat.java

Introduce a compat layer for OCChangeUtil.addHandlingMacros

Introduce a compat layer for OCChangeUtil.addHandlingMacros

---

WORKSPACE
base/src/com/google/idea/blaze/base/lang/buildfile/search/ExcludeBuildFilesScope.java
intellij_platform_sdk/BUILD.idea192
intellij_platform_sdk/BUILD.ue192
intellij_platform_sdk/build_defs.bzl
java/tests/integrationtests/com/google/idea/blaze/java/sync/projectstructure/JavaSourceFolderProviderTest.java

Move intellij beta branch to 2019.2

Move intellij beta branch to 2019.2

---

aspect/fast_build_info.bzl
java/src/com/google/idea/blaze/java/fastbuild/FastBuildBlazeData.java
java/src/com/google/idea/blaze/java/run/fastbuild/BazelFastBuildTestEnvironmentCreator.java
java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestEnvironmentCreator.java
proto/fast_build_info.proto

Fast run/debug: fix handling of targets with swigdeps disabled

Fast run/debug: fix handling of targets with swigdeps disabled

---

base/src/com/google/idea/blaze/base/sync/projectview/ProjectTargetsHelper.java
base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java
base/src/com/google/idea/blaze/base/sync/sharding/WildcardTargetExpander.java

Some fixes to sync sharding.

---

WORKSPACE

Update rules_scala version.

---

WORKSPACE

Update the 2019.1 Go plugin.

---

base/src/com/google/idea/blaze/base/sync/BlazeSyncPlugin.java
base/src/com/google/idea/blaze/base/sync/projectview/LanguageSupport.java
python/src/com/google/idea/blaze/python/sync/AlwaysPresentPythonSyncPlugin.java
python/src/com/google/idea/blaze/python/sync/BlazePythonSyncPlugin.java

Don't unconditionally enable python language support.

Don't unconditionally enable python language support.

---

base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java

Auto-deriving targets from directories: log the raw and filtered target count

Auto-deriving targets from directories: log the raw and filtered target count

---

WORKSPACE

Import Android Studio 3.5 RC 3 (3.5.0.20)

Import Android Studio 3.5 RC 3 (3.5.0.20)

---

skylark/src/com/google/idea/blaze/skylark/debugger/SkylarkDebuggingUtils.java

Turn on starlark debugging support for bazel users

Turn on starlark debugging support for bazel users

---

aspect/intellij_info_impl.bzl

Fix more instances of --incompatible_depset_is_not_iterable=false

Fix more instances of --incompatible_depset_is_not_iterable=false

---

aswb/BUILD
golang/BUILD
javascript/BUILD
testing/src/com/google/idea/testing/BlazeTestSystemPropertiesRule.java
testing/test_defs.bzl

Set the platform prefix based on the plugin_api

Set the platform prefix based on the plugin_api

---

aswb/sdkcompat/as34/com/android/tools/idea/projectsystem/ScopeType.java
aswb/sdkcompat/as35/com/android/tools/idea/projectsystem/ScopeType.java
aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystem.java
aswb/src/com/google/idea/blaze/android/projectsystem/BlazeProjectSystemSyncManager.java

Update IntelliJ plugin SDKs to 3.6 Canary 5 (3.6.0.5)

Update IntelliJ plugin SDKs to 3.6 Canary 5 (3.6.0.5)

---

testing/src/com/google/idea/testing/DisablePluginsTestRule.java

Simplify how plugins are disabled in newer API levels

Simplify how plugins are disabled in newer API levels

---

CHANGELOG

Changelog for v2019.08.19

---

plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginConfiguration.java

Intellij 192 compatibility changes

Intellij 192 compatibility changes

---

java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageProjectViewClassDecorator.java
sdkcompat/v183/BUILD
sdkcompat/v183/com/google/idea/sdkcompat/openapi/AbstractCoverageProjectViewNodeDecoratorCompat.java
sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/openapi/AbstractCoverageProjectViewNodeDecoratorCompat.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/openapi/AbstractCoverageProjectViewNodeDecoratorCompat.java

Fix 192 API regression

---

base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java

BEP parsing: handle NamedSetOfFiles event appearing after a TargetCompleted event referencing it.

BEP parsing: handle NamedSetOfFiles event appearing after a TargetCompleted event referencing it.

---

base/src/com/google/idea/blaze/base/logging/utils/SyncStats.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Log target map size during sync

Log target map size during sync

---

WORKSPACE

Import Android Studio 3.5 (3.5.0.21)

Import Android Studio 3.5 (3.5.0.21)

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/libraries/BlazeExternalSyntheticLibrary.java
base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java
base/tests/unittests/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManagerTest.java

Fix ExternalLibraryManager.

---

WORKSPACE

Import CLion 2019.2.1

---

sdkcompat/v191/com/google/idea/sdkcompat/clion/SymbolTableProviderCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/cidr/OCWorkspaceModifiableModelAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/clion/CPPToolSetWithHomeAndSeparators.java
sdkcompat/v192/com/google/idea/sdkcompat/clion/SymbolTableProviderCompat.java

CLion 2019.2 compat changes

---

aspect/intellij_info_impl.bzl
aspect/java_classpath.bzl

Use JavaInfo instead of .java provider in intellij plugin.

Use JavaInfo instead of .java provider in intellij plugin.

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystem.java

Add null check when converting library to ExternalLibrary

Add null check when converting library to ExternalLibrary

---

intellij_platform_sdk/build_defs.bzl

Switch AS stable to point to 3.5

Switch AS stable to point to 3.5

---

aswb/sdkcompat/as34/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryNormalBuildRunContext.java
aswb/sdkcompat/as34/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeAndroidBinaryMobileInstallRunContext.java
aswb/sdkcompat/as35/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryNormalBuildRunContext.java
aswb/sdkcompat/as35/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeAndroidBinaryMobileInstallRunContext.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryNormalBuildRunContext.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeAndroidBinaryMobileInstallRunContext.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryApplicationLaunchTaskProvider.java

Remove unused project argument.

Remove unused project argument.

---

base/src/com/google/idea/blaze/base/run/producers/BlazeBuildFileRunConfigurationProducer.java

Fix java_binary targets not appearing debuggable on first right-click.

Fix java_binary targets not appearing debuggable on first right-click.

---

CHANGELOG

Changelog for  v2019.09.03

---

base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java

Add blaze-invoking integration tests for sharded syncs.

Add blaze-invoking integration tests for sharded syncs.

---

aswb/tests/integrationtests/com/google/idea/blaze/android/AswbGotoDeclarationTest.java

Update caret location in AswbGotoDeclararationTest.java

Update caret location in AswbGotoDeclararationTest.java

---

aswb/BUILD

Remove unused deps

---

aswb/sdkcompat/as35/com/google/idea/blaze/android/run/runner/BlazeAndroidRunContext.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/runner/BlazeAndroidRunContext.java
aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryNormalBuildRunContextBase.java
aswb/src/com/google/idea/blaze/android/run/binary/mobileinstall/BlazeAndroidBinaryMobileInstallRunContextBase.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeAndroidRunConfigurationRunner.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunContextBase.java

Remove BlazeAndroidRunContext#augmentEnvironment

Remove BlazeAndroidRunContext#augmentEnvironment

---

base/src/com/google/idea/blaze/base/async/executor/ProgressiveTaskWithProgressIndicator.java

Fix dangling progress indicator.

Fix dangling progress indicator.

---

python/src/META-INF/python-contents.xml
python/src/com/google/idea/blaze/python/sdk/FallbackPythonSdkSuggester.java

Initialize system python interpreter information off the EDT, on opening the first blaze project.

Initialize system python interpreter information off the EDT, on opening the first blaze project.

---

golang/src/com/google/idea/blaze/golang/run/producers/GoBinaryContextProvider.java
golang/tests/integrationtests/com/google/idea/blaze/golang/run/producers/GoBinaryContextProviderTest.java

Allow running go binaries with main file in library dependencies.

Allow running go binaries with main file in library dependencies.

---

base/tests/utils/unit/com/google/idea/blaze/base/scope/ErrorCollector.java
javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptSyncPlugin.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypescriptSyncPlugin.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/JavascriptSyncTest.java

Improve JS/TS error messages during sync.

Improve JS/TS error messages during sync.

---

aswb/tests/unittests/com/google/idea/blaze/android/projectsystem/BlazeModuleSystemTest.java

Update IntelliJ plugin SDKs to 3.6 Canary 10 (3.6.0.10)

Update IntelliJ plugin SDKs to 3.6 Canary 10 (3.6.0.10)

---

sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/platform/LighterASTCompat.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/platform/LighterASTCompat.java

SDK compat for internal change.

SDK compat for internal change.

---

CHANGELOG

Changelog for v2019.09.16

---

cpp/src/com/google/idea/blaze/cpp/BlazeCSyncPlugin.java
python/src/com/google/idea/blaze/python/sync/BlazePythonSyncPlugin.java

Force refresh the exec root during sync, if necessary.

Force refresh the exec root during sync, if necessary.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/run/producers/VirtualFileTestContextProvider.java

Google3 view: support running/debugging tests *inside* the project.

Google3 view: support running/debugging tests *inside* the project.

---

aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryRunConfigurationHandler.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationHandler.java

Add DEPLOYS_TO_LOCAL_DEVICE user data key to deployable run configs.

Add DEPLOYS_TO_LOCAL_DEVICE user data key to deployable run configs.

---

python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java

Remove kill signal customization from python config runner.

Remove kill signal customization from python config runner.

---

testing/src/com/google/idea/testing/AbstractIntegrationTestCase.java

Move AbstractIntegrationTestCase to com.google.idea.testing.

Move AbstractIntegrationTestCase to com.google.idea.testing.

---

build_defs/build_defs.bzl

Simplify release rules for the other plugins

Simplify release rules for the other plugins

---

intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Drop in mac release for IJ CE 2019.1

Drop in mac release for IJ CE 2019.1

---

intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Drop in mac release for IJ UE 2019.1

Drop in mac release for IJ UE 2019.1

---

intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Drop in mac release for CLion 2019.1

Drop in mac release for CLion 2019.1

---

base/src/com/google/idea/blaze/base/logging/utils/SyncStats.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java

Log uptime, number of libraries, and post Blaze sync time.

Log uptime, number of libraries, and post Blaze sync time.

---

WORKSPACE

Update IJ CE latest to 2019.1.4

Update IJ CE latest to 2019.1.4

---

WORKSPACE

Update IJ UE stable to 2019.1.4

Update IJ UE stable to 2019.1.4

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypescriptGotoDeclarationHandler.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/OldBlazeTypescriptGotoDeclarationHandlerTest.java

Fix .d.ts to .jspb.js navigation after source comment change.

Fix .d.ts to .jspb.js navigation after source comment change.

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypescriptGotoDeclarationHandler.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/BlazeTypescriptGotoDeclarationHandlerTest.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/OldBlazeTypescriptGotoDeclarationHandlerTest.java

Fix typescript navigation tests for 2019.2 update.

Fix typescript navigation tests for 2019.2 update.

---

CHANGELOG

Update changelog for 2019.09.30

Update changelog for 2019.09.30

---

base/src/com/google/idea/blaze/base/settings/ui/AddDirectoryToProjectAction.java

Add directory to project: also partially sync if we're deriving targets from directories.

Add directory to project: also partially sync if we're deriving targets from directories.

---

base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java

Support sharding sync when deriving targets from directories.

Support sharding sync when deriving targets from directories.

---

base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java

Canonicalize run configuration targets before passing on to blaze.

Canonicalize run configuration targets before passing on to blaze.

---

common/experiments/src/com/google/idea/common/experiments/ExperimentService.java
common/experiments/src/com/google/idea/common/experiments/ExperimentServiceImpl.java
common/experiments/src/com/google/idea/common/experiments/FileExperimentLoader.java
common/experiments/tests/utils/unit/com/google/idea/common/experiments/MockExperimentService.java

Update cached experiments more quickly when experiment file changes.

Update cached experiments more quickly when experiment file changes.

---

java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestEnvironmentCreator.java

Fast run/debug: respect custom JVM args

Fast run/debug: respect custom JVM args

---

testing/test_defs.bzl

Exempt intellij_integration_test_suite from thread sanitizer tests.

Exempt intellij_integration_test_suite from thread sanitizer tests.

---

base/src/com/google/idea/blaze/base/sync/BlazeSyncPlugin.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
python/src/com/google/idea/blaze/python/sdk/FallbackPythonSdkSuggester.java
python/src/com/google/idea/blaze/python/sync/BlazePythonSyncPlugin.java
python/src/com/google/idea/blaze/python/sync/PySdkSuggester.java

BlazeSyncPlugin: Break SDK updates out of Transaction update

BlazeSyncPlugin: Break SDK updates out of Transaction update

---

base/src/com/google/idea/blaze/base/run/producers/RunConfigurationContext.java
base/src/com/google/idea/blaze/base/run/state/BlazeCommandRunConfigurationCommonState.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildRunProfileState.java

Unquote test filter before using it as an environment variable.

Unquote test filter before using it as an environment variable.

---

WORKSPACE

Import Android Studio 3.5.1 (3.5.1.0)

Import Android Studio 3.5.1 (3.5.1.0)

---

aswb/BUILD

Remove duplicate src entries in BUILD file.

Remove duplicate src entries in BUILD file.

---

base/src/com/google/idea/blaze/base/run/exporter/RunConfigurationSerializer.java
base/tests/integrationtests/com/google/idea/blaze/base/run/exporter/RunConfigurationSerializerTest.java

Don't clone "Keep In Sync" run config option.
Currently when a new run configuration is created based on a template,
every option is duplicated, including the "Keep In Sync" option. This
option should NOT be duplicated because a run config created from a
template will never have a external backing XML.

Don't clone "Keep In Sync" run config option.

---

golang/src/com/google/idea/blaze/golang/run/producers/GoTestContextProvider.java
golang/src/com/google/idea/blaze/golang/run/smrunner/BlazeGoTestEventsHandler.java
golang/tests/integrationtests/com/google/idea/blaze/golang/run/producers/BlazeGoTestConfigurationProducerTest.java

Run go tests from selected file only.

Run go tests from selected file only.

---

aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationCollector.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationHandler.java

Log executor ID in BlazeAndroidTestRunConfigurationCollector

Log executor ID in BlazeAndroidTestRunConfigurationCollector

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfigServiceImpl.java

Fix typescript service not restarting when tsconfig changes.

Fix typescript service not restarting when tsconfig changes.

---

base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java
base/src/com/google/idea/blaze/base/sync/sharding/SuggestBuildShardingNotification.java

Shard automatically to keep arg length below ARG_MAX.

Shard automatically to keep arg length below ARG_MAX.

---

javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/typescript/AddTsConfigNotificationProvider.java

Add editor notification if tsconfig for the current file is not in the project view.

Add editor notification if tsconfig for the current file is not in the project view.

---

base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java

Automatically shard builds on rabbit.

Automatically shard builds on rabbit.

---

aswb/src/com/google/idea/blaze/android/projectsystem/BlazeProjectSystemSyncManager.java
aswb/tests/integrationtests/com/google/idea/blaze/android/sync/AndroidSyncTest.java
aswb/tests/utils/integration/com/google/idea/blaze/android/BlazeAndroidIntegrationTestCase.java
base/src/com/google/idea/blaze/base/lang/AdditionalLanguagesHelper.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncManager.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncParams.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncStartupActivity.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncHandler.java
base/src/com/google/idea/blaze/base/sync/autosync/BuildFileAutoSyncProvider.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectViewAutoSyncProvider.java
base/src/com/google/idea/blaze/base/sync/autosync/ProtoAutoSyncProvider.java
base/tests/unittests/com/google/idea/blaze/base/sync/BlazeSyncManagerTest.java
java/src/com/google/idea/blaze/java/libraries/AddLibraryTargetDirectoryToProjectViewAction.java
java/tests/integrationtests/com/google/idea/blaze/java/sync/JavaSyncTest.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/JavascriptSyncTest.java
kotlin/tests/integrationtests/com/google/idea/blaze/kotlin/KotlinSyncTest.java
plugin_dev/tests/integrationtests/com/google/idea/blaze/plugin/sync/PluginDevSyncTest.java
scala/tests/integrationtests/com/google/idea/blaze/scala/sync/ScalaSyncTest.java

Refactor BlazeSyncParams to use AutoValue.

Refactor BlazeSyncParams to use AutoValue.

---

base/src/com/google/idea/blaze/base/sync/BlazeBuildParams.java

Parallelize remote syncs by default.

Parallelize remote syncs by default.

---

base/src/com/google/idea/blaze/base/logging/utils/BuildPhaseSyncStats.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java

Sync logging: handle parallel blaze builds

Sync logging: handle parallel blaze builds

---

CHANGELOG

Update changelog for 2019.10.14.

Update changelog for 2019.10.14.

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManager.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManagerImpl.java
base/src/com/google/idea/blaze/base/sync/projectview/TargetExpressionList.java
base/tests/unittests/com/google/idea/blaze/base/sync/projectview/TargetExpressionListTest.java

Track currently-syncing targets.

Track currently-syncing targets.

---

base/src/com/google/idea/blaze/base/dependencies/AddSourceToProjectAction.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManager.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManagerImpl.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusContributor.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusEditorTabColorProvider.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusEditorTabTitleProvider.java
base/src/com/google/idea/blaze/base/syncstatus/SyncStatusNodeDecorator.java
clwb/src/com/google/idea/blaze/clwb/run/test/GoogleTestLocation.java

Include per-file 'syncing' indicator in editor tabs / project view.

Include per-file 'syncing' indicator in editor tabs / project view.

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
third_party/go/BUILD
third_party/javascript/BUILD
third_party/python/BUILD
third_party/scala/BUILD

Add plugin_api files for intellij_ce_2019_3

Add plugin_api files for intellij_ce_2019_3

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
third_party/go/BUILD
third_party/javascript/BUILD
third_party/python/BUILD
third_party/scala/BUILD

Add plugin_api for intellij-ue-canary build 193.4386.10 / 2019.3.0

Add plugin_api for intellij-ue-canary build 193.4386.10 / 2019.3.0

---

base/src/com/google/idea/blaze/base/ideinfo/TargetIdeInfo.java

Reduce sync time precision to milliseconds.

Reduce sync time precision to milliseconds.

---

base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java

Fix NoSuchElementException from BlazeProblemsViewPanel.

Fix NoSuchElementException from BlazeProblemsViewPanel.

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Switch ASwB beta to point to 3.6

Switch ASwB beta to point to 3.6

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl

Automated g4 rollback of changelist 276073318.
*** Reason for rollback ***
cause bazel failure
*** Original change description ***

Automated g4 rollback of changelist 276073318.

---

testing/test_defs.bzl

intellij_integration_test_suite: allow tags in kwargs

intellij_integration_test_suite: allow tags in kwargs

---

common/experiments/src/com/google/idea/common/experiments/InternalDevFlag.java

Restrict visibility of developer check.

Restrict visibility of developer check.

---

base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncListener.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManager.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManagerImpl.java

Track project sync status

---

base/src/com/google/idea/blaze/base/model/primitives/Kind.java
base/src/com/google/idea/blaze/base/run/producers/PendingWebTestContext.java
base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestEventsHandler.java
dart/src/com/google/idea/blaze/dart/DartBlazeRules.java
golang/src/com/google/idea/blaze/golang/GoBlazeRules.java
golang/src/com/google/idea/blaze/golang/run/smrunner/BlazeGoTestLocator.java
java/src/com/google/idea/blaze/java/JavaBlazeRules.java
javascript/src/com/google/idea/blaze/javascript/JavascriptBlazeRules.java
python/src/com/google/idea/blaze/python/PythonBlazeRules.java

Fix web test context and handling for per-language web_tests.

Fix web test context and handling for per-language web_tests.

---

python/src/com/google/idea/blaze/python/run/producers/PyTestContextProvider.java
python/tests/integrationtests/com/google/idea/blaze/python/run/producers/BlazePyTestConfigurationProducerTest.java

Support PEP-8 underscore style for test naming

Support PEP-8 underscore style for test naming

---

golang/src/com/google/idea/blaze/golang/run/producers/GoTestContextProvider.java
golang/src/com/google/idea/blaze/golang/run/smrunner/BlazeGoTestEventsHandler.java
golang/tests/integrationtests/com/google/idea/blaze/golang/run/producers/BlazeGoTestConfigurationProducerTest.java

Automated g4 rollback of changelist 273528428.
*** Reason for rollback ***
b/143182633
*** Original change description ***
Run go tests from selected file only.

Automated g4 rollback of changelist 273528428.

---

python/src/com/google/idea/blaze/python/run/producers/PyTestContextProvider.java
python/tests/integrationtests/com/google/idea/blaze/python/run/producers/BlazePyTestConfigurationProducerTest.java

Support generating run configs for tests using a parameterized decorator with a literal list of args

Support generating run configs for tests using a parameterized decorator with a literal list of args

---

CHANGELOG

Update changelog for 2019.10.28 release.

Update changelog for 2019.10.28 release.

---

base/src/com/google/idea/blaze/base/actions/BlazeBuildService.java
base/src/com/google/idea/blaze/base/console/BlazeConsoleView.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncManager.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/SyncProjectTargetsHelper.java

Improve sync cancellation handling.

Improve sync cancellation handling.

---

base/src/com/google/idea/blaze/base/run/smrunner/BlazeWebTestEventsHandler.java
golang/src/com/google/idea/blaze/golang/run/smrunner/BlazeGoTestEventsHandler.java
golang/tests/integrationtests/com/google/idea/blaze/golang/run/smrunner/BlazeWebGoTestEventsHandlerTest.java
java/src/com/google/idea/blaze/java/sync/source/JavaLikeLanguage.java
java/tests/integrationtests/com/google/idea/blaze/java/run/BlazeWebJavaTestEventsHandlerTest.java
javascript/src/com/google/idea/blaze/javascript/run/producers/BlazeJavaScriptTestRunLineMarkerContributor.java
javascript/src/com/google/idea/blaze/javascript/run/smrunner/BlazeJavascriptTestLocator.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/producers/OldJavascriptTestContextProviderTest.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/smrunner/BlazeWebJavascriptTestEventsHandlerTest.java

Move *_web_test handling to per-language handlers.

Move *_web_test handling to per-language handlers.

---

aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryRunConfigurationState.java

Update split apk deprecation comment.

Update split apk deprecation comment.

---

intellij_platform_sdk/BUILD

Import Android Studio 4.0 Canary 1 (4.0.0.1)

Import Android Studio 4.0 Canary 1 (4.0.0.1)

---

base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java

Fix NoSuchElementException from BlazeProblemsViewPanel once and for all.

Fix NoSuchElementException from BlazeProblemsViewPanel once and for all.

---

base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManagerImpl.java

Trigger a project view sync status update for failed/cancelled syncs.

Trigger a project view sync status update for failed/cancelled syncs.

---

base/src/com/google/idea/blaze/base/actions/BlazeBuildService.java

Fix NPE running 'compile project' action

Fix NPE running 'compile project' action

---

java/src/com/google/idea/blaze/java/libraries/JarCache.java

Fix jar cache size logging.

---

aspect/intellij_info_impl.bzl
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/Direct.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/Distant.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/Indirect.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javalibrary/JavaLibraryTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javatest/JavaTestTest.java

Aspect: expose additional output groups containing a trimmed set of outputs.

Aspect: expose additional output groups containing a trimmed set of outputs.

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTest.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategy.java
base/tests/unittests/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyTest.java

Enable output graph trimming when deriving targets from directories

Enable output graph trimming when deriving targets from directories

---

base/src/com/google/idea/blaze/base/model/BlazeVersionData.java
base/src/com/google/idea/blaze/base/sync/data/BlazeProjectDataManagerImpl.java

Log project data size + CL when saving project.

Log project data size + CL when saving project.

---

aspect/intellij_info_impl.bzl
proto/intellij_ide_info.proto

Do not keep file level information in Android target info

Do not keep file level information in Android target info

---

WORKSPACE

Import Android Studio 3.6 Beta 3 (3.6.0.15)

Import Android Studio 3.6 Beta 3 (3.6.0.15)

---

aswb/src/com/google/idea/blaze/android/sync/BlazeAndroidJavaSyncAugmenter.java
aswb/src/com/google/idea/blaze/android/sync/BlazeAndroidLibrarySource.java
aswb/src/com/google/idea/blaze/android/sync/importer/BlazeImportUtil.java
aswb/src/com/google/idea/blaze/android/sync/model/BlazeAndroidImportResult.java
ijwb/src/com/google/idea/blaze/ijwb/android/BlazeAndroidLiteJavaSyncAugmenter.java
ijwb/src/com/google/idea/blaze/ijwb/android/BlazeAndroidLiteSyncPlugin.java
java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java
java/src/com/google/idea/blaze/java/sync/model/BlazeJarLibrary.java
java/tests/unittests/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporterTest.java
kotlin/src/com/google/idea/blaze/kotlin/sync/BlazeKotlinSyncPlugin.java
kotlin/src/com/google/idea/blaze/kotlin/sync/importer/KotlinSyncAugmenter.java
proto/project_data.proto
scala/src/com/google/idea/blaze/scala/sync/importer/BlazeScalaWorkspaceImporter.java

Add the target information building each JAR file in BlazeJarLibrary.

Add the target information building each JAR file in BlazeJarLibrary.

---

ijwb/tests/integrationtests/com/google/idea/blaze/ijwb/prefetch/IntelliJBazelPrefetchFileSourceTest.java
testing/src/com/google/idea/testing/BlazeTestSystemPropertiesRule.java

Add IntelliJ UE-specific prefetch file source test.

Add IntelliJ UE-specific prefetch file source test.

---

aswb/sdkcompat/as35/com/google/idea/blaze/android/sync/projectstructure/AndroidFacetModuleCustomizerCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/sync/projectstructure/AndroidFacetModuleCustomizerCompat.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/npw/project/BlazeAndroidModuleTemplate.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/run/test/StockAndroidTestLaunchTask.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/sync/projectstructure/AndroidFacetModuleCustomizerCompat.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/sync/projectstructure/BlazeAndroidProjectStructureSyncerCompat.java
aswb/src/com/google/idea/blaze/android/sync/projectstructure/AndroidFacetModuleCustomizer.java

Import Android Studio 4.0 Canary 2 (4.0.0.2)

Import Android Studio 4.0 Canary 2 (4.0.0.2)

---

WORKSPACE

import CLion 2019.2.5

---

aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTest.java
base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterface.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategy.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java
base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyProvider.java
base/tests/unittests/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyTest.java
base/tests/utils/integration/com/google/idea/blaze/base/sync/BlazeSyncIntegrationTestCase.java
java/src/com/google/idea/blaze/java/run/hotswap/JavaClasspathAspectStrategy.java

Aspect output trimming: restrict to users with the appropriate aspect.

Aspect output trimming: restrict to users with the appropriate aspect.

---

base/src/com/google/idea/blaze/base/sync/autosync/BuildFileAutoSyncProvider.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectViewAutoSyncProvider.java
base/src/com/google/idea/blaze/base/sync/autosync/ProtoAutoSyncProvider.java

Fix sync origin logging bug

---

base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncHandler.java
base/src/com/google/idea/blaze/base/sync/autosync/PendingChangesHandler.java

Auto-sync: increase time to wait before syncing

Auto-sync: increase time to wait before syncing

---

javascript/BUILD
scala/BUILD

Sort load arguments in BUILD files

Sort load arguments in BUILD files

---

base/src/com/google/idea/blaze/base/sync/BlazeSyncParams.java
base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncHandler.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManager.java
base/src/com/google/idea/blaze/base/sync/autosync/ProjectTargetManagerImpl.java
base/src/com/google/idea/blaze/base/sync/projectview/TargetExpressionList.java

Auto-sync: ignore currently-syncing targets.

Auto-sync: ignore currently-syncing targets.

---

golang/src/com/google/idea/blaze/golang/run/BlazeDlvPositionConverter.java

Fix dlv position converter.
We shouldn't have used a BiMap because the two directions are
different.
For remote to local, we want to keep a normalized remote path to local
file map, so we can convert different remote paths that normalize
identically to the same local file.
For local to remote, we might *not* get the normalized path as a path
recognized by dlv. In that case, we want to return an arbitrary path
that dlv recognizes and that we have mapped to the input local file.

Fix dlv position converter.

---

base/src/com/google/idea/blaze/base/sync/autosync/AutoSyncHandler.java
base/src/com/google/idea/blaze/base/sync/autosync/PendingChangesHandler.java

Auto-syncing: throttle auto-syncing after all project-wide syncs.

Auto-syncing: throttle auto-syncing after all project-wide syncs.

---

CHANGELOG

Update changelog for 2019.11.11 release.

Update changelog for 2019.11.11 release.

---

base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java

Project sync: retrieve 'syncing remotely' switch consistently during a sync operation.

Project sync: retrieve 'syncing remotely' switch consistently during a sync operation.

---

base/src/com/google/idea/blaze/base/lang/buildfile/validation/LoadStatementAnnotator.java
base/src/com/google/idea/blaze/base/settings/ui/BlazeUserSettingsConfigurable.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/validation/LoadStatementAnnotatorTest.java
skylark/src/com/google/idea/blaze/skylark/debugger/impl/SkylarkLineBreakpointType.java

Rename user-facing references from 'skylark' to 'starlark'

Rename user-facing references from 'skylark' to 'starlark'

---

base/src/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharder.java
base/src/com/google/idea/blaze/base/sync/sharding/BuildBatchingService.java
base/src/com/google/idea/blaze/base/sync/sharding/LexicographicTargetSharder.java
base/tests/unittests/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharderTest.java

Always use the remote batching service when syncing remotely.

Always use the remote batching service when syncing remotely.

---

sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java
sdkcompat/v193/BUILD
sdkcompat/v193/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java
testing/src/com/google/idea/testing/ServiceHelper.java

Move ServiceHelper.replaceComponentInstance to sdkcompat

Move ServiceHelper.replaceComponentInstance to sdkcompat

---

aspect/intellij_info_impl.bzl

Avoid recursively adding depth to depsets in intellij aspect

Avoid recursively adding depth to depsets in intellij aspect

---

aspect/fast_build_info.bzl

Fix iterating directly over depset

Fix iterating directly over depset

---

base/tests/unittests/com/google/idea/blaze/base/sync/BuildTargetFinderTest.java

Register BlazeImportSettingsManager as a project service

Register BlazeImportSettingsManager as a project service

---

aswb/sdkcompat/as35/com/google/idea/blaze/android/run/AndroidPlatformCompat.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/run/AndroidPlatformCompat.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/run/AndroidPlatformCompat.java
aswb/src/com/google/idea/blaze/android/run/BlazeAndroidRunConfigurationValidationUtil.java

Import Android Studio 4.0 Canary 3 (4.0.0.3)

Import Android Studio 4.0 Canary 3 (4.0.0.3)

---

WORKSPACE

Update IJ CE to 2019.2.4

---

WORKSPACE

Update IJ UE to 2019.2.4

---

WORKSPACE

Import ASwB 3.6 Beta 4 to Google3

Import ASwB 3.6 Beta 4 to Google3

---

base/tests/utils/unit/com/google/idea/blaze/base/BlazeTestCase.java
sdkcompat/v191/com/google/idea/sdkcompat/testframework/MockComponentManagerCompat.java
sdkcompat/v191/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/testframework/MockComponentManagerCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/testframework/MockComponentManagerCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/testframework/ServiceHelperCompat.java
testing/src/com/google/idea/testing/ServiceHelper.java

Fix registration of services

---

base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java
base/tests/unittests/com/google/idea/blaze/base/issueparser/BlazeIssueParserTest.java

Add compile error parsing for go/dart/python.

Add compile error parsing for go/dart/python.

---

base/src/com/google/idea/blaze/base/sync/sharding/SuggestBuildShardingNotification.java

Add missing space to notification message.

Add missing space to notification message.

---

kotlin/src/com/google/idea/blaze/kotlin/sync/importer/KotlinSyncAugmenter.java

Point TODO to bug instead of username

Point TODO to bug instead of username

---

base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java

Continue with other parsers if multiline parse failed.

Continue with other parsers if multiline parse failed.

---

base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java
base/tests/unittests/com/google/idea/blaze/base/issueparser/BlazeIssueParserTest.java

Ignore BUILD errors if they're immediately followed by a compile error.

Ignore BUILD errors if they're immediately followed by a compile error.

---

common/formatter/src/com/google/idea/common/formatter/FormatterInstaller.java
sdkcompat/v191/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java

Replace CodeStyleManager as a service instead of a component

Replace CodeStyleManager as a service instead of a component

---

base/tests/utils/integration/com/google/idea/blaze/base/run/producer/BlazeRunConfigurationProducerTestCase.java
testing/testcompat/v192/com/google/idea/sdkcompat/testframework/DataManagerCompat.java
testing/testcompat/v193/com/google/idea/sdkcompat/testframework/DataManagerCompat.java

Fix how DataManager is replaced in tests

Fix how DataManager is replaced in tests

---

WORKSPACE
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.clion193
intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
third_party/javascript/BUILD
third_party/python/BUILD

Import CLion 2019.3 beta

---

WORKSPACE
intellij_platform_sdk/BUILD
third_party/BUILD

Modify bazel plugins to correctly pull in truth8.

Modify bazel plugins to correctly pull in truth8.

---

base/src/com/google/idea/blaze/base/async/process/ExternalTask.java
base/tests/unittests/com/google/idea/blaze/base/async/process/ExternalTaskImplTest.java

Change ExternalTask to explicitly use CUSTOM_PATH_SYSTEM_PROPERTY to lookup commands.

Change ExternalTask to explicitly use CUSTOM_PATH_SYSTEM_PROPERTY to lookup commands.

---

golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackage.java
golang/tests/integrationtests/com/google/idea/blaze/golang/resolve/BlazeGoPackageTest.java

Fix go file processing override.

Fix go file processing override.

---

WORKSPACE
aswb/sdkcompat/as35/com/google/idea/blaze/android/projectsystem/BlazeProjectSystem.java
aswb/sdkcompat/as36/com/google/idea/blaze/android/projectsystem/BlazeProjectSystem.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/npw/project/BlazeAndroidModuleTemplate.java
aswb/sdkcompat/as40/com/google/idea/blaze/android/projectsystem/BlazeProjectSystem.java
aswb/src/com/google/idea/blaze/android/projectsystem/BlazeProjectSystemBase.java
aswb/src/com/google/idea/blaze/android/sync/model/idea/BlazeAndroidModel.java
intellij_platform_sdk/BUILD.android_studio40

Import ASwB canary 4

---

javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptAdditionalLibraryRootsProvider.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfigServiceImpl.java
javascript/src/com/google/idea/blaze/typescript/DelegatingTypeScriptConfigService.java
javascript/tests/integrationtests/com/google/idea/blaze/typescript/BlazeTypeScriptConfigTest.java

Update before getting files from tsconfig.
Currently, tsconfig only updates after sync has finished, but by that time we
would have already gotten and cached an empty list of files from the tsconfig
for prefetching and the external library.

Update before getting files from tsconfig.

---

aspect/intellij_info_impl.bzl
aspect/testing/rules/src/com/google/idea/blaze/aspect/IntellijAspectTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl/JavaProtoLibraryTest.java

Forward deps from proto_library shim targets.

Forward deps from proto_library shim targets.

---

base/src/com/google/idea/blaze/base/prefetch/PrefetchProjectInitializer.java

During initial prefetching, load project data off the EDT

During initial prefetching, load project data off the EDT

---

base/src/com/google/idea/blaze/base/lang/buildfile/references/BuildReferenceManager.java
base/src/com/google/idea/blaze/base/sync/workspace/WorkspaceHelper.java

Fix some common blaze plugin freezes related to file system operations.

Fix some common blaze plugin freezes related to file system operations.

---

sdkcompat/v193/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java

Replace bug with #api reminder.

Replace bug with #api reminder.

---

base/tests/integrationtests/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManagerTest.java

Refactor ExternalLibraryManagerTest into integration test.

Refactor ExternalLibraryManagerTest into integration test.

---

WORKSPACE
intellij_platform_sdk/BUILD.clion193
intellij_platform_sdk/BUILD.idea193
intellij_platform_sdk/BUILD.ue193

Add 'failureaccess' dependency required by Guava 27

Add 'failureaccess' dependency required by Guava 27

---

CHANGELOG

Update changelog for 2019.12.02 release.

Update changelog for 2019.12.02 release.

---

aswb/src/com/google/idea/blaze/android/manifest/ParsedManifestService.java
aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java

Invalidate one manifest at a time in ParsedManifestService.

Invalidate one manifest at a time in ParsedManifestService.

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/AbstractVcsAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/AbstractVcsAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/AbstractVcsAdapter.java

sdkcompat: AbstractVcs drops generic parameter

sdkcompat: AbstractVcs drops generic parameter

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java

Suppress wildcard entries for typescript import.

Suppress wildcard entries for typescript import.

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderBaseAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderBaseAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderBaseAdapter.java

compat: Compatibility shims for VCS API

compat: Compatibility shims for VCS API

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsExecutablePathSelectorAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsExecutablePathSelectorAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsExecutablePathSelectorAdapter.java

compat: VcsExecutablePathSelector constructor parameter change

compat: VcsExecutablePathSelector constructor parameter change

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/AbstractRepositoryManagerAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/AbstractRepositoryManagerAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/AbstractRepositoryManagerAdapter.java

compat: AbstractRepositoryManager constructor changed

compat: AbstractRepositoryManager constructor changed

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java

compat: VcsVFSListener changes to do with deleting files

compat: VcsVFSListener changes to do with deleting files

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/ChangesListViewCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/ChangesListViewCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/ChangesListViewCompat.java

compat: Change to DataKey provided by ChangesListView

compat: Change to DataKey provided by ChangesListView

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsIgnoredHolderUpdateListenerAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsIgnoredHolderUpdateListenerAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsIgnoredHolderUpdateListenerAdapter.java

compat: VcsIgnoredHolderUpdateListener methods changed

compat: VcsIgnoredHolderUpdateListener methods changed

---

WORKSPACE

Import Android Studio 3.6 Beta 5 (3.6.0.17)

Import Android Studio 3.6 Beta 5 (3.6.0.17)

---

javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java

Unsuppress wildcard imports after 2019.3.
According to the upstream bug it's fixed in 2019.3, but we need to keep
this workaround until the broken versions are obsolete.

Unsuppress wildcard imports after 2019.3.

---

base/src/com/google/idea/blaze/base/sync/libraries/BlazeExternalSyntheticLibrary.java
base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java
golang/src/com/google/idea/blaze/golang/sync/BlazeGoAdditionalLibraryRootsProvider.java

Add go files to external library as they are resolved.

Add go files to external library as they are resolved.

---

WORKSPACE

Import CLion 2019.3.1

---

java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java
java/tests/unittests/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporterTest.java

Use LinkedHashMap instead of HashMap to store libraries.
Classpath in IntelliJ is determined by the order in which JARs are added to the
module. We store the libraries in a HashTable and then stream it into a List,
which effectively radomizes the order in which JARs are added. This causes
potential symbol resolution issues where a dependent JAR packs a subset of its
dependecies, and IntelliJ uses the dependent JAR as canonical source of the
dependency.
This CL changes the HashMap to a LinkedHashMap which preserves the order in
which keys were added. As a result, streaming the JARs into a List retains the
order in which JARs were added to the HashMap. JARs are added to the
LinkedHashMap in a bottom first order. The dependencies are added first
followed by the dependent JARs. This prevents …

Use LinkedHashMap instead of HashMap to store libraries.

---

CHANGELOG

Update changelog for 2019.12.16 release.

Update changelog for 2019.12.16 release.

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderBaseAdapter.java
sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderCompat.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderBaseAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderCompat.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderBaseAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsRepositoryIgnoredFilesHolderCompat.java

compat: sdk compat layer for VcsRepositoryIgnoredFiles-related apis

compat: sdk compat layer for VcsRepositoryIgnoredFiles-related apis

---

javascript/src/META-INF/javascript-contents.xml
javascript/src/com/google/idea/blaze/javascript/BlazeJsCompletionService.java

Fix timeout wait on EDT in JSCompletionService.

Fix timeout wait on EDT in JSCompletionService.

---

sdkcompat/v192/com/google/idea/sdkcompat/clion/MessageBusFactoryAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/clion/MessageBusFactoryAdapter.java

Change OverrideFileSymbolTableCacheListener to not rely on visibility of MessageBusConnectionImpl.

Change OverrideFileSymbolTableCacheListener to not rely on visibility of MessageBusConnectionImpl.

---

sdkcompat/v191/BUILD
sdkcompat/v191/com/google/idea/sdkcompat/psi/impl/file/impl/ResolveScopeManagerImplCompat.java
sdkcompat/v192/BUILD
sdkcompat/v192/com/google/idea/sdkcompat/psi/impl/file/impl/ResolveScopeManagerImplCompat.java
sdkcompat/v193/BUILD
sdkcompat/v193/com/google/idea/sdkcompat/psi/impl/file/impl/ResolveScopeManagerImplCompat.java

compat: Add compat class for ResolveScopeManagerImpl

compat: Add compat class for ResolveScopeManagerImpl

---

testing/testcompat/v192/com/google/idea/sdkcompat/codeinsight/documentation/DocumentationManagerCompat.java
testing/testcompat/v193/com/google/idea/sdkcompat/codeinsight/documentation/DocumentationManagerCompat.java

compat: Add compat class for DocumentationManager#generateDocumentation.
DocumentationManager#generateDocumentation has changed signatures in v193. This CL adds a compat class for consistent signatures.

compat: Add compat class for DocumentationManager#generateDocumentation.

---

WORKSPACE

Update IJ UE from 2019.3.0 to 2019.3.1

Update IJ UE from 2019.3.0 to 2019.3.1

---

build_defs/Repackager.java

Repackaging uses constant timestamps for files to make jars reproducible
The CL updates the process of repackaging jar files with a new step that 
sets all the creation, modification and access dates to a constant for 
all the files inside of an output jar. This should allow multiple 
repackaging of the same input jar file to produce exactly the same 
outputs.

Repackaging uses constant timestamps for files to make jars reproducible

---

cpp/src/com/google/idea/blaze/cpp/BlazeCppAutoImportHelper.java

Fix exception in BlazeCppAutoImportHelper

Fix exception in BlazeCppAutoImportHelper

---

WORKSPACE

Update IJ CE from 2019.3.0 to 2019.3.1

Update IJ CE from 2019.3.0 to 2019.3.1

---

base/src/com/google/idea/blaze/base/sync/libraries/BlazeExternalSyntheticLibrary.java

Reindex for external libraries after 5 seconds of no new files being added.
Previously we relied on the delay of the indexing itself (usually 5 seconds apart) to batch the indexing of new files, but this could result in continuous indexing until files stop being added. We will change the order: wait for files to stop being added first, then reindex all at once. At the worst case, this will be identical to the previous behavior, if the user just happens to have new files added exactly 5 seconds apart, but this is very unlikely.

Reindex for external libraries after 5 seconds of no new files being added.

---

WORKSPACE

Import CLion 2019.3.2

---

sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java
sdkcompat/v193/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java

Make sure our VcsVFSListener actually listens.

Make sure our VcsVFSListener actually listens.

---

WORKSPACE

Import Android Studio 3.6 RC 1 (3.6.0.18)

Import Android Studio 3.6 RC 1 (3.6.0.18)

---

sdkcompat/v191/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java
sdkcompat/v192/com/google/idea/sdkcompat/vcs/VcsVFSListenerAdapter.java

Don't return shared mutable list of deleted files, to avoid races.

Don't return shared mutable list of deleted files, to avoid races.

---

aspect/BUILD
aspect/BUILD.aspect
aspect/intellij_info_impl.bzl
aspect/tools/BUILD
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java
aspect/tools/tests/unittests/com/google/idea/blaze/aspect/CreateAarTest.java
aspect/tools/tests/unittests/generated_aar/AndroidManifest.xml
aspect/tools/tests/unittests/generated_aar/res/values/colors.xml

Create aar files for resource files

Create aar files for resource files

---

base/src/com/google/idea/blaze/base/run/producers/BinaryContextRunConfigurationProducer.java
base/src/com/google/idea/blaze/base/run/producers/TestContextRunConfigurationProducer.java

Wrap context with custom equals implementation for cached value stability.

Wrap context with custom equals implementation for cached value stability.

---

CHANGELOG

Update changelog for 2020.01.13 release.

Update changelog for 2020.01.13 release.

---

testing/src/com/google/idea/testing/IntellijRule.java

api193: Miscellaneous fixes.
Fixes:
- QualifierAdjuster.java: As of api193, `semicolon` is the last child of the UsingStatement rather than its sibling. This CL adds a conditional to handle `semicolon` being either a child or a sibling.
- LintAnnotatorRegistration.java: The plugin descriptor of a dynamic extension cannot be set of null in api193. This CL adds a null check before calling `setPluginDescriptor`.
- ProtobufferModeDetector.java: Implement `getDetectedFileTypes()` which causes test failures in api193
- IntellijRule.java: Uses `TestUtil.MockApplication` which is not supported by `ServiceContainerUtil`, so added logic to register services/components internally rather than delegating to `ServiceHelper`

api193: Miscellaneous fixes.

---

java/src/com/google/idea/blaze/java/fastbuild/FastBuildChangedFilesService.java

Add @SuppressWarnings for new violations of the GuardedBy checker.

Add @SuppressWarnings for new violations of the GuardedBy checker.

---

golang/tests/integrationtests/com/google/idea/blaze/golang/resolve/BlazeGoAnnotatorTest.java

Add regression test for https://youtrack.jetbrains.com/issue/GO-8698.

Add regression test for https://youtrack.jetbrains.com/issue/GO-8698.

---

golang/tests/integrationtests/com/google/idea/blaze/golang/resolve/BlazeGoAnnotatorTest.java

Add cases to BlazeGoAnnotatorTest for types and fields.

Add cases to BlazeGoAnnotatorTest for types and fields.

---

CHANGELOG

Update changelog for 2020.01.27 release

Update changelog for 2020.01.27 release

---

aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepMobileInstallIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeApkBuildStepNormalBuildIntegrationTest.java
aswb/tests/integrationtests/com/google/idea/blaze/android/functional/BlazeInstrumentationTestApkBuildStepIntegrationTest.java
base/src/com/google/idea/blaze/base/command/buildresult/ParsedBepOutput.java
base/src/com/google/idea/blaze/base/logging/utils/BuildPhaseSyncStats.java
base/src/com/google/idea/blaze/base/logging/utils/SyncStats.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java

Add .blazeproject files and build ID to sync logs.

Add .blazeproject files and build ID to sync logs.

---

WORKSPACE

Update IJ CE to 2019.3.2

---

WORKSPACE

Update IJ UE to 2019.3.2

---

base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/findusages/LocalVariableUsagesTest.java

Fix a failing test in 2019.3

---

WORKSPACE

Update python and scala plugins for 2019.3

Update python and scala plugins for 2019.3

---

proto/project_data.proto

This idiom broke in Bazel@HEAD due to 50013dd.
details.

Import Bazel protos using their repo relative path.

---

.bazelci/aspect.yml

This pull request adds tasks for testing aspects against all the IDE versions supported internally and externally.

Add aspect tests for all supported IJ versions

---

.bazelci/intellij-ue.yml
.bazelci/intellij.yml

rename canary to under-dev in CI

---

java/src/com/google/idea/blaze/java/libraries/JarCache.java

Sync master branch to google branch

Reduce CPU usage of the local action that repackages lint jars

---

examples/kotlin/simple_coroutines_project/test/GreetingTest.kt

Update coroutines example test.

Update coroutines example test

---

WORKSPACE

details.
The current version of rules_kotlin contains a bug that causes it to break in Bazel 6.0. It's been fixed in https://github.com/bazelbuild/rules_kotlin/pull/777 and the latest release includes this fix.

Update rules_kotlin version

---

WORKSPACE

update dependencies to current IntelliJ platform EAP release 222.3345

update dependencies to current IntelliJ platform EAP release 222.3345

---

common/actions/src/com/google/idea/common/actions/ReplaceActionHelper.java

details.
Issue number: Fixes #3788

RemovedAction should delegate isDumbAware 

---

common/experiments/src/com/google/idea/common/experiments/experiment.properties

- Roll out Kotlin coroutines debugging to 50% of users
- Roll out the new sync window to 50% of users

Roll out Experimental Features to 50% of users

---

WORKSPACE
golang/BUILD
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.idea212
intellij_platform_sdk/BUILD.idea213
intellij_platform_sdk/BUILD.idea221
intellij_platform_sdk/BUILD.idea222
intellij_platform_sdk/BUILD.ue212
intellij_platform_sdk/BUILD.ue213
intellij_platform_sdk/BUILD.ue221
intellij_platform_sdk/BUILD.ue222
testing/testcompat/v222/com/google/idea/sdkcompat/indexing/ProjectIndexingHistoryWrapper.java

Reverts bazelbuild/intellij#3812

Revert "IntelliJ 2022.2 compatibility fixes"

---

CHANGELOG

Update changelog for 2022.08.09 release

---

common/experiments/src/com/google/idea/common/experiments/experiment.properties

- Roll out Kotlin coroutines debugging to 70% of users
- Roll out the new sync window to 70% of users

Roll out Experimental Features to 70% of users

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- [ Yes] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ Yes] I have received the approval from the maintainers to make this change.
- [ Yes] This is not a stylistic, refactoring, or cleanup change.
details.
This PR provides the templates for type:bug and type:feature in bazelbuild/Intellij Repository.

Bazel intellij Issue Template

---

CHANGELOG

Please comment with any significant changes that you want to be mentioned in the release changelog.

Starting v2022.08.24 release

---

base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java
base/src/com/google/idea/blaze/base/sync/data/BlazeDataStorage.java

Fixes hardcoded Intellij project data path to support other IDE products as reported in https://github.com/bazelbuild/intellij/pull/3601#issuecomment-1219955183

Detect project data directory per IDE product

---

CHANGELOG

Please comment with any significant changes that you want to be mentioned in the release change log.

Release v2022.09.07

---

aspect/fast_build_info.bzl
aspect/intellij_info_impl.bzl

Similar to https://github.com/bazelbuild/intellij/commit/41d1964a6c2871c5458a26c94d667574b3e7c487; fixes JavaTestFastBuildAspectTest
PiperOrigin-RevId: 473291296
details.

Future-proof fast_build_info generation

---

CHANGELOG

Please comment with any significant changes that you want to be mentioned in the release changelog.

Starting v2022.09.20 release

---

base/src/com/google/idea/blaze/base/sync/projectstructure/ContentEntryEditor.java

Refactoring to make the code more readable
details.
https://github.com/bazelbuild/intellij/pull/3671
Refactoring to make the code more readable, please see the discussion above

Refactor walkFileSystem() method in ContentEntryEditor

---

examples/java/greetings_project/WORKSPACE
examples/java/greetings_project/greeting_lib/BUILD
examples/java/greetings_project/greeting_lib/src/com/example/Greeting.java
examples/java/greetings_project/greeting_lib/tests/com/example/GreetingTest.java
examples/java/greetings_project/hello/BUILD
examples/java/greetings_project/hello/hello.bazelproject
examples/java/greetings_project/hello/src/com/example/HelloGreeter.java
examples/java/greetings_project/hi/BUILD
examples/java/greetings_project/hi/hi.bazelproject
examples/java/greetings_project/hi/src/com/example/HiGreeter.java

Add example java project to be used for manual testing.

Add Java Example Project

---

CHANGELOG

Please comment with any significant changes that you want to be mentioned in the release changelog.

Starting v2022.10.04 release

---

CHANGELOG

Please comment with any significant changes that you want to be mentioned in the release change log.

Release v2022.10.18

---

README.md

Adding a reference to the SIG charter to readme.md

readme.md: add a section how to find the SIG

---

CONTRIBUTING.md
DEV_IDE_SETUP.md

details.
I've found it difficult to set up my dev environment, so I've made a doc with the findings.

fix(docs): Add instructions to set up development environment

---

base/src/com/google/idea/blaze/base/lang/buildfile/parser/StatementParsing.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/parser/BuildParserTest.java

details.
Issue number: #4027 
Change Starlark parser to allow function definitions anywhere a statement is allowed

Support Starlark nested function definitions

---

CHANGELOG

Hello, Please let us know if there are any changes you want to add in release. Thanks!

v2022.11.01 Clion & Intellij Release

---

sdkcompat/v222/BUILD

These pattern do not glob anything
See: https://github.com/bazelbuild/intellij/issues/4040
details.

Remove pattern that does not glob anything

---

WORKSPACE

Bump ij to 2022.3 Beta

---

WORKSPACE
testing/testcompat/v222/com/google/idea/sdkcompat/BaseSdkTestCompat.java

details.
Issue number: closes #4081 
1. `a87a05e9debdb49bc0b509eb090b214c8b0a05a15de495a23da98d90fc59545f` was a checksum for Idea 223.7401.16
2.  Tests were failing due to incorrect cast in `BaseSdkTestCompat.java`

Fix 223 beta update

---

WORKSPACE

Bump Clion to 2022.3 Beta

---

CHANGELOG

Please comment with any significant changes that you want to be mentioned in the release changelog.

Starting v2022.11.15 release for the IDEA and CLion plugin

---

CHANGELOG

Please comment with any significant changes you want to be included in release changelog.

Release v2022.11.15 for Android Studio Plugin

---

CHANGELOG

Please let us know if there are any significant changes you want to add in release changelog. Thanks!

Release for v2022.11.29 Clion & Intellij 

---

WORKSPACE
intellij_platform_sdk/BUILD.clion223

Update CLion to 2022.3 release

---

examples/cpp/simple_project/WORKSPACE
examples/cpp/simple_project/proj.bazelproject
examples/cpp/simple_project/src/BUILD
examples/cpp/simple_project/src/hello_world.cc
examples/cpp/simple_project/src/lib/BUILD
examples/cpp/simple_project/src/lib/greeting_lib.cc
examples/cpp/simple_project/src/lib/greeting_lib.h
examples/cpp/simple_project/src/lib/greeting_test.cc

Adding example project for C++ to manually test the plugin released for CLion.

Add C++ example project

---

CHANGELOG

Please comment with any important changes that you want to make visible by adding to the Change log.

Release for v2023.01.10 IDEA and CLion 

---

CHANGELOG

Please comment with any important changes that you want to make visible by adding to the Change log.

Update changelog for 2023.01.24 IDEA & CLion release

---

WORKSPACE
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfig.java
javascript/src/com/google/idea/blaze/typescript/BlazeTypeScriptConfigServiceImpl.java
javascript/src/com/google/idea/blaze/typescript/DelegatingTypeScriptConfigService.java
sdkcompat/v213/BUILD
sdkcompat/v213/com/google/idea/sdkcompat/javascript/JSModuleResolutionWrapper.java
sdkcompat/v213/com/google/idea/sdkcompat/javascript/JSModuleTargetWrapper.java
sdkcompat/v213/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java
sdkcompat/v213/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java
sdkcompat/v221/BUILD
sdkcompat/v221/com/google/idea/sdkcompat/javascript/JSModuleResolutionWrapper.java
sdkcompat/v221/com/google/idea/sdkcompat/javascript/JSModuleTargetWrapper.java
sdkcompat/v221/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java
sdkcompat/v221/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java
sdkcompat/v222/BUILD
sdkcompat/v222/com/google/idea/sdkcompat/javascript/JSModuleResolutionWrapper.java
sdkcompat/v222/com/google/idea/sdkcompat/javascript/JSModuleTargetWrapper.java
sdkcompat/v222/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java
sdkcompat/v222/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java
sdkcompat/v223/BUILD
sdkcompat/v223/com/google/idea/sdkcompat/javascript/JSModuleResolutionWrapper.java
sdkcompat/v223/com/google/idea/sdkcompat/javascript/JSModuleTargetWrapper.java
sdkcompat/v223/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java
sdkcompat/v223/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java
sdkcompat/v231/BUILD
sdkcompat/v231/com/google/idea/sdkcompat/javascript/JSModuleResolutionWrapper.java
sdkcompat/v231/com/google/idea/sdkcompat/javascript/JSModuleTargetWrapper.java
sdkcompat/v231/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java
sdkcompat/v231/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java

Bump versions to CLion 231.5920.6 and IntelliJ 231.5920.14

---

CHANGELOG

Please comment with any important changes that you want to make visible by adding to the Change log.

Update changelog for v2023.02.07 IDEA & CLion release

---

WORKSPACE

Bump to IntelliJ 231.6890.12 and CLion 231.6890.13 (Feb 9 EAP)

---

plugin_dev/src/com/google/idea/blaze/plugin/run/IntellijWithPluginClasspathHelper.java

details.
Each product bundle contains product-info.json file which contains basic information
such as jar files that should be loaded, or required JVM parameters.
This will simplify steps defined in DEV_IDE_SETUP.md
For versions 2022.3 and older we keep the old behavior (hardcoded library set)
This should make the codebase easier to maintain - no need to keep hardcoded libraries up to date

Read product info json instead hardcoded intellij libraries

---

WORKSPACE
intellij_platform_sdk/BUILD

details.
The line `"intellij-2023.1": ["@jsr305_annotations//jar"]` is added, because
javax.annotation.Nullable was missing

Bump to 231.7665.28 (EAP 6)

---

CHANGELOG

Update changelog for v2023.02.22 IDEA & CLion release

---

.github/workflows/stale.yml

Same changes as in https://github.com/bazelbuild/bazel/pull/17555

Stale workflow - process updates

---

WORKSPACE

Bump to IntelliJ 231.7864.76 and CLion 231.7864.77

---

.github/workflows/stale.yml

Ready to be approved but not merged yet (fyi @sgowroji)
cc @meteorcloudy

Update stale workflow (final) - 6 months

---

WORKSPACE

Bump IntelliJ to 231.8109.90 and CLion to 231.8109.80

---

WORKSPACE

Bump IntelliJ to 231.8109.144 and CLion to 231.8109.141

---

java/src/com/google/idea/blaze/java/run/producers/BlazeJavaAbstractTestCaseConfigurationProducer.java
java/tests/integrationtests/com/google/idea/blaze/java/run/producers/BlazeJavaAbstractTestCaseConfigurationProducerTest.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/4573
Before this change, clicking a gutter play arrow in a superclass
test-method would generate a filter which droppde the method name.
This seems to be because IntelliJ was giving us a PsiIdentifier for the
method, not a PsiMethod.
This change adds a step to resolve a method's PsiIdentifier to its
PsiMethod, which means the test filter gets correctly generated.
Fixes #4573

Superclass method test runs run the correct method

---

plugin_dev/src/com/google/idea/blaze/plugin/run/IntellijWithPluginClasspathHelper.java

1. Take into account that the product-info.json file is in /Applications/<ij>/Content/Resoureces/
2. Replace APP_PACKAGE with the right installation path
details.

plugin_dev: Fix run configuration on Mac OS X

---

base/src/com/google/idea/blaze/base/run/BlazeBeforeRunCommandHelper.java

Fix for https://github.com/bazelbuild/intellij/issues/4253

Allow run script path override

---

CHANGELOG

Update changelog for v2023.04.18 IDEA and CLion release

---

CHANGELOG

Update changelog for 2023.05.02 release

---

plugin_dev/src/com/google/idea/blaze/plugin/run/IntellijWithPluginClasspathHelper.java

plugin_dev: Allow plugin development on Windows

---

CHANGELOG

Update changelog for v2023.05.16 release

---

CHANGELOG

Update changelog for release v2023.05.30

---

WORKSPACE

Bump JUnit to 4.13.2

---

WORKSPACE

Bump 2023.1 artifacts

---

WORKSPACE

Bump IntelliJ to 2023.2 EAP 5 and plugins to newest versions

---

WORKSPACE
java/tests/integrationtests/com/google/idea/blaze/java/sync/projectstructure/JdksTest.java

Bump dependency versions

---

CHANGELOG

Update CHANGELOG for release v2023.07.04

---

WORKSPACE

Bump to new EAPs

---

CHANGELOG

Update changelog for release v2023.07.18

---

WORKSPACE

Bump IntelliJ versions

---

WORKSPACE

Bump CLion to RC

---

CHANGELOG

Update changelog for release v2023.08.01

---

base/src/META-INF/blaze-base.xml

Fix the "No display name is specified' error

---

CHANGELOG

Update changelog for release v2023.08.15

---

base/src/com/google/idea/blaze/base/vcs/git/GitBlazeVcsHandlerProvider.java

details.
Our project is in git repo and have `.git` folder in one of the parent folder so check for `.git` is not enough.

Proper check for git repository

---

CHANGELOG

Update changelog for release v2023.08.29

---

CHANGELOG

Update changelog for release v2023.09.12

---

WORKSPACE

Bump IntelliJ and plugins

---

CHANGELOG

Update changelog for v2023.09.26

---

base/src/META-INF/blaze-base.xml

Prepare for 2023.3: Specify 'text' field explicitely in XML file

---

CHANGELOG

Update CHANGELOG for v2023.10.10

---

WORKSPACE
plugin_dev/BUILD
third_party/devkit/BUILD

Bump to newest EAPs

---

WORKSPACE

Bump to 2023.3 EAP 5

---

CHANGELOG

Update changelog for 2023.10.24

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Update assignees in issue templates

Update assignees in templates

---

base/src/com/google/idea/blaze/base/lang/buildfile/references/BuildReferenceManager.java
base/src/com/google/idea/blaze/base/lang/buildfile/references/FileLookupData.java
base/src/com/google/idea/blaze/base/model/primitives/WorkspaceRoot.java
base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/references/BuildReferenceManagerTest.java

Discussed offline with @blorente.
Do not complete ignored directories in a label in build files.

fix: Do not complete ignored directories

---

golang/src/com/google/idea/blaze/golang/resolve/BlazeGoPackageFactory.java

Fix 'Non-blaze project is provided' error in GoLand

---

WORKSPACE

Bump JetBrains products versions

---

CHANGELOG

Update CHANGELOG for 2023.12.05 release

---

CHANGELOG

Update changelog for 2023.12.19 release

---

CHANGELOG

Update changelog for 2024.01.02

---

WORKSPACE
golang/tests/integrationtests/com/google/idea/blaze/golang/resolve/BlazeGoAnnotatorTest.java

Also, don't use the removed AnnotationHolderImpl constructor
https://github.com/JetBrains/intellij-community/commit/b7533e8c138149628cd19ae44ca5d37bedd50d6d#diff-a97641ee13ee7d2630298fd2a6bb50595c040c4c0a4bde071f936e3548052864L38-L47

Bump JetBrains IDEs

---

testing/testcompat/v241/com/google/idea/java/JavaSdkCompat.java

Use dedicated API instead of implementation details

---

WORKSPACE
base/src/com/google/idea/blaze/base/ui/problems/BlazeProblemsViewPanel.java
sdkcompat/v223/com/google/idea/sdkcompat/general/NewErrorTreeViewPanelAdapter.java
sdkcompat/v231/com/google/idea/sdkcompat/general/NewErrorTreeViewPanelAdapter.java
sdkcompat/v232/com/google/idea/sdkcompat/general/NewErrorTreeViewPanelAdapter.java
sdkcompat/v233/com/google/idea/sdkcompat/general/NewErrorTreeViewPanelAdapter.java
sdkcompat/v241/com/google/idea/sdkcompat/general/NewErrorTreeViewPanelAdapter.java

chore: Bump JetBrains dependencies

---

CHANGELOG

Update changelog for 2024.02.13

---

WORKSPACE

Bump jetbrains products

---

base/src/com/google/idea/blaze/base/bazel/BazelWorkspaceRootProvider.java
base/src/com/google/idea/blaze/base/wizard2/UseExistingBazelWorkspaceOption.java

details.
Issue number: #6037
Added `MODULE.bazel` to the `isWorkspaceRoot` check.

Added MODULE.bazel to valid workspace root files

---

intellij_platform_sdk/build_defs.bzl

details.
2024.1 update: declare 2024.1 as stable

2024.1 update: declare 2024.1 as stable

---

WORKSPACE.bzlmod
python/BUILD
third_party/toml/BUILD

chore: Bump JetBrains products versions

---

CHANGELOG

Update changelog for 2024.02.27 release

---

base/src/com/google/idea/blaze/base/project/AutoImportProjectOpenProcessor.java

details.
Issue number: #6037
Added `MODULE.bazel` to `isBazelWorkspace` in AutoImportProjectOpenProcessor.

Added MODULE.bazel to isBazelWorkspace in AutoImportProjectOpenProcessor

---

base/tests/unittests/com/google/idea/blaze/base/qsync/DependencyTrackerImplTest.java
querysync/javatests/com/google/idea/blaze/qsync/QuerySyncTestUtils.java

Fixes https://github.com/bazelbuild/intellij/issues/6172

Fix unit test failure with bazel@head

---

examples/kotlin/simple_coroutines_project/BUILD
examples/kotlin/simple_project/BUILD

Fixes: https://github.com/bazelbuild/intellij/issues/6232

Fix kotlin example projects

---

WORKSPACE.bzlmod

Bump CLion

---

WORKSPACE.bzlmod

chore: Bump JetBrains IDEs

---

CHANGELOG

Update CHANGELOG for v2024.03.26

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Update assignee in issue templates

Update assignee in issue templates

---

README.md

Extend "Known Limitations" in README.md

---

CHANGELOG

Update CHANGELOG for 2024.04.09 release

---

CHANGELOG

Update changelog for v2024.04.23 release

---

CHANGELOG

Update CHANGELOG for v2024.05.07

---

CHANGELOG

Update CHANGELOG for v2024.05.21 release

---

CHANGELOG

Update CHANGELOG for v2024.06.04

---

base/src/com/google/idea/blaze/base/util/SaveUtil.java

details.
Issue number: `N/A`
To make sure it happens all the time.

fix: Mark saveAllFiles as a WriteAction

---

WORKSPACE.bzlmod

Bump JetBrains plugins

---

CHANGELOG

Update changelog for v2024.07.02 release

---

README.md
clwb/src/META-INF/description.html
ijwb/src/META-INF/description.html

doc: Add reference to the youtube video

---

maven_install.json

Result of $ REPIN=1 bazel run @maven//:pin
details.

chore: Run maven repin

---

.github/labeler.yml

Typo Error in labeler

---

base/src/META-INF/blaze-base.xml

details.
This action and menu no longer exits since 6e6c399.

Remove IntelliJExt registrations

---

CODEOWNERS

I don't really have the capacity to regularly review changes, can still do so on request

Update CODEOWNERS - remove Justin Kaeser

---

base/src/com/google/idea/blaze/base/prefetch/FetchExecutor.java

fix: Adjust executor threads based on device core count

---

intellij_platform_sdk/BUILD
intellij_platform_sdk/build_defs.bzl
testing/BUILD
third_party/go/BUILD
third_party/javascript/BUILD
third_party/python/BUILD
third_party/scala/BUILD

Drop support IntelliJ 2021.3 - part 1

---

base/src/com/google/idea/blaze/base/sync/projectstructure/ModuleEditorImpl.java

Fixed in IntelliJ here
https://github.com/JetBrains/intellij-community/commit/8d0a816aa26f6e9cd5e21c56fc6d01766b0b0b55
details.

chore: remove a hack made for 2021.1

---

.bazelci/clion.yml
MODULE.bazel
MODULE.bazel.lock
clwb/test_defs.bzl
clwb/tests/integrationtests/com/google/idea/blaze/clwb/base/ClwbIntegrationTestCase.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/base/InMemoryPreferencesFactory.java
clwb/tests/integrationtests/com/google/idea/blaze/clwb/base/SyncOutput.java

details.
Adds a MacOS runner for CLion. As far as I can tell, all test work on MacOS including the integration tests.

MacOS CI Runner

---

cpp/src/com/google/idea/blaze/cpp/BlazeLanguageKindCalculatorHelper.java

chore: Add @Override annotation as 212 api is already dropped

---

testing/testcompat/v221/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v222/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v223/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v231/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v232/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v233/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v241/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v242/com/google/idea/sdkcompat/BaseSdkTestCompat.java

If we drop 221, all the implementations will be the same
details.

chore: fix sdkcompat api annotations

---

testing/src/com/google/idea/testing/AbstractIntegrationTestCase.java
testing/testcompat/v221/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v222/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v223/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v231/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v232/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v233/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v241/com/google/idea/sdkcompat/BaseSdkTestCompat.java
testing/testcompat/v242/com/google/idea/sdkcompat/BaseSdkTestCompat.java

chore: drop 213:  Inline createLightFixtureBuilder from sdkcompat

---

sdkcompat/v221/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v222/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v223/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v231/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v232/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v233/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v241/com/google/idea/sdkcompat/general/BaseSdkCompat.java
sdkcompat/v242/com/google/idea/sdkcompat/general/BaseSdkCompat.java

chore: drop 213: Remove unused SdkCompat methods

---

kotlin/src/com/google/idea/blaze/kotlin/qsync/BlazeKotlinQuerySyncPlugin.java
kotlin/src/com/google/idea/blaze/kotlin/sync/BlazeKotlinSyncPlugin.java
sdkcompat/v221/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v222/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v223/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v231/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v232/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v233/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v241/com/google/idea/sdkcompat/kotlin/KotlinCompat.java
sdkcompat/v242/com/google/idea/sdkcompat/kotlin/KotlinCompat.java

chore: drop 213: Inline some KotlinCompat methods

---

kotlin/src/com/google/idea/blaze/kotlin/run/producers/KotlinBinaryContextProvider.java

chore: drop 213: Update deprecated method use

---

sdkcompat/v223/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v231/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v232/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v233/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v241/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v242/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java

chore: Fix invalid API annotations

---

clwb/src/com/google/idea/blaze/clwb/oclang/run/CidrGoogleTestUtilAdapter.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java

details.
Issue number: #6740
2 changes required after 2024.2 update.

Fix googletest integration with CLion 2024.2

---

base/src/com/google/idea/blaze/base/command/info/BlazeInfo.java
base/src/com/google/idea/blaze/base/run/coverage/CoverageUtils.java
java/tests/integrationtests/com/google/idea/blaze/java/fastbuild/FastBuildChangedFilesServiceTest.java

Issue number: #6764
This restores show coverage functionality broken by #6728

[#6764] Fix coverage display when running tests

---

MODULE.bazel
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.clion243
intellij_platform_sdk/BUILD.idea243
intellij_platform_sdk/BUILD.ue243

chore: Support Jetbrains IDEs 243 - part 1

---

intellij_platform_sdk/build_defs.bzl
sdkcompat/BUILD
sdkcompat/v243/BUILD
sdkcompat/v243/com/google/idea/sdkcompat/clion/CidrDebugProcessCreator.java
sdkcompat/v243/com/google/idea/sdkcompat/editor/markup/UIControllerCreator.java
sdkcompat/v243/com/google/idea/sdkcompat/general/NewErrorTreeViewPanelAdapter.java
sdkcompat/v243/com/google/idea/sdkcompat/go/GoSdkCompat.java
sdkcompat/v243/com/google/idea/sdkcompat/javascript/JSModuleResolutionWrapper.java
sdkcompat/v243/com/google/idea/sdkcompat/javascript/JSModuleTargetWrapper.java
sdkcompat/v243/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java
sdkcompat/v243/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java
sdkcompat/v243/com/google/idea/sdkcompat/refactoring/safedelete/JavaSafeDeleteProcessorCompat.java
sdkcompat/v243/com/google/idea/sdkcompat/ui/icons/IconManagerCompat.java
sdkcompat/v243/com/google/idea/sdkcompat/vcs/changes/ChangeListAdapterCompat.java
sdkcompat/v243/com/google/idea/sdkcompat/vcs/changes/FakeRevisionCompat.java
sdkcompat/v243/com/google/idea/sdkcompat/vcs/changes/ui/ChangesListViewCreator.java
sdkcompat/v243/com/google/idea/sdkcompat/vcs/impl/VcsBaseContentProviderDelegator.java
testing/BUILD
testing/testcompat/v243/com/google/idea/java/JavaSdkCompat.java
testing/testcompat/v243/com/google/idea/testing/TestRunnerUtilCompat.java
third_party/go/BUILD
third_party/javascript/BUILD
third_party/python/BUILD
third_party/scala/BUILD

This is a raw copy of 242 compat layer, to compare it, please run:
diff -r sdkcompat/v2{42,43}
diff -r testing/testcompat/v2{42,43}
details.

chore: Prepare for 243 bump

---

examples/cpp/simple_project/WORKSPACE

chore: Bump cpp example

---

base/src/com/google/idea/blaze/base/command/info/BlazeInfoProvider.java

feature: Cache 'bazel info' results

---

base/src/com/google/idea/blaze/base/command/mod/BlazeModRunnerImpl.java

fix: Fix bazel mod deps execution

---

MODULE.bazel
MODULE.bazel.lock
clwb/clwb.bazelproject
clwb/sdkcompat/BUILD
clwb/sdkcompat/v243/BUILD
clwb/sdkcompat/v243/com/google/idea/blaze/clwb/BazelCNotificationProvider.java
clwb/sdkcompat/v243/com/google/idea/blaze/clwb/CLionNotificationProvider.kt
clwb/sdkcompat/v243/com/google/idea/blaze/clwb/MSVCCompilerVersionCompat.java
clwb/test_defs.bzl
cpp/sdkcompat/BUILD
cpp/sdkcompat/v243/BUILD
cpp/sdkcompat/v243/com/google/idea/blaze/cpp/qsync/OCWorkspaceModifiableModelDisposer.java
intellij_platform_sdk/BUILD.clion243
intellij_platform_sdk/build_defs.bzl
testing/test_defs.bzl
third_party/javascript/BUILD

Adds support for CLion 243 EAP. Fixes compatibility and test issues.

Support Jetbrains IDEs 243 - CLion

---

shared/java/com/google/idea/blaze/common/RuleKinds.java

fix: Query Sync works for kotlin

---

base/src/com/google/idea/blaze/base/wizard2/ui/BlazeEditProjectViewControl.java

Fixes #6829, fixes #434, fixes #6454

[fix] Confirm if user wants to reimport instead of disallowing it

---

base/src/com/google/idea/blaze/base/bazel/BazelBuildSystemProvider.java

[feature] Recognize WORKSPACE.bzlmod files

---

clwb/clwb.bazelproject

chore: Make clwb config appearing by default

---

.bazelrc

fix: project sync failing due to an error in rules_rust

---

aspect/BUILD
aspect/intellij_info_impl.bzl

chore: Aspect templating - 5/n - bundled-only section

---

docs/querysync.md

Document query sync

---

MODULE.bazel
MODULE.bazel.lock
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRemoteDebugProcess.java

chore: Bump CLion

---

skylark/src/com/google/idea/blaze/skylark/debugger/impl/SkylarkDebugProcess.java

Fix starlark debugger

---

docs/gazelle.md

doc: Document gazelle integration

---

java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestEnvironmentCreator.java

fix: fast test not working when main class is not set

---

docs/index.md

doc: Table of contents

---

base/src/META-INF/blaze-base.xml
base/src/com/google/idea/blaze/base/ui/BlazeModuleRendererFactory.java

details.
https://github.com/user-attachments/assets/5b11024f-11fd-497d-a5a5-63e66a4784d2

feat: More descriptive location labels (instead of just .workspace)

---

base/src/com/google/idea/blaze/base/buildview/events/AbortedParser.kt

Improves the aborted parse to report unknown targets.

BEP parse unknown targets in aborted event

---

sdkcompat/v243/com/google/idea/sdkcompat/javascript/TypeScriptConfigAdapter.java

fix: 2024.3 builds

---

intellij_platform_sdk/BUILD.idea241
intellij_platform_sdk/BUILD.idea242
intellij_platform_sdk/BUILD.idea243
python/BUILD
third_party/toml/BUILD

fix: Python tests

---

MODULE.bazel

chore: Bump JetBrains IDEs and fix scala integration tests

---

base/src/com/google/idea/blaze/base/wizard2/BlazeImportProjectAction.java

Make the BlazeImportProjectAction dumb aware

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncManager.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncPromo.java

feat: Query Sync promo

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncNotificationProvider.java

fix(qsync): Some improvements to the RD-compatible notification panel

---

base/src/com/google/idea/blaze/base/sync/workspace/WorkspaceHelper.java

fix: NPE in WorkspaceHelper when project is not loaded yet

---

CHANGELOG
base/src/com/google/idea/blaze/base/sync/aspects/strategy/SyncAspectTemplateProvider.java

V2024.11.19 hotfix

---

.bazelrc

We are o bazel 8 now, n/a
details.

chore: Remove commented code in .bazelrc

---

docs/querysync.md

Query Sync doc - difference between "sync" and "enable analysis"

---

examples/java/greetings_project/WORKSPACE
examples/java/greetings_project/junit5_deps.bzl

chore: Bump deps

---

docs/querysync.md

doc: Update querysync.md title

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncPromo.java

There are still some important issues
details.

fix: Disable Query Sync promo

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncManager.java

Adds support for the new sync view for query sync.

Enable the new sync view for query sync

---

ijwb/ijwb.bazelproject

chore: set explicit 2024.3 version and enable qs in the project view

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java

Cherry pick AOSP commit [8f1fc345c9f4b7a9528f983a2b4426a15ff57a3d](https://cs.android.com/android-studio/platform/tools/adt/idea/+/8f1fc345c9f4b7a9528f983a2b4426a15ff57a3d).
using experiments.
Together with experiments properly supporting channels and build numbers
it should allow overriding the aspect for specific versions and
channels.
Bug: 379999838
Test: n/a
Change-Id: If8bf38a2a3b77809580bfd28600f63242efa5fca
AOSP: 8f1fc345c9f4b7a9528f983a2b4426a15ff57a3d

[AOSP-pick] Enable altering the location of aspect files

---

CHANGELOG
aspect/intellij_info_impl.bzl
base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
kotlin/src/com/google/idea/blaze/kotlin/KotlinBlazeRules.java

V2024.11.19 hotfix 2

---

CHANGELOG
aspect/intellij_info_impl.bzl
base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
kotlin/src/com/google/idea/blaze/kotlin/KotlinBlazeRules.java

V2024.12.03 hotfix

---

tools/bump_major/main.go

internal: introduce 'add new major version script'

---

.bazelci/android-studio.yml
.bazelci/aspect.yml
.bazelci/clion.yml
.bazelci/intellij-ue.yml
.bazelci/intellij.yml

(cherry picked from commit 36fc091c69cd991d4923254b37f75ad7e656e46f)

[google] Update testing platforms for ubuntu

---

examples/java/greetings_project/.bazelrc
examples/java/greetings_project/MODULE.bazel
examples/java/greetings_project/MODULE.bazel.lock
examples/java/greetings_project/WORKSPACE

Fixes https://github.com/bazelbuild/intellij/issues/7148

Use bzlmod in java example

---

querysync/java/com/google/idea/blaze/qsync/AffectedPackagesCalculator.java

Fix qsync NPE

---

base/src/META-INF/blaze-base.xml
java/src/META-INF/java-contents.xml

Cherry pick AOSP commit [6c2b2d9c8fb1a83009b49a28432b0a6400f6a71b](https://cs.android.com/android-studio/platform/tools/adt/idea/+/6c2b2d9c8fb1a83009b49a28432b0a6400f6a71b).
(cherry picked from commit 07c85a3e226c35c6f488760572bf9fe7308d8526)
(with fixups to cover new code)
GitOrigin-RevId: af77ae2b1a15450c2e9d8defd2f8aa310ebe25d5
Change-Id: Ia68206973a31e1b7750a6a9a400ba72b87e3a63e
AOSP: 6c2b2d9c8fb1a83009b49a28432b0a6400f6a71b

[AOSP-pick] [all] plugin.xml: replace <reference> `id` with `ref` (IJPL-171993)

---

ijwb/ijwb.bazelproject

Update ij_product in ijwb.bazelproject

---

CHANGELOG

Update CHANGELOG for v2025.01.21 release

---

aswb/src/com/android/tools/idea/rendering/tokens/BazelBuildSystemFilePreviewServices.java
aswb/src/com/google/idea/blaze/android/projectsystem/BlazeModuleSystemBase.java

Cherry pick AOSP commit [f3e881aec1ed3f4acafb462b99e1421fc8ccf702](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f3e881aec1ed3f4acafb462b99e1421fc8ccf702).
Bug: n/a
Test: n/a
Change-Id: I805164b169db6c4bb35ec0e769fc99bad7c8f2cb
AOSP: f3e881aec1ed3f4acafb462b99e1421fc8ccf702

[AOSP-pick] Extract render services project system api

---

CODEOWNERS

Add @LeFrosch and @ujohnny as code owners

Modify CODEOWNERS

---

aswb/tests/utils/integration/com/google/idea/blaze/android/targetmapbuilder/BlazeInfoData.java

Cherry pick AOSP commit [ebc27d197e2e564415b327b82066d01088574215](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ebc27d197e2e564415b327b82066d01088574215).
Make it explicit.
Bug: n/a
Test: n/a
Change-Id: Id64cb7584debecb6229b7fd0193a20e383ee5559
AOSP: ebc27d197e2e564415b327b82066d01088574215

[AOSP-pick] BlazeInfoData is an immutable singleton

---

clwb/tests/projects/external_includes/MODULE.bazel
clwb/tests/projects/llvm_toolchain/MODULE.bazel
clwb/tests/projects/simple/MODULE.bazel
clwb/tests/projects/virtual_includes/MODULE.bazel

updating rules_cc to fix broken integration tests pipeline

---

base/src/com/google/idea/blaze/base/buildview/BuildViewMigration.kt
base/src/com/google/idea/blaze/base/toolwindow/ToolWindowTabs.java

Add gotit tooltip to promote the new sync view

---

java/src/com/google/idea/blaze/java/qsync/BlazeJavaQuerySyncPlugin.java
java/src/com/google/idea/blaze/java/sync/BlazeJavaSyncPlugin.java
java/src/com/google/idea/blaze/java/sync/JavaLanguageLevelHelper.java
java/src/com/google/idea/blaze/java/sync/projectstructure/Jdks.java

details.
Issue number: https://github.com/bazelbuild/intellij/issues/7298

More customary to IJ error reporting for cases when required JDK is missing

---

base/src/com/google/idea/blaze/base/build/BlazeBuildService.java
base/src/com/google/idea/blaze/base/qsync/BazelAppInspectorBuilder.java
base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/src/com/google/idea/blaze/base/qsync/BazelRenderJarBuilder.java
base/src/com/google/idea/blaze/base/sync/BuildPhaseSyncTask.java
base/src/com/google/idea/blaze/base/sync/SyncPhaseCoordinator.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeIdeInterfaceAspectsImpl.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java
plugin_dev/src/com/google/idea/blaze/plugin/run/BuildPluginBeforeRunTaskProvider.java

Cherry pick AOSP commit [8c2d4549999b5cdcb0f47dea084ac76e38330f1f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/8c2d4549999b5cdcb0f47dea084ac76e38330f1f).
to make it extractable into an interface
Bug: n/a
Test: n/a
Change-Id: I1d8651f1ea3cdfea7111fa69a33fa17c50b555b1
AOSP: 8c2d4549999b5cdcb0f47dea084ac76e38330f1f

[AOSP-pick] Encapsulate buildResult field

---

aswb/src/com/google/idea/blaze/android/run/runner/BlazeAndroidDeviceSelector.java
aswb/src/com/google/idea/blaze/android/run/runner/BlazeAndroidRunConfigurationRunner.java

Cherry pick AOSP commit [2fcf730c0a62e6162fd2409afefbc4ad896edc7c](https://cs.android.com/android-studio/platform/tools/adt/idea/+/2fcf730c0a62e6162fd2409afefbc4ad896edc7c).
Bug: 323568263
Test: n/a
Change-Id: I121bc275c7841a1e8bf85e026fd6f8acdb155c84
AOSP: 2fcf730c0a62e6162fd2409afefbc4ad896edc7c

[AOSP-pick] Clean up DeployTarget interface

---

base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java

Rename Android Studio handler to Bazel handler in run configs

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
base/src/com/google/idea/blaze/base/command/CommandLineBlazeCommandRunner.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBlazeCommandRunner.java

Cherry pick AOSP commit [225cf7702db7ebc53648bf2698e54fc12ba523ac](https://cs.android.com/android-studio/platform/tools/adt/idea/+/225cf7702db7ebc53648bf2698e54fc12ba523ac).
Bug: n/a
Test: n/a
Change-Id: I6595886ea1cdd4590dc24b03083a8b6676649bb2
AOSP: 225cf7702db7ebc53648bf2698e54fc12ba523ac

[AOSP-pick] Cleanup BlazeBuildOutputs instantiation

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.java
base/src/com/google/idea/blaze/base/command/buildresult/bepparser/ParsedBepOutput.java

Cherry pick AOSP commit [a069fba218da28dacea1cd3231287ffb538c40ca](https://cs.android.com/android-studio/platform/tools/adt/idea/+/a069fba218da28dacea1cd3231287ffb538c40ca).
as it prevent migration to a different api.
Bug: n/a
Test: n/a
Change-Id: I93fa4f8a605409514f86e5ed354b058e71e323ec
AOSP: a069fba218da28dacea1cd3231287ffb538c40ca

[AOSP-pick] Drop log only localExecRoot property

---

aswb/src/com/google/idea/blaze/android/run/deployinfo/BlazeApkDeployInfoProtoHelper.java
base/src/com/google/idea/blaze/base/sync/aspects/BlazeBuildOutputs.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationRunner.java
java/src/com/google/idea/blaze/java/fastbuild/FastBuildServiceImpl.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java

Cherry pick AOSP commit [abb8479a68846d6a51fe48c2d77617cd8cf182d2](https://cs.android.com/android-studio/platform/tools/adt/idea/+/abb8479a68846d6a51fe48c2d77617cd8cf182d2).
Bug: n/a
Test: n/a
Change-Id: I3bf09dfbf7b0123229056e30169878f618f7d6af
AOSP: abb8479a68846d6a51fe48c2d77617cd8cf182d2

[AOSP-pick] Clean up and Java docs

---

base/tests/unittests/com/google/idea/blaze/base/sync/workspace/ExecutionRootPathResolverTest.java
base/tests/utils/unit/com/google/idea/blaze/base/BlazeTestCase.java

details.
mark Registry as loaded in non-application tests

address uninitialized registry warnings

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java

Cherry pick AOSP commit [92dc691ea5a4f1a70774b704fa5c647b49e15a79](https://cs.android.com/android-studio/platform/tools/adt/idea/+/92dc691ea5a4f1a70774b704fa5c647b49e15a79).
Bug: n/a
Test: n/a
Change-Id: I17cfa05707db7ed17b54e1d68cda7792698a6936
AOSP: 92dc691ea5a4f1a70774b704fa5c647b49e15a79

[AOSP-pick] Expose QuerySyncProject deps to tests

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java

Cherry pick AOSP commit [d542ecbebf8230ff0359c3b160730f0ab6da85ec](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d542ecbebf8230ff0359c3b160730f0ab6da85ec).
STAT (diff to AOSP): 28 insertions(+), 29 deletion(-)
so that aspect integration tests could invoke aspect in an environment
closer to the real one.
Bug: n/a
Test: n/a
Change-Id: I0448e1e40564610f012edf3c703544485e98e3d1
AOSP: d542ecbebf8230ff0359c3b160730f0ab6da85ec

[AOSP-pick] Expose Bazel command from BazelDependencyBuilder

---

base/src/com/google/idea/blaze/base/command/buildresult/bepparser/BepParser.kt

Cherry pick AOSP commit [4eb05a163330913173c64225660847ab2b909db3](https://cs.android.com/android-studio/platform/tools/adt/idea/+/4eb05a163330913173c64225660847ab2b909db3).
into file set traversal and output artifact conversion.
Bug: n/a
Test: n/a
Change-Id: I6e52035f323323b4612a5fb365ffca01030109d7
AOSP: 4eb05a163330913173c64225660847ab2b909db3

[AOSP-pick] Split traverseFileSets

---

common/experiments/src/com/google/idea/common/experiments/ExperimentServiceImpl.java

Cherry pick AOSP commit [d6ba729c51980b921725db7e32570d1d3bf6c14f](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d6ba729c51980b921725db7e32570d1d3bf6c14f).
caused by build and version retrieval.
Bug: n/a
Test: n/a
Change-Id: I84d2f904e7e277d81730cac75049718987c09c17
AOSP: d6ba729c51980b921725db7e32570d1d3bf6c14f

[AOSP-pick] Fix experiment service performance issues

---

base/src/com/google/idea/blaze/base/qsync/BazelDependencyBuilder.java
base/tests/integrationtests/com/google/idea/blaze/base/qsync/BazelDependencyBuilderTest.java

Cherry pick AOSP commit [4787de10edb6db084158310a0d358884e81f1b11](https://cs.android.com/android-studio/platform/tools/adt/idea/+/4787de10edb6db084158310a0d358884e81f1b11).
STAT (diff to AOSP): 4 insertions(+), 4 deletion(-)
so that more can be added to the list.
Bug: 330348550
Test: SyncedInBazelProjectTest
Change-Id: I1374254b460229b647c992fc9e70786178bdac2b
AOSP: 4787de10edb6db084158310a0d358884e81f1b11

[AOSP-pick] Separate preparing and updating aspect files

---

base/src/com/google/idea/blaze/base/qsync/DependencyTracker.java
base/src/com/google/idea/blaze/base/qsync/DependencyTrackerImpl.java

Cherry pick AOSP commit [f56b821d8cb7e18e8241dfa6692433996b744c06](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f56b821d8cb7e18e8241dfa6692433996b744c06).
Bug: n/a
Test: n/a
Change-Id: Ia098cf97e93da64a93e7a812cc4f651e05802fb9
AOSP: f56b821d8cb7e18e8241dfa6692433996b744c06

[AOSP-pick] Delete SINGLE_TARGET case as unused

---

examples/python/simple_code_generator/MODULE.bazel
examples/python/simple_code_generator/rules/rules.bzl

details.
Issue number: N/A
This change will update the Python `simple_code_generator` so that it works with more recent versions of `rules_python`.

update python example to more recent version of rules_python

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncHighlightingFilter.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncHighlightingSettingProvider.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncManager.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java
base/src/com/google/idea/blaze/base/qsync/QuerySyncTrafficLightRendererContributor.java

Cherry pick AOSP commit [ca0333739e9febb40d1ea26b9acc022904be8108](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ca0333739e9febb40d1ea26b9acc022904be8108).
STAT (diff to AOSP): 1 insertions(+), 1 deletion(-)
Bug: n/a
Test: existing
Change-Id: Ia2ed299fb775bb4ac14988f6b9b70566eb1a1efe
AOSP: ca0333739e9febb40d1ea26b9acc022904be8108

[AOSP-pick] isReadyForAnalysis needs only a virtual file

---

aswb/src/com/google/idea/blaze/android/projectsystem/BazelModuleDependencies.java

Cherry pick AOSP commit [cc82106eebb10774b4e10ef2108754781d287da9](https://cs.android.com/android-studio/platform/tools/adt/idea/+/cc82106eebb10774b4e10ef2108754781d287da9).
Bug: 391967656
Test: n/a (this is being replaced with new UI tools integration)
Change-Id: I9d650930baea446a2b0deac9b06dce3dec1564e4
AOSP: cc82106eebb10774b4e10ef2108754781d287da9

[AOSP-pick] Fix NPE

---

aswb/src/com/google/idea/blaze/android/resources/BlazeLightResourceClassService.java

Cherry pick AOSP commit [aa24429759671ef9d08dad3cb59a1267b39f81b7](https://cs.android.com/android-studio/platform/tools/adt/idea/+/aa24429759671ef9d08dad3cb59a1267b39f81b7).
Remove experiment from the source code and always enable.
Bug: 391569121
Bug: 150960389
Test: Manually build and run ASwB with this change
Change-Id: If6f6303e316ffb43e2687e808dc71005be1e815c
AOSP: aa24429759671ef9d08dad3cb59a1267b39f81b7

[AOSP-pick] Remove aswb.workspace.light.class.enabled experiment

---

java/tests/integrationtests/com/google/idea/blaze/java/run/producers/NonBlazeProducerConfigurationTest.java

Cherry pick AOSP commit [bbcd3cc814677b3fcc6e97053e6be250c52027d8](https://cs.android.com/android-studio/platform/tools/adt/idea/+/bbcd3cc814677b3fcc6e97053e6be250c52027d8).
Bug: 393230483
Test: Unit tests added
Change-Id: I81551414580af2899fd979b143c7c8b7f42a75af
AOSP: bbcd3cc814677b3fcc6e97053e6be250c52027d8

[AOSP-pick] Producers for Screenshot test Gradle Run Configuration

---

aspect/build_dependencies.bzl
aspect/build_dependencies_deps.bzl

Cherry pick AOSP commit [f0de95f22de16ec0c789feb3093382ae398a0e8b](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f0de95f22de16ec0c789feb3093382ae398a0e8b).
Bug: n/a
Test: n/a
Change-Id: Ib2e6b5e82c779d08963ea581405215ab24c7cc55
AOSP: f0de95f22de16ec0c789feb3093382ae398a0e8b

[AOSP-pick] Extract IDE_JAVA_PROTO bazel sync interface

---

testing/test_deps/test_deps_bazel_artifacts.bzl

Cherry pick AOSP commit [0a28b0e1a85c5155d68a506df88510ce53a9c481](https://cs.android.com/android-studio/platform/tools/adt/idea/+/0a28b0e1a85c5155d68a506df88510ce53a9c481).
Bug: n/a
Test: n/a
Change-Id: I85c4f75908e614e2789852acac15527462a2771f
AOSP: 0a28b0e1a85c5155d68a506df88510ce53a9c481

[AOSP-pick] Sort ASwB test deps

---

examples/scala/with_bzlmod/MODULE.bazel
examples/scala/with_bzlmod/MODULE.bazel.lock
examples/scala/with_bzlmod/hello/BUILD
examples/scala/with_bzlmod/hello/Hello.scala
examples/scala/with_bzlmod/hello/HelloApp.scala
examples/scala/with_bzlmod/hello/HelloTest.scala

This should be useful to reproduce #7374 and other Scala issues.

Added an example Scala project with Bzlmod.

---

examples/kotlin/simple_project/.bazelrc

Fixes https://github.com/bazelbuild/intellij/issues/7501

Set Java version in kotlin example project

---

base/src/META-INF/blaze-base.xml

Cherry pick AOSP commit [f55329db1fc7be2c203d34b5edb16f63d7c58acc](https://cs.android.com/android-studio/platform/tools/adt/idea/+/f55329db1fc7be2c203d34b5edb16f63d7c58acc).
Bug: n/a
Test: n/a
Change-Id: Ifd9fc88c139a0d91a732de7468f53733afb7da42
AOSP: f55329db1fc7be2c203d34b5edb16f63d7c58acc

[AOSP-pick] Fix invalidate caches contributor registration

---

base/src/com/google/idea/blaze/base/qsync/QuerySyncProject.java

Cherry pick AOSP commit [3621a66aaed39df2e68c4873965e38de91ca3950](https://cs.android.com/android-studio/platform/tools/adt/idea/+/3621a66aaed39df2e68c4873965e38de91ca3950).
to simplify debugging.
Bug: n/a
Test: existing (pure refactoring)
Change-Id: Idcaa586fe9ec9ca43fbe1f6ea9391322521e7f07
AOSP: 3621a66aaed39df2e68c4873965e38de91ca3950

[AOSP-pick] Extract updateProjectSnapshot method

---

base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolUtils.java

Cherry pick AOSP commit [a64230339f8a44540f0456d777952ccdc9074432](https://cs.android.com/android-studio/platform/tools/adt/idea/+/a64230339f8a44540f0456d777952ccdc9074432).
This change was introduced in I3fa6311a269bbc18af9118de81d29d1eb73078f7.
Bug:n/a
Test: n/a
Change-Id: I38d16863f8cc6351266eea3c17447d418c703a6d
AOSP: a64230339f8a44540f0456d777952ccdc9074432

[AOSP-pick] Revert unnecessary change

---

CHANGELOG

Update CHANGELOG for  v2025.04.01 release

---

base/src/com/google/idea/blaze/base/buildview/BazelExecService.kt
clwb/clwb.bazelproject
ijwb/ijwb.bazelproject
plugin_dev/src/com/google/idea/blaze/plugin/run/BlazeIntellijPluginDeployer.java

Disable curses on windows and fix the BlazeIntellijPluginDeployer.

Windows fixes

---

querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java

Cherry pick AOSP commit [79d2c3816f073620abb730547c4158fad211d69e](https://cs.android.com/android-studio/platform/tools/adt/idea/+/79d2c3816f073620abb730547c4158fad211d69e).
Bug: Not applicable
Test: Not applicable
Change-Id: I77199b3f536bf176175825a8e68e6d187e1e7cbb
AOSP: 79d2c3816f073620abb730547c4158fad211d69e

[AOSP-pick] Sort the rules

---

aswb/tests/utils/unit/com/android/ide/common/repository/GoogleMavenArtifactIdHelper.java

Cherry pick AOSP commit [d3a3facacbc7782233fbc4199bffb2c6ce5f961c](https://cs.android.com/android-studio/platform/tools/adt/idea/+/d3a3facacbc7782233fbc4199bffb2c6ce5f961c).
Bug: none filed
Test: existing
Change-Id: I76fd9169dd5cc9fb99a145511f7fb0785b0050f3
AOSP: d3a3facacbc7782233fbc4199bffb2c6ce5f961c

[AOSP-pick] Inline used-once utility

---

base/src/com/google/idea/blaze/base/qsync/BazelQueryRunner.java
querysync/java/com/google/idea/blaze/qsync/PartialProjectRefresh.java
querysync/java/com/google/idea/blaze/qsync/QuerySyncProjectSnapshot.java
querysync/java/com/google/idea/blaze/qsync/project/PostQuerySyncData.java
querysync/java/com/google/idea/blaze/qsync/query/QuerySummary.java
querysync/java/com/google/idea/blaze/qsync/query/QuerySummaryImpl.java
querysync/java/com/google/idea/blaze/qsync/util/QuerySummarizer.java
querysync/javatests/com/google/idea/blaze/qsync/AffectedPackagesTest.java
querysync/javatests/com/google/idea/blaze/qsync/PartialProjectRefreshTest.java
querysync/javatests/com/google/idea/blaze/qsync/ProjectRefresherTest.java
querysync/javatests/com/google/idea/blaze/qsync/QuerySyncTestUtils.java
querysync/javatests/com/google/idea/blaze/qsync/TestDataSyncRunner.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySummaryTest.java
querysync/javatests/com/google/idea/blaze/qsync/query/QuerySummaryTestBuilder.java

Cherry pick AOSP commit [8053b5eab71ad04b32fc5102b1aa5f99333f3ce7](https://cs.android.com/android-studio/platform/tools/adt/idea/+/8053b5eab71ad04b32fc5102b1aa5f99333f3ce7).
STAT (diff to AOSP): 51 insertions(+), 37 deletion(-)
Bug: n/a
Test: n/a
Change-Id: I3e5907222f4dd80e05e1d5fb676ee64d829083fe
AOSP: 8053b5eab71ad04b32fc5102b1aa5f99333f3ce7

[AOSP-pick] Make it clear what QuerySummary is

---

base/src/com/google/idea/blaze/base/bazel/AbstractBuildInvoker.java
base/src/com/google/idea/blaze/base/bazel/AbstractBuildInvoker1.java
base/src/com/google/idea/blaze/base/bazel/BazelBuildSystem.java
base/src/com/google/idea/blaze/base/bazel/BuildSystem.java
base/src/com/google/idea/blaze/base/bazel/LocalInvoker.java
base/tests/unittests/com/google/idea/blaze/base/sync/sharding/BlazeBuildTargetSharderTest.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/BuildSystemProviderWrapper.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildInvoker.java
base/tests/utils/unit/com/google/idea/blaze/base/bazel/FakeBuildSystem.java

Cherry pick AOSP commit [dbd082f2619480edf8c3d89dc96e5ded925c9537](https://cs.android.com/android-studio/platform/tools/adt/idea/+/dbd082f2619480edf8c3d89dc96e5ded925c9537).
STAT (diff to AOSP): 1 insertions(+), 1 deletion(-)
Pure refactor, removes some unnecesasry methods from the BuildSystem for the cleanup.
Bug: n/a
Test: n/a
Change-Id: If9346d6f1ea0d549f2062d22469b8b5df089fdd5
AOSP: dbd082f2619480edf8c3d89dc96e5ded925c9537

[AOSP-pick] Remove unnecessary methods

---

base/src/com/google/idea/blaze/base/qsync/action/BuildDependenciesAction.java
querysync/java/com/google/idea/blaze/qsync/BlazeQueryParser.java
querysync/java/com/google/idea/blaze/qsync/GraphToProjectConverter.java
querysync/java/com/google/idea/blaze/qsync/QuerySyncProjectSnapshot.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphDataImpl.java
querysync/java/com/google/idea/blaze/qsync/project/DepsGraph.java
querysync/javatests/com/google/idea/blaze/qsync/project/BuildGraphDataTest.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/BuildGraphs.java

Cherry pick AOSP commit [ba4956357370ed2f5d626a7ced5ee89fb695131e](https://cs.android.com/android-studio/platform/tools/adt/idea/+/ba4956357370ed2f5d626a7ced5ee89fb695131e).
STAT (diff to AOSP): 9 insertions(+), 11 deletion(-)
to make it easier to understand what it is responsible for.
Bug: n/a
Test: n/a
Change-Id: I6530ac248ab83ff8a2e98109f2e78a93b1efc7ed
AOSP: ba4956357370ed2f5d626a7ced5ee89fb695131e

[AOSP-pick] Extract `BuildGraphData` interface

---

aswb/testdata/projects/gensrcjars/gen_srcjar.bzl
aswb/testdata/projects/gensrcjars/java/com/example/jar2/Jar2Class.java_
querysync/java/com/google/idea/blaze/qsync/java/AddProjectGenSrcJars.java
querysync/javatests/com/google/idea/blaze/qsync/java/AddProjectGenSrcJarsTest.java

Cherry pick AOSP commit [247d3f47040653b98651eed9a8004a98b96b91de](https://cs.android.com/android-studio/platform/tools/adt/idea/+/247d3f47040653b98651eed9a8004a98b96b91de).
And update and add tests.
Bug: 314330462
Bug: 293497337
Bug: 317709068
Bug: 314330462
Test: //tools/vendor/google3/aswb/javatests/com/google/
devtools/intellij/blaze/plugin/
aswb:query_sync_integration_tests
//tools/adt/idea/aswb/querysync/javatests/com/google/
idea/blaze/qsync/...
Change-Id: I3ba6b436493fc086da92628c35f8b08af9999358
AOSP: 247d3f47040653b98651eed9a8004a98b96b91de

[AOSP-pick] Unzip generated sources for project structure

---

testing/test_deps/projects/.gitignore
testing/test_deps/projects/MODULE.bazel
testing/test_deps/projects/simple_proto/.bazelproject
testing/test_deps/projects/simple_proto/external/BUILD
testing/test_deps/projects/simple_proto/external/external.proto
testing/test_deps/projects/simple_proto/project/BUILD
testing/test_deps/projects/simple_proto/project/java/com/example/android/ProtoConsumer.java
testing/test_deps/projects/simple_proto/project/java/com/example/lib/ProtoConsumer.java
testing/test_deps/projects/simple_proto/project/lib.proto
testing/test_deps/test_deps.MODULE.bazel

Cherry pick AOSP commit [eef296f42116c534c704a17cb7f5dc2433c5525a](https://cs.android.com/android-studio/platform/tools/adt/idea/+/eef296f42116c534c704a17cb7f5dc2433c5525a).
Bug: 337007753
Test: n/a
Change-Id: Ic884761bb87b3c7bdbe8240d1afc1f480865c00f
AOSP: eef296f42116c534c704a17cb7f5dc2433c5525a

[AOSP-pick] Add a simple Java only test project for protobuf

---

MODULE.bazel
clwb/src/com/google/idea/blaze/clwb/run/BlazeDebuggerKind.java
intellij_platform_sdk/BUILD.idea251
intellij_platform_sdk/BUILD.ue251
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/smrunner/BlazeJavascriptWebTestEventsHandlerTest.java
javascript/tests/integrationtests/com/google/idea/blaze/javascript/run/smrunner/BlazeWebJavascriptTestEventsHandlerTest.java
scala/src/com/google/idea/blaze/scala/sync/BlazeScalaSyncPlugin.java
sdkcompat/v251/com/google/idea/sdkcompat/javascript/DelegatingTypeScriptConfigServiceCompat.java
sdkcompat/v251/com/google/idea/sdkcompat/javascript/TypeScriptConfigServiceAdapter.java
tools/maintenance/BUILD
tools/maintenance/maintenance.kt

Bump all versions and move the maintenance script to tools. Rules kotlin seem to be broken for running the binary target :c

Bump intellij SDK versions

---

.bazelci/clion.yml
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultParser.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncStartupActivity.java
clwb/BUILD
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
clwb/tests/headlesstests/com/google/idea/blaze/clwb/ExecutionTest.java
clwb/tests/headlesstests/com/google/idea/blaze/clwb/base/ClwbHeadlessTestCase.java
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.clion242
intellij_platform_sdk/BUILD.clion243
intellij_platform_sdk/BUILD.clion251
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
testing/src/com/google/idea/testing/headless/HeadlessTestCase.java

CLion fix run configuration

---

.bazelci/clion.yml
base/src/com/google/idea/blaze/base/command/buildresult/BuildResultParser.java
base/src/com/google/idea/blaze/base/sync/BlazeSyncStartupActivity.java
clwb/BUILD
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java
clwb/tests/headlesstests/com/google/idea/blaze/clwb/ExecutionTest.java
clwb/tests/headlesstests/com/google/idea/blaze/clwb/base/ClwbHeadlessTestCase.java
intellij_platform_sdk/BUILD
intellij_platform_sdk/BUILD.clion242
intellij_platform_sdk/BUILD.clion243
intellij_platform_sdk/BUILD.clion251
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java
testing/src/com/google/idea/testing/headless/HeadlessTestCase.java

(cherry picked from commit 74a11c458a29e7ca60465de4a9f3b0614bdfb335)

Cherry Pick: Fix CIDR and PY runconfiguration runner AOSP regression (#7595)

---

.gitignore

details.
Add known masks for gitignore from https://github.com/github/gitignore/blob/main/Global/macOS.gitignore

add macOS specific files to gitignore

---

MODULE.bazel
MODULE.bazel.lock

chore: update IJ products to 2025.1.1

---

aswb/src/com/google/idea/blaze/android/run/binary/BlazeAndroidBinaryRunConfigurationHandlerProvider.java
aswb/src/com/google/idea/blaze/android/run/test/BlazeAndroidTestRunConfigurationHandlerProvider.java
base/src/com/google/idea/blaze/base/run/BlazeCommandRunConfiguration.java
base/src/com/google/idea/blaze/base/run/confighandler/BlazeCommandGenericRunConfigurationHandlerProvider.java
base/src/com/google/idea/blaze/base/run/confighandler/BlazeCommandRunConfigurationHandlerProvider.java
base/src/com/google/idea/blaze/base/run/confighandler/PendingTargetRunConfigurationHandler.java
base/src/com/google/idea/blaze/base/run/confighandler/PendingTargetRunConfigurationHandlerProvider.java
base/tests/integrationtests/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationGenericHandlerIntegrationTest.java
base/tests/integrationtests/com/google/idea/blaze/base/run/BlazeCommandRunConfigurationRunManagerImplTest.java
base/tests/utils/unit/com/google/idea/blaze/base/run/MockBlazeCommandRunConfigurationHandlerProvider.java
clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationHandlerProvider.java
golang/src/com/google/idea/blaze/golang/run/BlazeGoRunConfigurationHandlerProvider.java
java/src/com/google/idea/blaze/java/run/BlazeJavaRunConfigurationHandlerProvider.java
java/tests/unittests/com/google/idea/blaze/java/run/BlazeJavaRunProfileStateTest.java
python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationHandlerProvider.java

This reverts commit da8d881e96753fc30ef6f29a5a305f91804c04fa.
details.

Revert "Make run configurations configurable (#7275)"

---

querysync/javatests/com/google/idea/blaze/qsync/query/QuerySummaryTest.java
querysync/javatests/com/google/idea/blaze/qsync/testdata/buildincludes/sub/includes/includes.bzl
querysync/javatests/com/google/idea/blaze/qsync/testdata/buildincludes/sub/includes/includes2.bzl

Missing load statments for Bazel 9

---

base/src/com/google/idea/blaze/base/qsync/ProjectLoaderImpl.java
base/src/com/google/idea/blaze/base/sync/projectstructure/ContentEntryEditor.java
base/src/com/google/idea/blaze/base/sync/projectview/ImportRoots.java

Add project data directory to exclusion patterns as well

---

java/src/com/google/idea/blaze/java/run/BlazeJavaRunProfileState.java

details.
Issue number: #7682
partially revert AOSP changes to
the previous implementation
fixes #7682

java: fix broken debugger output

---

CHANGELOG

Update CHANGELOG for v2025.05.13 stable release

---

CHANGELOG

Update CHANGELOG for v2025.05.27 release

---

python/src/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategy.java

details.
Issue number: #6832
This doesn't solve the underlying problem, which still needs investigation. However, the offending import path will now be properly logged.

Catch and log the error when there are dots in a qualified name

---

base/src/com/google/idea/blaze/base/sync/projectstructure/ModuleEditorImpl.java

Fixing removing incorectly detected iml file

---

MODULE.bazel
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalabinary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalalibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalamacrolibrary/BUILD
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalamacrolibrary/ScalaMacroLibraryTest.java
aspect/testing/tests/src/com/google/idea/blaze/aspect/scala/scalatest/BUILD

Updating rules_scala to 7.0.0 and switching back to official releases

---

CHANGELOG

Update CHANGELOG for v2025.06.10 release

---

CHANGELOG

Update changelog for v2025.06.24 release

---

MODULE.bazel
MODULE.bazel.lock

chore: update CLion 252 dependencies

---

CHANGELOG
base/src/com/google/idea/blaze/base/sync/libraries/ExternalLibraryManager.java
docs/hotswap.md
java/src/META-INF/java-contents.xml
java/src/com/google/idea/blaze/java/run/hotswap/BlazeHotSwapAction.java

Picks to v2025.06.24

---

MODULE.bazel
MODULE.bazel.lock
intellij_platform_sdk/BUILD.ue252

chore(SDK): update IJwB 252 dependencies

---

README.md

The PR adds a disclaimer to README file in accordance with the transfer agreement.

Plugin Transfer: added disclaimer to readme

---

.managed.bazelproject

This PR allows this project to be imported by the new Bazel plugin.

Update .manged.bazelproject for use with the new Bazel plugin

---

ijwb/BUILD

Changing ijwb plugin name to mark it as legacy

---

MODULE.bazel
MODULE.bazel.lock
tools/maintenance/maintenance.kt

Update platform versions for IJwB

---

CHANGELOG

Update CHANGELOG for v2025.09.19 release

---

MODULE.bazel
base/tests/integrationtests/com/google/idea/blaze/base/lang/buildfile/formatting/BuildFileFoldingBuilderTest.java
intellij_platform_sdk/BUILD.idea252
intellij_platform_sdk/BUILD.ue252

Update platform for 252
